.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH AR 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
ar \- verwaltet Funktionsbibliotheken
.SH SYNTAX 
.B ar
.RB [ dmpqrtx [ abi
.I Positionsname
.RB [ cilosuv ]]]
.I Archiv Datei ...
.SH BESCHREIBUNG
Mit 
.B ar
werden beliebig viele Dateien zu einer einzigen zusammengefasst.  Eine
Kompression findet nicht statt.
.I Archiv
ist der Name der zu bearbeitenden Archivdatei.  Die Archivdateien haben
per Konvention die Endung 
.BR .a .
.I Datei
ist der Name einer Datei, die in das Archiv eingefügt oder aus ihm
gelöscht werden soll.
.PP
.B ar
wird vor allem zur Verwaltung von Bibliotheken für den C-Compiler
verwendet.  Der Linker benötigt die spezielle Datei
.BR __.SYMDEF ,
in der die Symboltabellen aller Objektdateien zusammengefasst sind.  Mit
der Option 
.B \-s
wird diese Datei
erstellt und in das Archiv eingefügt.
.SH OPTIONEN
.TP
.B d
(delete)  löscht
.I Datei
aus dem
.I Archiv
.TP
.B m
(move) verschiebt die
.I Datei
nach
.RB ( a "fter) vor"
.RB ( b "efore) oder ersetzt sie anstelle"
.RB ( i "nstead) der Datei"
.TR Positionsname
.TP
.B p
(print) gibt die
.IR Datei
auf der Standardausgabe aus; die Zusatzoption 
.B v
(verbose) gibt den Dateinamen vor jeder Datei aus
.TP
.B q
(quick) fügt die
.IR Datei
in das
.IR Archiv
ein, ohne zu prüfen, ob die Datei schon vorhanden ist; durch die Zusatzoption 
.B c
wird die Warnung beim Erzeugen eines neuen Archivs unterdrückt
.TP
.B r
(replace)
.IR Datei
ersetzt den gleichnamigen Eintrag in
.IR Archiv ;
wenn noch kein Eintrag dieses Namens existiert, wird ein neuer angelegt
.TP
.B t
(table) gibt das Inhaltsverzeichnis aus; die zusätzliche Option 
.B v
lässt die ausführliche Version anzeigen
.TP
.B x
(extract)
.IR Datei
wird aus dem
.IR Archiv
herauskopiert
.TP
.B s
sorgt für Erstellung und Aktualisierung der Symboltabelle
.B __.SYMDEF
für den Linker, wie das Kommando
.B ranlib
.SH AUTOR
Viele, Free Software Foundation.

