.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH CHGRP 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"  
.SH BEZEICHNUNG 
chgrp \- (change group) ändert die Gruppenzugehörigkeit einer Datei
oder eines Verzeichnisses
.SH SYNTAX 
.B chgrp
.RB [ \-Rcfv ]
.RB [ \-\-recursive ]
.RB [ \-\-show-changes ]
.RB [ \-\-silent ]
.RB [ \-\-quiet ]
.RB [ \-\-verbose ]
.I Gruppe Datei ...
.SH BESCHREIBUNG
Der Befehl 
.B chgrp
ändert die Gruppenzugehörigkeit einer Datei oder eines Verzeichnisses.  Die
Benutzung von
.B chgrp
ist nur dem Eigentümer und dem Superuser (root) erlaubt.  Der Eigentümer
kann eine Datei nur den Gruppen zuordnen, denen er selbst auch angehört.
.PP
Die
.I Gruppe
kann als ganze Zahl oder als Name angegeben werden.  Die möglichen Gruppen
und ihre Kennzahlen sind in der Datei /etc/group festgelegt und können mit
.B id
angezeigt werden.
.SH OPTIONEN
.TP
.B \-c
(changes) diese Option zeigt die Dateien an, deren Gruppe geändert wird
.TP
.B \-f
(force) es werden keine Fehlermeldungen ausgegeben
.TP
.B \-v
(verbose) alle Aktionen werden angezeigt
.TP
.B \-R
(recursive) die Gruppenzugehörigkeit der Dateien in den Unterverzeichnissen
wird ebenfalls geändert
.SH "SIEHE AUCH"
.BR chmod (1),
.BR chown (1).
.SH AUTOR
David MacKenzie

