.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH CMP 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"     
.SH NAME 
cmp \-
(compare) vergleicht zwei Dateien byteweise
.SH SYNTAX 
.B cmp
.RB [ \-cls ]
.RB [ \-\-show-chars ]
.RB [ \-\-verbose ]
.RB [ \-\-silent]
.RB [ \-\-quiet ]
.I Datei1
.RI [ Datei2 ]
.SH BESCHREIBUNG
.B cmp
vergleicht zwei (binäre) Dateien und liefert die
dezimale Position des ersten Bytes, in dem sich die Dateien
unterscheiden, sowie die Zeilennummer zurück. Wird statt eines
Dateinamens \fB-\fP angegeben, so wird von der Standardeingabe
gelesen; wird nur eine Datei benannt, so wird anstelle der zweiten
ebenfalls von der Standardeingabe gelesen.
.SH OPTIONEN
.IP \fB-c\fP
(character) gibt die abweichenden Zeichen aus
.IP \fB-l\fP
(list) gibt die Position und den oktalen Wert aller
differierenden Zeichen in einer Liste aus
.IP \fB-s\fP
(silent) gibt nichts auf die Standardausgabe. Der Status ist 0
(wahr), wenn die Dateien übereinstimmen und 1 (falsch), wenn sie sich
unterscheiden
.SH SIEHE AUCH
\fBdiff\fP(info), \fBcomm\fP(1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Torbjorn Granlund und David MacKenzie

