.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH COMM 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
comm \- vergleicht zwei sortierte Dateien
.SH SYNTAX 
.B comm
.RB [ \-{1,2,3} ]
.I Datei1 Datei2
.SH BESCHREIBUNG
.B comm
vergleicht zwei sortierte Dateien, und gibt die gemeinsamen und die
verschiedenen Zeilen jeweils in Spalten aus.  Die erste Spalte enthält
die Zeilen, die nur in Datei1 enthalten sind.  Die zweite Spalte enthält
die Zeilen, die in beiden Dateien enthalten sind.  Die dritte Spalte
enthält schließlich die Zeilen, die nur in der zweiten Datei enthalten sind.
.PP
Ein
.B \-
anstelle eines Dateinamens steht für die Standardeingabe.
.SH OPTIONEN
.TP
.B \-{1,2,3}
unterdrückt die erste, zweite bzw. dritte Spalte
.SH "SIEHE AUCH"
.BR diff (info),
.BR cmp (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Richard Stallman und David MacKenzie

