.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH CP 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
cp \-
(copy) kopiert eine oder mehrere Dateien
.SH SYNTAX        
.B cp
.RI [ Optionen ]
.I Quelle Ziel
.sp
.B cp
.RI [ Optionen ]
.I Quelle ... Verzeichnis
.SH OPTIONEN
.TP
.B \-a
(archiv) das gleiche wie -dpR
.TP
.B \-b
(backup) sichert Dateien im Zielverzeichnis vor dem Überschreiben
.TP
.B \-d
(no-dereference) kopiert die Links und nicht die Dateien,
auf die der Link zeigt
.TP
.B \-f
(force) Dateien im Zielverzeichnis werden überschrieben
.TP
.B \-i
(interactive) erwartet Bestätigung vor dem Überschreiben bereits existierender
Dateien
.TP
.B \-l
(link) macht Links anstelle von Kopien (nur bei normalen Dateien)
.TP
.B \-P
(path) die Quelldateien werden mit Pfad relativ zum Zielverzeichnis
kopiert
.TP
.B \-p
(preserve) erhält die Zugriffsrechte und Eigentümer des Originals (nicht die
SUID und SGID Bits)
.TP
.B \-r
kopiert die Dateien der Unterverzeichnisse mit
.TP
.B \-s
(symbolic link) macht symbolische Links anstelle von Kopien (absolute
Pfadnamen)
.TP
.B \-u
(update) überschreibt Ziel- nur durch neuere Quelldateien
.TP
.B \-v
(verbose) 
.TP
.B \-x
(one file-system) ignoriert Unterverzeichnisse, die in anderen
Dateisystemen angesiedelt sind
.TP
.B \-R
(recursive)
.TP
.BI \-S " Endung"
(Endung) sichert die Dateien vor dem Überschreiben durch Umbenennung mit der
.IR Endung "; Voreinstellung ist"
.B ~
.TP
.BR \-V " {" numbered ", " existing ", " simple "}"
(version-control) erhält auch frühere Versionen
einer Datei, indem jeweils neue Backups erzeugt werden.
Die Art der Backups kann auch durch die Umgebungsvariable
.B VERSION_CONTROL
bestimmt werden. Die Option
.BR \-V " überschattet " VERSION_CONTROL .
Wenn weder die Option noch die Environmentvariable gesetzt sind, wird
.I existing
benutzt. Gültige Werte für
.BR VERSION_CONTROL " sind:"
.RS
.TP
.B numbered
Backups werden nummeriert
.TP
.B existing
Backups werden nur für Dateien nummeriert die bereits
nummerierte Backups haben.
.TP
.B simple
es werden immer einfache Backups gemacht
.RE
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
Torbjorn Granlund, David MacKenzie und Jim Meyering

