.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH CSPLIT 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
csplit \-
(context split) teilt eine Datei in mehrere Teile
.SH SYNTAX  
.B csplit
.RB [ \-sk ]
.RB [ \-f
.IR  Prefix ]
.RB  [ \-n
.IR  Stellen ] 
.RB [ \-\-prefix=
.IR Prefix ]
.RB [ \-\-digits=
.IR Stellen ]
.RB [ \-\-quiet ]
.RB [ \-\-silent ]
.RB [ \-\-keep-files ]
.I Datei Muster ...
.SH BESCHREIBUNG
.B csplit
liest aus
.I Datei
oder aus der Standardeingabe, wenn als Datei
.B \-
angegeben wird und gibt den Inhalt in mehrere Dateien aus. Der Inhalt der
Ausgabedateien ist abhängig vom
.IR Muster ".  Die erste Zeile, in der das " Muster
vorkommt, wird zur ersten Zeile der nächsten Datei. Als {\it Muster\/}
kommen folgende in Frage:
.TP
.BI / Ausdruck /[ Offset "] {" Anzahl }
erzeugt eine Ausgabedatei, die alle Zeilen der Eingabe bis (ausschließlich)
zu der Zeile mit dem
.I Ausdruck
enthält. Wird zusätzlich eine Zahl
.BI { Anzahl }
in geschweiften Klammern angegeben, wird der Vorgang mit dem gleichen
.I Ausdruck
und dem verbleibenden Rest
.I Anzahl
mal wiederholt. Wird zusätzlich eine ganze Zahl mit einem führenden
.BR + " oder " \- "  als "
.I Offset
angegeben, so wird der Beginn der nächsten Datei um diese Anzahl Zeilen
verschoben.
.TP
.BI % Ausdruck %[ Offset "] {" Anzahl }
arbeitet im Prinzip wie die vorher beschriebene Option, mit der Abweichung,
daß keine Ausgabedatei erzeugt wird, dieser Teil der Eingabe also ingoriert
wird.
.TP
.I Nummer
(eine einfache ganze Zahl) als Muster erzeugt eine Ausgabedatei aus den
.I Nummer
folgenden Zeilen.
.PP
Die Namen der Ausgabedateien bestehen aus dem
.I Prefix
und einer normalerweise zweistelligen Zahl. Der Standard für
.I Prefix
.RB ist Bxx .
Tritt während der Ausführung von
.B csplit
ein Fehler auf, so werden die bis dahin angelegten Dateien gelöscht.
.SH OPTIONEN
.TP
.B \-s
(silent) die Ausgabe der Ausgabedateigröße wird unterdrückt
.TP
.B \-k
(keep) bei einem Abbruch von
.B csplit
werden die bereits angelegten Dateien nicht gelöscht 
.TP
.BI \-f " Prefix"
die Ausgabedateien erhalten den
.IR Prefix " als Namen"
.TP
.BI \-n " Stellen"
die Ausgabedateien erhalten Nummern mit der angegebenen Anzahl
.I Stellen
.SH "SIEHE AUCH"
.BR split (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Stuart Kemp und David MacKenzie

