.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH DD 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
dd \-
(disk dump) konvertiert Dateien für verschiedene
Speichermedien
.SH SYNTAX 
.B dd
.RB [ if=
.IR Datei ]
.RB [ of=
.IR Datei ]
.RB [ ibs=
.IR Bytes ]
.RB [ obs=
.IR Bytes ]
.RB [ bs=
.IR Bytes ]
.RB [ cbs=
.IR Bytes ]
.RB [ skip=
.IR Blöcke ]
.RB [ seek=
.IR Blöcke ]
.RB [ count=
.IR Blöcke ]
.RB [ conv=
.RB { ascii ,
.BR ebcdic ,
.BR ibm ,
.BR block ,
.BR unblock ,
.BR lcase ,
.BR ucase ,
.BR swab ,
.BR noerror ,
.BR notrunc ,
.BR sync }]
.SH BESCHREIBUNG
.B dd
liest eine Datei und schreibt den Inhalt mit wählbarer Blockgröße und
verschiedenen Konvertierungen.  Mit Hilfe dieses Kommandos können reguläre
Dateien ebenso wie ganze Disketten oder Festplattenpartitionen kopiert werden.
.SH OPTIONEN
.TP
.BI if= Datei
(input file) der Name der Eingabedatei (voreingestellt ist
die Standardeingabe)
.TP
.BI of= Datei
(output file) der Name der Ausgabedatei (voreingestellt ist die Standardausgabe)
.TP
.BI ibs= Schritt
(input block size) Blockgröße der Eingabedatei
.TP
.BI obs= Schritt
(output block size) Blockgröße der Ausgabedatei
.TP
.BI bs= Schritt
(block size) Blockgröße für Ein- und Ausgabedatei
.TP
.BI cbs= Schritt
(conversion block size) Blockgröße für Konvertierung
.TP
.BI skip= Blocks
.RI "ignoriert am Anfang die angegebene Anzahl " Blocks " von der Eingabe"
.TP
.BI seek= Blocks
.RI "unterdrückt am Anfang die Ausgabe der angegebenen Anzahl " Blocks
.TP
.BI count= Blocks
.RI "kopiert die angegebene Anzahl " Blocks
.TP
.BI conv= Konvertierung...
bestimmt die Art der Konvertierung.
.IR Konvertierung " ist dabei eine von:"
.RS
.TP
.B ascii
konvertiert EBCDIC nach ASCII 
.TP
.B ebcdic
konvertiert ASCII nach EBCDIC 
.TP
.B ibm
konvertiert ASCII nach big blue special EBCDIC 
.TP
.B block
schreibt Zeilen in Felder der Größe
.I cbs
und ersetzt das Zeilenende durch Leerzeichen.  Der Rest des Feldes
wird ebenfalls mit Leerzeichen aufgefüllt
.TP
.B unblock
ersetzt abschließende Leerzeichen eines Blocks der Größe
.IR cbs " durch ein Zeilenende"
.TP
.B lcase
wandelt Großbuchstaben in Kleinbuchstaben
.TP
.B ucase
wandelt Kleinbuchstaben in  Großbuchstaben
.TP
.B swab
vertauscht je zwei Bytes der Eingabe.  Wenn die Anzahl der gelesenen
Bytes ungerade ist, wird das letzte Byte einfach kopiert
.TP
.B noerror
ignoriert Lesefehler
.TP
.B sync
.RB "füllt Eingabeblöcke bis zur Größe von " ibs " mit Nullen"
.RE
.SH BEISPIEL
Das Kommando
.sp
dd bs=8192 if=Image of=/dev/fd0
.sp
wird verwendet, um die fertig übersetzte Kerneldatei (Image) auf eine
formatierte Diskette zu schreiben und so eine Bootdiskette zu erzeugen.
.PP
Mit dem Kommando
.sp
dd if=/dev/hda of=/dev/fd0 bs=512 count=1
.sp
kann der Superuser (root) eine Kopie des Festplattenbootsektors
auf einer Diskette anlegen.  Mit dieser Diskette kann die
Festplatte gebootet werden, wenn der Festplattenbootsektor zerstört
wurde.
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
Paul Rubin, David MacKenzie und Stuart Kemp

