.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH DF 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
df \-
(disk free) zeigt den freien Festplattenplatz 
.SH SYNTAX 
.B df
.RB [ \-aikPv ]
.RB [ \-t
.IR fstype ]
.RB [ \-\-all ]
.RB [ \-\-inodes ]
.RB [ \-\-type
.IR fstype ]
.RB [ \-\-kilobytes ]
.RB [ \-\-portability ]
.RI [Pfad ...]
.SH BESCHREIBUNG
.B df
zeigt den freien Festplattenplatz für
das Dateisystem in dem das Verzeichnis \fIPfad\fP angesiedelt ist.
Wenn kein Verzeichnis angegeben ist, wird der freie Platz für alle
aufgesetzten Dateisysteme angezeigt. Die Angabe erfolgt in Kilobyte,
wenn nicht die Umgebungsvariable \fBPOSIXLY_CORRECT\fP gesetzt ist.
In diesem Fall wird der freie Platz in 512--Byte Sektoren angezeigt.
.PP
Wird als \fIPfad\fP der absolute Name der Gerätedatei eines aufgesetzten Dateisystems angegeben, so
wird der freie Platz auf diesem Gerät (Partition einer Festplatte) angegeben und nicht der des Dateisystem,
in dem sich die Gerätedatei befindet. Der freie Platz auf einem abgesetzten
Dateisystem ist auf diese Weise nicht zu ermitteln. 
.IP \fB-a\fP
(all) zeigt alle Dateisysteme an, einschließlich der mit 0 Bytes
Kapazität und der vom Typ \fBignore\fP oder \fBauto\fP
.IP \fB-i\fP
(inodes) zeigt die Auslastung der Inodes anstelle der Blockauslastung
.IP \fB-k\fP
(kilobytes) zeigt den freien Platz in Kilobyteblöcken,
auch wenn die Umgebungsvariable \fBPOSIXLY_CORRECT\fP gesetzt ist
.IP \fB-P\fP
(portability) erzwingt die Ausgabe in einer Zeile pro Dateisystem
.IP "\fB-t \fIFstyp\fR"
(type) schränkt die Ausgabe auf die Dateisysteme vom Typ
\fIFstyp\fP ein
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

