.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH DOSHELL 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
.B doshell
startet eine Shell auf einem (virtuellen) Port ohne \fBlogin\fP
.SH SYNTAX 
.B doshell
.I "Port Shell"
.SH BESCHREIBUNG
.B doshell
ermöglicht es, auch auf den (virtuellen) Terminals, auf denen von
.BR init " keine"
.BR getty -Prozesse
gestartet wurden, und auf denen deshalb kein
.B login
möglich ist, eine Shell zu starten.  Die Umschaltung zwischen den virtuellen
Terminals erfolgt mit den Tastenkombinationen
.BR alt "-F1 bis"
.BR alt -F8.
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
Jim Wiegand

