.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH EXPAND 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH BEZEICHNUNG 
expand \-
ersetzt Tabulatorzeichen durch
Folgen von Leerzeichen
.SH SYNTAX  
.B expand
.RI  [ \-Tab1
.RB [ ,
.IR Tab2 ]
.RB [ ", " ...]]]
.RB  [ \-t
.I Tab1
.RB [ ,
.I Tab2
.RB [ ", " ...]]]
.RB [ \-i ]
.RB [ \-\-tabs=
.I Tab1
.RB [ ,
.I Tab2
.RB [ ", " ...]]]
.RB [ \-\-initial ]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B expand
liest eine Textdatei
und ersetzt alle Tabulatoren durch entsprechende Folgen von
Leerzeichen. In der Voreinstellung werden alle Tabulatoren ersetzt und
eine Tabellenbreite von 8 Zeichen angenommen. Backspace Zeichen werden
unverändert ausgegeben.
.PP
Wenn anstelle eines Dateinamens ein \fB-\fP, oder gar kein Dateiname
angegeben ist, wird von der Standardeingabe gelesen.
.SH OPTIONEN
.IP \fB-\fITab1\fR
setzt die Tabellenbreite für alle Spalten
auf \fITab1\fP anstelle von 8
.IP "\fB-\fITab1\fR, \fITab2\fR, ..."
setzt die erste
Tabellenspalte auf \fITab1\fP, die zweite auf \fITab2\fP und so
weiter; wenn im Text mehr Tabulatoren auftauchen als bei der Option
angegeben, werden alle folgenden Tabulatoren durch einzelne
Leerzeichen ersetzt
.IP "\fB-t \fITab1\fR..."
macht nichts anderes als die
oben beschriebenen Optionen
.IP \fB-i\fP
konvertiert nur die führenden Tabulatoren jeder Zeile
in Leerzeichen
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

