.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH EXPR 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch" 
.SH BEZEICHNUNG 
.B expr
(expression) bearbeitet einen Ausdruck
.SH SYNTAX 
.B expr
\fIAusdruck\fP ...
.SH BESCHREIBUNG
.B expr
bewertet oder berechnet einen oder
mehrere \fIAusdrücke\fP und gibt das Ergebnis auf die
Standardausgabe. Ein Ausdruck besteht aus Zahlen oder Zeichenketten,
die durch Operatoren verbunden sind.  Eine Zeichenkette braucht nicht
in Anführungszeichen eingeschlossen werden.  Ob eine Ziffernfolge als
Zeichenkette oder als Zahl bearbeitet wird, hängt vom Operator und der
Position der Ziffernfolge im Ausdruck ab.
.PP
Folgende Operatoren werden erkannt:
.IP \fB|\fP
\fIAusdruck1\fR|\fIAusdruck2\fR liefert \fIAusdruck1\fP, wenn
dieser nicht leer oder gleich 0 ist. Anderenfalls wird \fIAusdruck2\fP
ausgegeben.
.IP \fB&\fP
\fIAusdruck1\fR&\fIAusdruck2\fR ist gleich 0, wenn einer der
beiden Ausdrücke leer oder 0 ist. Sonst wird \fIAusdruck1\fP ausgegeben.
.TP
.BR < , <= , = , != , >= , >
Vergleicht zwei Ausdrücke und liefert 1, wenn die
Relation stimmt, anderenfalls 0. Es wird zuerst versucht, beide Ausdrücke
numerisch zu vergleichen. Wenn mindestens einer der Ausdrücke keinen
numerischen Wert hat, werden die Ausdrücke lexikografisch verglichen.
.IP "\fB+ - * / %\fP"
verknüpft die Ausdrücke arithmetisch. Wenn einer
der Ausdrücke keinen numerischen Wert hat, wird eine Fehlermeldung ausgegeben. 
Der % Operator liefert den Rest bei ganzzahliger Division (Modulo).
.IP \fB:\fP
\fIAusdruck1\fR:\fIAusdruck2\fR wendet den regulären \fIAusdruck2\fP auf die Zeichenkette \fIAusdruck1\fP an und liefert die
Anzahl der passenden Zeichen oder den, auf den von \fB\\(\fP und \fB\\)\fP eingeschlossenen Teil von {\it
Ausdruck2\/} passenden Teil von \fIAusdruck1\fP, zurück. Wenn der
\fIAusdruck2\fP auf \fIAusdruck1\fP nicht paßt, liefert der
Operator 0.
.PP
Der Status von \fBexpr\fP ist
.RS
.IP \fB0\fP
wenn der gesamte bewertete Ausdruck weder leer, noch 0 ist
.IP \fB1\fP
wenn der gesamte bewertete Ausdruck leer oder 0 ist
.IP \fB2\fP
wenn ein Fehler aufgetreten ist
.RE
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Mike Parker

