.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH FDFORMAT 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
fdformat \- formatiert eine Diskette (low-level)
.SH SYNTAX 
.B fdformat
.RB [ \-n ]
.I Gerätedatei
.SH BESCHREIBUNG
.B fdformat
formatiert eine Diskette.  Der Diskettentyp, die Kapazität und das
Laufwerk werden durch die entsprechende Gerätedatei ausgewählt.  In
der folgenden Liste sind die Gerätedateien mit den dazugehörenden
Diskettenformaten aufgeführt. Die Zahlen in Klammern sind die
Major/Minor Gerätenummern.
.TP
.B /dev/fd0D360
(2,20) Laufwerk A, 3.5 Zoll 369 KB
.TP
.B /dev/fd0H1440
(2,28) Laufwerk A, 3.5 Zoll 1440 KB
.TP
.B /dev/fd0Q720
(2,16) Laufwerk A, 3.5 Zoll 720 KB
.TP
.B /dev/fd0d360
(2,20) Laufwerk A, 5 1/4 Zoll 360 KB
.TP
.B /dev/fd0h1200
(2,8) Laufwerk A, 5 1/4 Zoll 1200 KB
.TP
.B /dev/fd0q720
(2,24) Laufwerk A, 5 1/4 Zoll 720 KB
.TP
.B /dev/fd1D360
(2,21) Laufwerk B, 3.5 Zoll 360 KB
.TP
.B /dev/fd1H1440
(2,29) Laufwerk B, 3.5 Zoll 1440 KB
.TP
.B /dev/fd1Q720
(2,17) Laufwerk B, 3.5 Zoll 720 KB
.TP
.B /dev/fd1d360
(2,21) Laufwerk B, 5 1/4 Zoll 360 KB
.TP
.B /dev/fd1h1200
(2,9) Laufwerk B, 5 1/4 Zoll 1200 KB
.TP
.B /dev/fd1q720
(2,25) Laufwerk B, 5 1/4 Zoll 720 KB
.PP
Auf der Diskette wird kein Dateisystem eingerichtet.  Dazu stehen die
Kommandos
.BR mkfs ", " mkxfs " und " mke2fs
für Linux Dateisysteme und
.B mformat
für MS-DOS Dateisysteme zur Verfügung.  Die roh formatierte Diskette
kann aber auch von
.B tar
direkt beschrieben werden.
.SH OPTIONEN
.TP
.B -n
unterdrückt die Verifizierung der formatierten Diskette
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Werner Almesberger

