.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH FIND 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
find \- sucht nach bestimmten Dateien
.SH SYNTAX 
.B find
.RI [ Verzeichnis ]
.RI [ \-Option ...]
.RI  [ \-Test ...]
.RI [ \-Aktion ...]
.SH BESCHREIBUNG
.B find
durchsucht eine oder mehrere
Verzeichnishierarchien nach Dateien mit bestimmten Eigenschaften, und
führt damit bestimmte Aktionen aus.  Die Eigenschaften können durch
Tests bestimmt werden.
.PP
Optionen, Tests und Aktionen können mit Operatoren zusammengefaßt werden.
.B find
bewertet für jede Datei in den Verzeichnishierarchien die
Optionen, Tests und Aktionen von links nach rechts, bis ein falscher
Wahrheitswert auftaucht oder die Kommandozeilenargumente zu Ende sind.
.PP
Das erste Argument, das mit einem
.BR \- ", einer Klammer " ( ", " ) ", einem Komma " ,
.RB " oder einem Ausrufezeichen " !
beginnt, wird als Anfang einer Option oder Test interpretiert.  Alle
Argumente davor werden als Verzeichnisnamen interpretiert.
.PP
Wenn kein Verzeichnis angegeben ist, wird das aktuelle Verzeichnis genommen.
Wenn keine Aktion angegeben ist, wird die Aktion
.B \-print
ausgeführt.
.PP
Der Status von
.B find
ist Null, wenn alle Aktionen erfolgreich waren, im Fehlerfall ist der Status
größer als Null.
.SH OPTIONEN
Die Optionen bestimmen das allgemeine Verhalten des Kommandos, und
beziehen sich nicht auf spezielle Dateien. Die Optionen sind immer wahr.
.TP
.B \-daystart
mißt die Zeiten für die -amin, -atime, -cmin, -ctime, -mmin und -mtime
Eigenschaften vom Beginn des aktuellen Tages anstelle der letzten 24 Stunden
.TP
.B \-depth
bearbeitet den Inhalt jedes Verzeichnisses vor dem Verzeichnis selbst
.TP
.B \-follow
folgt den symbolischen Links; diese Option schließt
.BR \-noleaf " mit ein"
.TP
.BI \-maxdepth " Ebenen"
steigt bis zu der gegebenen
Zahl von Ebenen im Verzeichnisbaum auf (in der Hierarchie ab); bei 0
Ebenen werden die Tests nur auf die in der Kommandozeile übergebenen
Dateien und Verzeichnisnamen angewendet
.TP
.BI \-mindepth " Ebenen"
steigt mindestens die gegebene Zahl von Ebenen im Verzeichnisbaum auf
(in der Hierarchie ab); bei einer Ebene werden die in der Kommandozeile
genannten Dateien und Verzeichnisnamen nicht bearbeitet
.TP
.B \-noleaf
erzwingt die Bearbeitung aller Verzeichniseinträge; normalerweise kann
davon ausgegangen werden, daß jedes Linuxverzeichnis wenigstens zwei
(harte) Links enthält: das Verzeichnis
.B .
ist ein Link auf das Verzeichnis selbst, und jedes Unterverzeichnis
enthält den Eintrag
.B ..
als Link auf das Oberverzeichnis; wenn
.B find
bei der Untersuchung eines Verzeichnisses zwei Unterverzeichnisse weniger
untersucht hat, als das Verzeichnis Links zählt, kann deshalb
normalerweise die weitere Suche beendet werden
.TP
.B \-version
gibt die Versionsnummer auf die Standardfehlerausgabe
.TP
.B \-xdev
durchsucht keine Verzeichnisse in anderen Dateisystemem
(auf anderen Partitionen)
.SS Tests:
Alle numerischen Argumente können auf drei Arten angegeben werden:
.RS
.TP
.BI + " N"
.RI "steht für alle Zahlen größer als " N
.TP
.BI \- " N"
.RI "steht für alle Zahlen kleiner als " N
.TP
.I N
.RI "steht für genau " N 
.RE
Alle Tests werden auf die Dateien in den angegebenen Verzeichnissen
einzeln angewendet.  Die Tests liefern einen Wahrheitswert von 0
(Wahr), wenn der Test erfolgreich war.
.PP
Die Tests auf die erweiterten Zeitmarken (Zugriff und Erstellung)
werden nur in solchen Verzeichnissen korrekt behandelt, die auf einem
der neuen Linuxdateisysteme angesiedelt sind (e2fs, xiafs, new minix).
Auf den anderen Dateisystemen wird nur das Datum der letzten Änderung
zuverlässig getestet. Das Ergebnis der anderen Tests hängt davon ab,
ob der letzte Zugriff bzw. die letzte Änderung so kurz zurückliegen,
daß die veränderte I-Node noch im Arbeitsspeicher (Cache) ist. Dann
können auch für die Dateien der alten Dateissysteme alle drei Zeitmarken
unterschieden werden.
.TP
.BI \-amin " N"
.RI "auf die Datei ist vor " N " Minuten zugegriffen worden"
.TP
.BI \-anewer " Referenzdatei"
auf die Datei ist vor weniger Zeit zugegriffen worden, als seit der
letzten Veränderung der
.I Referenzdatei
vergangen ist; im Zusammenhang mit
.BR \-follow " tritt " \-anewer " nur in Effekt, wenn " \-follow " vor"
.BR \-anewer " in der Kommandozeile steht"
.TP
.BI \-atime " N"
auf die Datei ist vor
.IR N *24
Stunden zugegriffen worden
.TP
.BI \-cmin " N"
.RI "der Status der Datei wurde vor " N " Minuten geändert"
.TP
.BI \-cnewer " Referenzdatei"
der Status der Datei wurde vor weniger Zeit verändert, als seit der
letzten Veränderung der
.I Referenzdatei
vergangen ist; zusammen mit
.BR \-follow " tritt " \-cnewer " nur in Effekt, wenn " \-follow " vor "
.BR \-cnewer " in der Kommandozeile steht"
.TP
.BI \-ctime " N"
.RI "der Dateistatus wurde vor " N "*24 Stunden geändert"
.TP
.B \-empty
die reguläre Datei oder das Verzeichnis ist leer
.TP
.B \-false
ist immer falsch
.TP
.BI \-fstype " Typ"
die Datei ist in einem Dateisystem vom angegebenen
.IR Typ "; unter anderem werden
.BR minix ", " msdos ", " ext " und " proc " erkannt"
.TP
.BI \-gid " N"
.RI "die Datei gehört der Gruppe mit der Kennzahl " N
.TP
.BI \-group " Name"
.RI "die Datei gehört der Gruppe " Name
.TP
.BI \-inum " IN"
.RI "die Datei belegt die Inode mit der Nummer " N
.TP
.BI \-links " N"
.RI "die Datei hat " N " (harte) Links"
.TP
.BI \-lname " Muster"
die Datei ist ein symbolischer Link auf eine Datei oder ein Verzeichnis
mit einem zum
.IR Muster " passenden Namen"
.TP
.BI \-mmin " N"
.RI "der Inhalt der Datei wurde vor " N " Minuten verändert"
.TP
.BI \-mtime " N"
.RI "der Inhalt der Datei wurde vor " IN "*24 Stunden verändert"
.TP
.BI \-name " Muster"
.RI "der Name der Datei paßt zu dem " Muster
.TP
.BI \-newer " Referenzdatei"
die Datei ist später verändert worden als die
.IR Referenzdatei "; zusammen mit " \-follow " tritt " \-newer " nur in"
.RB "Effekt, wenn " \-follow " vor " \-newer " in der Kommandozeile steht"
.TP
.B \-nouser
die Datei gehört keinem im System eingetragenen Benutzer
.TP
.B \-nogroup
die Datei gehört keiner im System angemeldeten Gruppe
.TP
.BI \-path " Muster"
.RI "der Pfadname der Datei paßt zum " Muster"
.TP
.BI \-perm " Modus"
die Zugriffsrechte auf die Datei entprechen exakt dem
.IR Modus "; der " Modus " kann als Oktalzahl oder mit den bei"
.BR chmod (1)
beschriebenen Kennungen beschrieben werden, die Kennungen werden auf Modus
.BR 000 bezogen
.TP
.BI "\-perm -" Modus
.RI "(mindestens) die Zugriffsrechte für den " Modus " sind gesetzt"
.TP
.BI "\-perm +" Modus
.RI "die Zugriffsrechte entsprechen höchstens dem " Modus
(oder sind weiter eingeschränkt)
.TP
.BI \-regex " Muster"
.RI "der Pfadname paßt zu dem regulären Ausdruck " Muster
.TP
"\fBsize \fIN\fR[{\fBc\fR,\fBk\fR}]"
die Datei belegt
.I N
Datenblöcke zu 512 Bytes, bzw. N Bytes und N Kilobytes mit nachgestelltem
.BR c " oder " k
.TP
.B \-true
ist immer wahr
.TP
.BI \-type " C"
.RI "die Datei ist vom Typ " C "; folgende Typen werden unterschieden:"
.RS
.TP
.B b
gepufferte Gerätedatei für ein blockorientiertes Gerät
.TP
.B c
ungepufferte Gerätedatei für ein zeichenorientiertes Gerät
.TP
.B d
Verzeichnis
.TP
.B p
benannte Pipeline (FiFo)
.TP
.B f
normale Datei
.TP
.B l
symbolischer Link
.TP
.B s
Socket
.RE
.TP
.BI \-uid " N"
.RI "die Kennziffer des Eigentümers ist " N
.TP
.BI \-used " N"
.RI "auf die Datei ist " N " Tage nach der letzten Änderung zugegriffen worden"
.TP
.BI\ -user " Name"
.RI "die Datei gehört dem Anwender " Name
.TP
.BI \-xtype " C"
.RB "das gleiche wie " \-type
für alle Dateien, die keine symbolischen Links sind; wenn die Datei ein
symbolischer Link ist und die Option
.B \-follow
nicht gesetzt ist, wird die Datei, auf die der Link zeigt, auf den Typ C
geprüft; wenn die Option
.B \-follow
gesetzt ist, ist der Test wahr, wenn C =
.BR l " ist"
.SS Aktionen:
.TP
.BI \-exec " Kommando;"
führt das
.I Kommando
aus; die Aktion ist wahr, wenn das Kommando einen Status von Null liefert;
alle auf den Kommandonamen folgenden Argumente bis zu einem Semikolon
.B ;
werden als Kommandozeilenargumente für das Kommando interpretiert; das
Semikolon kann nicht weggelassen werden, und es muß durch mindestens ein
Whitespace von der letzen Option getrennt werden; die Konstruktion
.B {}
wird durch den Pfadnamen der Datei ersetzt; die Klammern und das Semikolon
müssen in der Kommandozeile für
.B find
quotiert werden, damit sie nicht von der Shell bearbeitet werden
.TP
.BI \-fprint " Ausgabedatei"
schreibt den Pfadnamen der getesteten Datei in die
.IR Ausgabedatei ;
wenn die Ausgabedatei nicht existiert, wird sie erzeugt, sonst wird sie
erweitert; die Standardausgabe und die Standardfehlerausgabe werden als
.BR /dev/stdout " und " /dev/stderr " angesprochen"
.TP
.BI \-fprint0 " Ausgabedatei"
schreibt den Namen der getesteten Datei in die
.I Ausgabedatei
und schließt die Ausgabe mit einem Nullbyte ab, wie
.B \-print0
.TP
.BI \-fprintf " Ausgabedatei Format"
schreibt den Namen der getesteten Datei in die
.IR Ausgabedatei " und benutzt dabei das " Format " mit Sonderzeichen wie bei"
.B printf
.TP
.BI \-ok " Kommando;"
.RB "wie " \-exec ,
vor der Ausführung des Kommandos wird aber noch eine Bestätigung erwartet;
.RB "nur eine Eingabe, die mit einem " B " oder einem " y
beginnt, führt zur Ausführung des Kommandos
.TP
.B \-print
gibt den vollständigen Pfadnamen der getesteten Datei auf die Standardausgabe
.TP
.B \-print0
gibt den Pfadnamen der getesteten Datei, von einem Nullbyte abgeschlossen,
auf die Standardausgabe; auf diese Weise können auch Pfadnamen korrekt
weiterverarbeitet werden, die ein Zeilenende enthalten
.TP
.BI \-printf " Format"
gibt für die getestete Datei die Zeichenkette
.I Format
auf der Standardausgabe aus; Format kann verschiedene Sonderzeichen und
.RB "Platzhalter enthalten, die von " find " bearbeitet werden:"
.RS
.TP
\fB\\a\fR
Alarmton
.TP
\fB\\b\fR
Rückschritt
.TP
\fB\\c\fR
Abbruch der Ausgabe
.TP
\fB\\f\fR
Seitenvorschub
.TP
\fB\\n\fR
Zeilenvorschub
.TP
\fB\\r\fP
Wagenrücklauf
.TP
\fB\\t\fP
horizontaler Tabulator
.TP
\fB\\v\fP
vertikaler Tabulator
.TP
\fB\\\\\fR
der Backslash selbst
.RE
.PP
ein Backspace gefolgt von irgendeinem anderen Zeichen wird als normales Zeichen
interpretiert und einfach ausgegeben
.RS
.TP
.B %%
das Prozentzeichen selbst
.TP
.B %a
die Zeit des letzten Zugriffs auf die Datei, in dem Format der
.BR ctime " Funktion"
.TP
.BI %A " k"
die Zeit des letzten Zugriffs auf die Datei, in dem von
.I k
bestimmte Format; k hat dabei das gleiche Format wie der entprechende
.RB "Parameter der " strftime " Funktion in C:"
.RS
.TP
.B @
Sekunden seit dem 1.1.1970 0 Uhr GMT
.TP
.B H
Stunde (00 bis 23)
.TP
.B I
Stunde (01 bis 12)
.TP
.B k
Stunde (0 bis 23)
.TP
.B l
Stunde (1 bis 12)
.TP
.B M
Minute (00 bis 59)
.TP
.B p
PM oder AM
.TP
.B r
Zeit, 12 Stunden (hh:mm:ss: AM/PM)
.TP
.B S
Sekunden (00 bis 61)
.TP
.B T
Zeit, 24 Stunden (hh:mm:ss)
.TP
.B X
Zeit (H:M:S)
.TP
.B Z
Zeitzone, oder nichts
.TP
.B a
abgekürzter Wochentag
.TP
.B A
ausgeschriebener Wochentag
.TP
.B b
abgekürzter Monatsname
.TP
.B B
ausgeschriebener Monatsname
.TP
.B c
Datum und Zeit
.TP
.B d
Tag im Monat
.TP
.B D
Datum (mm/dd/yy)
.TP
.B h
das gleiche wie \fBb\fP
.TP
.B j
der Tag im Jahr
.TP
.B m
die Zahl des Monats
.TP
.B U
die Nummer der Woche, Sonntag als erster Wochentag
.TP
.B w
die Zahl des Wochentags
.TP
.B W
die Nummer der Woche, Montag als erster Wochentag
.TP
.B x
Datum (mm/dd/yy)
.TP
.B y
die letzten beiden Stellen der Jahreszahl
.TP
.B Y
die Jahreszahl
.RE
.TP
.B %b
die Dateigröße in 512 Byte Blöcken (aufgerundet)
.TP
.B %c
das Datum der letzten Statusänderung im Format der C
.BR ctime " Funktion"
.TP
.BI %C k
das Datum der letzten Statusänderung im Format der
BR strftime " Funktion; Parameter wie oben"
.TP
.B %d
die Höhe der Datei im Verzeichnisbaum; Null bedeutet, daß die Datei
Kommandozeilenargument ist
.TP
.B %f
der Name der getesteten Datei, ohne Verzeichnisse
.TP
.B %g
der Gruppenname der getesteten Datei oder die
Kennzahl, wenn die Gruppe nicht eingetragen ist
.TP
.B %G
die Gruppenkennzahl
.TP
.B %h
die Verzeichnisnamen des Pfadnamen der getesteten Datei
.TP
.B %H
das Kommandozeilenargument (Test), mit dem die Datei gefunden wurde
.TP
.B %i
die Nummer der Inode der getesteten Datei
.TP
.B %k
die aufgerundete Größe der getesteten Datei in Kilobytes
.TP
.B %l
das Objekt, auf die ein symbolischer Link zeigt; leer, wenn die getestete Datei
kein symbolischer Link ist
.TP
.B %m
die Zugriffsrechte als Oktalzahl
.TP
.B %n
die Anzahl der harten Links auf die getestete Datei
.TP
.B %p
der Pfadname der Datei
.TP
.B %P
der Pfadname und das Kommandozeilenargument (Test), mit dem die Datei gefunden
wurde
.TP
.B %s
die Größe der getesteten Datei in Bytes
.TP
.B %t
.RB "die Zeit der letzten Änderung, im " ctime " Format"
.TP
.BI %T k
.RB "die Zeit der letzten Änderung, im " strftime " Format (siehe oben)"
.TP
.B %u
der Name des Eigentümers der getesteten Datei oder die Kennzahl, wenn der
Benutzer nicht eingetragen ist
.TP
.B %U
die Benutzerkennzahl des Eigentümers der getesteten Datei
.RE
.TP
.B \-prune
.RB "wahr, wenn die Option " \-depth " gesetzt ist; sonst falsch"
.TP
.B \-ls
zeigt das Verzeichnis in dem die getestete Datei gefunden wurde mit
.BR "ls \-dils " an
.SS Operatoren:
Die Optionen, Tests und Aktionen können mit Operatoren verknüpft
werden. Die Bearbeitung erfolgt prinzipiell von links nach rechts.
.TP
.BI ( " Ausdruck " )
.RI "die Klammern fassen den " Ausdruck " zu einer Operation zusammen"
.TP
.BI ! " Ausdruck"
:RI "ist wahr, wenn der " Ausdruck " falsch ist"
.TP
.BI \-not " Ausdruck"
.RI "ist ebenfalls wahr, wenn der " Ausdruck " falsch ist"
.TP
.I "Ausdruck1 Ausdruck2"
UND Verknüpfung; wenn
.IR Ausdruck1 " wahr ist, wird " Ausdruck2 " bewertet (ausgeführt)"
.TP
.IB Ausdruck1 " -a " Ausdruck2
auch eine UND Verknüpfung
.TP
.IB Ausdruck1 " -and " Ausdruck2
auch eine UND Verknüpfung
.TP
.IB Ausdruck1 " -o " Ausdruck2
ODER Verknüpfung;
.IR Ausdruck2 " wird bewertet (ausgeführt), wenn " Ausdruck1 " falsch ist"
.TP
.IB Ausdruck1 " -or " Ausdruck2
auch eine ODER Verknüpfung
.TP
.IB Ausdruck1 " , "Ausdruck2
Liste; beide Ausdrücke werden immer bewertet (ausgeführt); der Wahrheitswert
des gesamten Ausdrucks entspricht dem von Ausdruck2
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
Eric Decker, David MacKenzie, Jay Plett und Tim Wood

