.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH FOLD 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"    
.SH NAME 
fold \- bricht Zeilen ab einer bestimmten Länge um
.SH SYNTAX 
.B fold
.RB [ \-bs ]
.RB [ \-w
.IR Länge ]
.RB [ \-\-bytes ]
.RB [ \-\-spaces ]
.RB [ \-\-width=
.IR Länge ]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B fold
liest die Datei(en) oder die
Standardeingabe, wenn keine Datei oder anstelle einer Datei \fB-\fP
angegeben ist und schreibt den Inhalt auf die Standardausgabe. Dabei
werden Zeilen ab einer bestimmten Länge umgebrochen. Voreingestellte
Länge ist 80 Zeichen pro Zeile. Ohne weitere Optionen wird einfach
nach dem achtzigsten Zeichen ein Zeilenvorschub eingefügt.
.PP
\fBfold\fP zählt nicht die Zeichen, sondern die Bildschirmspalten, so
daß Tabulatoren korrekt behandelt werden. Ein Backspace erniedrigt die
Zeichenzahl entsprechend, und ein Wagenrücklauf (carriage return)
setzt die Zahl auf Null zurück.
.SH OPTIONEN
.IP \fB-b\fP
es werden nicht die Bildschirmspalten, sondern die
Zeichen gezählt; die oben genannten Sonderzeichen erhöhen die
Zeichenzahl jeweils um Eins, wie alle anderen Zeichen auch
.IP \fB-s\fP
der Zeilenumbruch findet bei dem letzten Leerzeichen
der Zeile statt, wenn in der Zeile ein Leerzeichen vorhanden ist
.IP "\fB-w \fILänge\fR"
setzt die maximale Zeilenlänge auf den
angegebenen Wert
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

