.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH FREE 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH BEZEICHNUNG 
free - zeigt den freien Speicherplatz an
.SH SYNTAX 
.B free
.RB [ \-msribpc ]
.RB [ \-d
.IR Blockdevice ]
.RB [ \-S
.IR Intervall ]
.RI [ Swapdevice ]
.SH BESCHREIBUNG
.RB "Das " free " Kommando gehört zu der " ps "-Suite."
.RB "Wie das " ps
Programm muß es bestimmte Daten direkt aus dem Kernelspeicher lesen.  Dazu
gibt es wieder die beiden Möglichkeiten, die bei
.BR ps "(1) beschrieben sind.  Die " free " Version, die mit dem
Prozessdateisystem arbeitet, erkennt die hier aufgeführten Optionen nicht.  Es
zeigt nur den freien Speicherplatz im Arbeitsspeicher und auf dem Swapgerät,
.RB wie " free \-ms "."
.SH OPTIONEN
.TP
.B \-m
zeigt nur den freien Speicherplatz im Arbeitsspeicher
.TP
.B \-s
zeigt nur den freien Speicherplatz im Swapdevice
.TP
.B \-i
zeigt die Auslastung der Inodes im Blockdepot
.TP
.B \-b
zeigt die Auslastung der Datenblöcke im Blockdepot
.TP
.BI \-d " Gerät"
zeigt nur die Daten für die gepufferten Blöcke vom Gerät
.TP
.B \-f
zeigt die Auslastung der Dateikennzeichner (Filedescriptoren)
.TP
.B \-r
zeigt die Daten einer aktuellen Anforderung von Blöcken aus dem Blockdepot
.TP
.B \-p
zeigt die Anzahl der Seiten anstelle von Kilobytes (bei den Optionen
.BR \-m " und " \-s ")"
.TP
.BI \-S " Sekunden"
wiederholt die Anzeige nach der angegebenen Zahl Sekunden
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
Branco Lancaster

