.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH GROFF 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
groff \- formatiert Texte (z.B. Manualpages)
.SH SYNTAX 
.B groff
.RB [ \-tpeszaivhblCENRVZ ]
.RB [ \-w
.IR Name ]
.RB [ \-W
.IR Name ]
.RB [ \-H
.IR Datei ]
.RB [ \-m
.IR Makro ]
.RB [ \-F
.IR Verzeichnis ]
.RB [ \-T
.IR Format ]
.RB [ \-f
.IR Familie ]
.RB [ \-M
.IR Verzeichnis ]
.RB [ \-d
.IR cs ]
.RB [ \-r
.IR cn ]
.RB [ \-n
.IR Nummer ]
.RB [ \-o
.IR Liste ]
.RB [ \-P
.IR Argument ]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B groff
ist der Kern eines Textformatiersystems.  Normalerweise startet
.B groff " das " gtroff
Kommando und leitet die Ausgabe durch einen Postprozessor für ein
bestimmtes Ausgabegerät.  Folgende Ausgabeformate stehen zur Verfügung:
.TP
.B ps
Postscript
.TP
.B dvi
(DeVice Independent) das TeX Ausgabeformat
.TP
.B X75
für X-Windows Ausgabe mit 75dpi
.TP
.B X100
für X-Windows Ausgabe mit 100dpi
.TP
.B ascii
für einfache Druckerausgabe
.TP
.B latin1
für Druckerausgabe mit ISO Latin-1 Zeichensatz
.PP
Das Standardformat ist ascii. 
.PP
Im
.B groff
System stehen außerdem die Präprozessoren
.BR gpic ", " geqn ", " gtbl ", " grefer " und " gsoelim
zur Verfügung.
.SH OPTIONEN
.TP
.B -h
gibt einen Hilfstext aus
.TP
.B -e
leitet die Eingabe durch den
.B geqn
Präprozessor
.TP
.B -t
leitet die Eingabe durch den
.B gtbl
Präprozessor
.TP
.B -p
leitet die Eingabe durch den
.B gpic
Präprozessor
.TP
.B -s
leitet die Eingabe durch den
.B gsoelim
Präprozessor
.TP
.B -R
leitet die Eingabe durch den
.B grefer
Präprozessor; die Übergabe von Kommandozeilenargumenten an
.B grefer
wird nicht unterstützt
.TP
.B -v
die von
.B groff
aufgerufenen Programme geben ihre Versionsnummer aus
.TP
.B -V
gibt die von groff zusammengestellte Kommandozeile (Pipeline) auf der
Standardausgabe aus, anstatt sie auszuführen
.TP
.B -z
unterdrückt die Ausgabe von gtroff; nur Fehlermeldungen werden ausgegeben
.TP
.B -Z
unterdrückt den Postprozessor
.TP
.BI -P " Argument"
gibt das
.I Argument
an den Postprozessor weiter; jedes Argument sollte einzeln übergeben
werden; den Argumenten wird kein
.BR - " vorangestellt"
.TP
.BI -L " Argument"
gibt das
.I Argument
an den Spooler weiter
.TP
.BI -T " Format"
benutzt
.RI Ausgabe Format ;
Voreinstellung ist ascii
.TP
.B -N
übergibt die -N Option an geqn
.TP
.B -a
produziert reinen ascii Code, ohne Steuerzeichen
.TP
.B -b
gibt zusätzliche Information bei Fehlermeldungen
.TP
.B -i
liest aus der Standardeingabe, nachdem alle Eingabedateien bearbeitet sind
.TP
.B -C
schaltet in den Kompatibilitätsmodus (zu troff)
.TP
.B -E
unterdrückt alle Fehlermeldungen
.TP
.BI -w " Name"
erlaubt Warnung
.I Name
.TP
.BI -W " Name"
unterdrückt Warnung
.I Name
.TP
.BI -m " Makro"
die Datei
.BI tmac. Makro
wird gelesen und die darin definierten Makros zum Formatieren des
Dokuments benutzt
.TP
.BI -o " Liste"
gibt nur die Seiten aus
.I Liste
aus; die
.I Liste
ist eine durch Kommata getrennte Liste von Seitenbereichen
.TP
.BI -d " cs"
definiert das Register
.I c " mit " s ;
dabei ist
.I c
ein Buchstabe und
.I s
eine Zeichenkette
.TP
.BI -r " cn"
setzt Register
.IR c " auf " n .
Dabei ist
.I c
ein Buchstabe und
.I n
ein numerischer Ausdruck.
.TP
.BI -F " Verzeichnis"
sucht im
.I Verzeichnis
nach den Fonts
.TP
.BI -M " Verzeichnis"
sucht im
.I Verzeichnis
nach den Makros
.TP
.BI -H " Datei"
benutzt
.I Datei
nach der Trennmusterdatei
.TP
.BI -f " Familie"
benutzt
.I Familie
als Fontfamilie
.TP
.BI -n " Nummer"
setzt die Nummer der ersten Ausgabeseite auf
.I Nummer
.SS Umgebung:
Folgende Umgebungsvariablen werden unterstützt:
.TP
.B GROFF_TMAC_PATH
eine durch Doppelpunkte getrennte Liste von Verzeichnissen, in
denen nach Makrodateien gesucht wird
.TP
.B GROFF_TYPESETTER
das Standardausgabeformat
.TP
.B GROFF_FONT_PATH
eine durch Doppelpunkte getrennte Liste von Verzeichnissen, in
denen nach den Gerätetreibern und den Zeichensätzen für das
Ausgabeformat gesucht wird
.TP
.B GROFF_HYPHEN
eine Datei mit Mustern für die automatische Trennung durch groff
.TP
.B GROFF_TMPDIR
ein Verzeichnis, in dem die temporären Dateien von groff angelegt
werden; wenn kein Verzeichnis angegeben ist, wird das Verzeichnis
/tmp benutzt
.SS Dateien:
Die folgenden Dateien werden vom
.B groff
System benutzt:
.TP
.B /usr/lib/groff/hyphen
die Standardtrennmusterdatei
.TP
.BI /usr/lib/groff/tmac/tmac. Name
die Makrodatei für
.BI -m Name
.TP
.BI /usr/lib/groff/font/dev Name DESC
der Gerätetreiber für das Gerät
.I Name
.TP
.BI /usr/lib/groff/font/dev Name F
die Fontdatei für Font
.B F
von Gerät
.I Name
.TP
.BI /usr/lib/groff/font/dev Name /eqnchar
die Definitionen von (g)eqn für das Gerät
.I Name
.SH SIEHE AUCH
.BR grog (1),
.BR gtroff (1),
.BR gtbl (1),
.BR gpic (1),
.BR geqn (1),
.BR gsoelim (1),
.BR grefer (1),
.BR grops (1),
.BR grodvi (1),
.BR grotty (1),
.BR groff_font (5),
.BR groff_out (5),
.BR groff_msr (7),
.BR groff_me (7)
und das LunetIX Linuxhandbuch
.SH AUTOR
James Clark

