.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH GROFF 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"    
.SH BEZEICHNUNG 
groff \- formatiert Texte (z.B. Manualpages)
.SH SYNTAX 
.B groff
.RB [ \-tpeszaivhblCENRVZ ]
.RB [ \-w
.IR Name ]
.RB [ \-W
.IR Name ]
.RB [ \-H
.IR Datei ]
.RB [ \-m
.IR Makro ]
.RB [ \-F
.IR Verzeichnis ]
.RB [ \-T
.IR Format ]
.RB [ \-f
.IR Familie ]
.RB [ \-M
.IR Verzeichnis ]
.RB [ \-d
.IR cs ]
.RB [ \-r
.IR cn ]
.RB [ \-n
.IR Nummer ]
.RB [ \-o
.IR Liste ]
.RB [ \-P
.IR Argument ]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B groff
ist der Kern eines Textformatiersystems.
Normalerweise startet \fBgroff\fP das 
.B gtroff
Kommando und leitet die
Ausgabe durch einen Postprozessor für ein bestimmtes Ausgabegerät. Folgende
Ausgabeformate stehen zur Verfügung:
.IP \fBps\fP
Postscript
.IP \fBdvi\fP
(DeVice Independent) das TeX Ausgabeformat
.IP \fBX75\fP
für X-Windows Ausgabe mit 75dpi
.IP \fBX100\fP
für X-Windows Ausgabe mit 100dpi
.IP \fBascii\fP
für einfache Druckerausgabe
.IP \fBlatin1\fP
für Druckerausgabe mit ISO Latin-1 Zeichensatz
.PP
Das Standardformat ist ascii. 
.PP
Im \fBgroff\fP System stehen außerdem die Präprozessoren \fBgpic\fP, \fBgeqn\fP,
\fBgtbl\fP, \fBgrefer\fP und \fBgsoelim\fP zur Verfügung.
.SH OPTIONEN
.IP \fB-h\fP
gibt einen Hilfstext aus
.IP \fB-e\fP
leitet die Eingabe durch den \fBgeqn\fP Präprozessor
.IP \fB-t\fP
leitet die Eingabe durch den \fBgtbl\fP Präprozessor
.IP \fB-p\fP
leitet die Eingabe durch den \fBgpic\fP Präprozessor
.IP \fB-s\fP
leitet die Eingabe durch den \fBgsoelim\fP Präprozessor
.IP \fB-R\fP
leitet die Eingabe durch den \fBgrefer\fP Präprozessor; die
Übergabe von Kommandozeilenargumenten an \fBgrefer\fP wird nicht unterstützt
.IP \fB-v\fP
die von \fBgroff\fP aufgerufenen Programme geben ihre Versionsnummer
aus
.IP \fB-V\fP
gibt die von groff zusammengestellte Kommandozeile (Pipeline) auf der
Standardausgabe aus, anstatt sie auszuführen
.IP \fB-z\fP
unterdrückt die Ausgabe von gtroff; nur
Fehlermeldungen werden ausgegeben
.IP \fB-Z\fP
unterdrückt den Postprozessor
.IP "\fB-P \fIArgument\fR"
gibt das \fIArgument\fP an den
Postprozessor weiter; jedes Argument sollte einzeln übergeben
werden; den Argumenten wird kein \fB-\fP vorangestellt
.IP "\fB-L \fIArgument\fR"
gibt das \fIArgument\fP an den
Spooler weiter
.IP "\fB-T \fIFormat\fR"
benutzt Ausgabe\fIFormat\fP;
Voreinstellung ist ascii
.IP \fB-N\fP
übergibt die -N Option an geqn
.IP \fB-a\fP
produziert reinen ascii Code, ohne Steuerzeichen
.IP \fB-b\fP
gibt zusätzliche Information bei Fehlermeldungen
.IP \fB-i\fP
liest aus der Standardeingabe, nachdem alle
Eingabedateien bearbeitet sind
.IP \fB-C\fP
schaltet in den Kompatibilitätsmodus (zu troff)
.IP \fB-E\fP
unterdrückt alle Fehlermeldungen
.IP "\fB-w \fIName\fR"
erlaubt Warnung \fIName\fP
.IP "\fB-W \fIName\fR"
unterdrückt Warnung \fIName\fP
.IP "\fB-m \fIMakro\fR"
die Datei \fBtmac.\fIMakro\fR wird
gelesen und die darin definierten Makros zum Formatieren des
Dokuments benutzt
.IP "\fB-o \fIListe\fR"
gibt nur die Seiten aus \fIListe\fP
aus; die \fIListe\fP ist eine durch Kommata getrennte Liste von
Seitenbereichen
.IP "\fB-d \fIcs\fR"
definiert das Register \fIc\fP mit \fI    s\fP; dabei ist \fIc\fP ein Buchstabe und \fIs\fP eine
Zeichenkette
.IP "\fB-r \fIcn\fR"
setzt Register \fIc\fP auf \fIn\fP.
Dabei ist \fIc\fP ein Buchstabe und \fIn\fP ein numerischer
Ausdruck.
.IP "\fB-F \fIVerzeichnis\fR"
sucht im \fIVerzeichnis\fP
nach den Fonts
.IP "\fB-M \fIVerzeichnis\fR"
sucht im \fIVerzeichnis\fP
nach den Makros
.IP "\fB-H \fIDatei\fR"
benutzt \fIDatei\fP nach der Trennmusterdatei
.IP "\fB-f \fIFamilie\fR"
benutzt \fIFamilie\fP als Fontfamilie
.IP "\fB-n \fINummer\fR"
setzt die Nummer der ersten Ausgabeseite auf \fINummer\fP 
.SS Umgebung:
Folgende Umgebungsvariablen werden unterstützt:
.IP \fBGROFF_TMAC_PATH\fP
eine durch Doppelpunkte getrennte Liste von Verzeichnissen, in
denen nach Makrodateien gesucht wird
.IP \fBGROFF_TYPESETTER\fP
das Standardausgabeformat
.IP \fBGROFF_FONT_PATH\fP
eine durch Doppelpunkte getrennte Liste von Verzeichnissen, in
denen nach den Gerätetreibern und den Zeichensätzen für das Ausgabeformat gesucht wird
.IP \fBGROFF_HYPHEN\fP
eine Datei mit Mustern für die automatische Trennung durch groff
.IP \fBGROFF_TMPDIR\fP
ein Verzeichnis, in dem die temporären Dateien von groff angelegt
werden; wenn kein Verzeichnis angegeben ist, wird das Verzeichnis /tmp benutzt
.SS Dateien:
Die folgenden Dateien werden vom \fBgroff\fP System benutzt:
.IP \fB/usr/lib/groff/hyphen\fP
die Standardtrennmusterdatei
.IP \fB/usr/lib/groff/tmac/tmac.\fIName\fR\fP
die Makrodatei für \fB-m\fIName\fR
.IP \fB/usr/lib/groff/font/dev\fIName\fR/DESC\fP
der Gerätetreiber für das Gerät \fIName\fP
.IP \fB/usr/lib/groff/font/dev\fIName\fR/F\fP
die Fontdatei für Font \fBF\fP von Gerät \fIName\fP
.IP \fB/usr/lib/groff/font/dev\fIName\fR/eqnchar\fP
die Definitionen von (g)eqn für das
Gerät \fIName\fP
.SH SIEHE AUCH
\fBgrog\fP(1), \fBgtroff\fP(1), \fBgtbl\fP(1), \fBgpic\fP(1), \fBgeqn\fP(1), \fBgsoelim\fP(1),
\fBgrefer\fP(1), \fBgrops\fP(1), \fBgrodvi\fP(1), \fBgrotty\fP(1), \fBgroff_font\fP(5), \fBgroff_out\fP(5), \fBgroff_msr\fP(7),
\fBgroff_me\fP(7)
und das LunetIX Linuxhandbuch
.SH AUTOR
James Clark

