.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH GZIP 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
gzip \- komprimiert Dateien
.SH SYNTAX 
.B gzip
.RB [ \-cdfhLrtvV19 ]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B gzip
komprimiert Dateien mit dem LZ77 Lempel-Ziv Algorithmus.
.B gzip
erzielt erheblich bessere Kompressionsraten als das mit dem LZW Algorithmus
arbeitende
.B compress
Programm. Weil es sich ansonsten sehr ähnlich verhält, ist abzusehen daß es
.B compress
als Standardpacker im Bereich der freien Software verdrängen wird. Mit
.B gzip
können auch Dateien ausgepackt werden, die mit
.B compress
gepackt wurden.
.PP
.B gzip
ist kein Archivpacker wie
.BR lharc ", " arj " oder " pkzip .
.PP
.B gzip
komprimiert einzelne Dateien, unabhängig davon ob die resultierende Datei
tatsächlich kleiner ist, und ersetzt die Urdatei durch die komprimierte,
indem es an den Dateinamen die Endung
.B .gz
anhängt. Dabei bleiben die Zugriffsrechte und das Erstellungsdatum der
Urdatei erhalten.
.PP
Wenn der Dateiname durch Anhängen der Endung unzulässig lang würde, schneidet
.B gzip
automatisch die erforderliche Anzahl Zeichen vom Dateinamen ab, speichert
aber den vollständigen Namen zur Restaurierung beim Auspacken in der Datei ab.
.PP
.RB "Wenn " gzip
ohne Dateinamen aufgerufen wird, liest es von der
Standardeingabe und schreibt auf die Standardausgabe.
.PP
Wie bei
.BR compress " kann auch " gzip " auf andere Namen gelinkt werden um"
bestimmte Aufgaben zu erfüllen.
.PP
Unter dem namen 
.BR gunzip " arbeitet es wie " gzip -d ","
packt also komprimierte Dateien aus.  Dabei kann es auch die von
.B compress
(ab Version 3.0) gepackten Dateien bearbeiten.
.B gunzip
erwartet die Endung
.BR .z " oder " .Z " an dem Dateinamen.
Nach dem Auspacken bleiben die Zugriffsrechte und das Erstellungsdatum der
Datei erhalten.
.PP
.B zcat
schreibt die entkomprimierte Datei auf die Standardausgabe
und läßt die komprimierte Datei unberührt.
.SH OPTIONEN
.TP
.B \-c
schreibt die (ent)komprimierte
.I Datei
auf die Standardausgabe, anstatt die Datei zu ersetzen
.TP
.B \-d
(decompress) dekomprimiert die
.I Datei
.TP
.B \-f
(force) ersetzt bestehende Dateien mit Endung
.BR .z ;
normalerweise fragt
.B gzip
vor dem Überschreiben solcher Dateien nach
.TP
.B \-h
(help) gibt eine Kurzhilfe zum Programm aus
.TP
.B \-L
(license) gibt eine Kurzfassung des Lizenztextes aus
.TP
.B \-r
(recursive) packt alle Dateien in den angegebenen Unterverzeichnissen
.TP
.B \-t
(test) prüft die Integrität der angegebenen
.I Datei
.TP
.B \-v
(verbose) gibt den Kompressionsfaktor für jede
.IR Datei " aus"
.TP
.B \-V
(Version) gibt die Versionsnummer des Programms aus
.TP
.BI \- Ziffer
bestimmt mit einer Ziffer von 1 bis 9 die Kompressionstiefe; 1 bedeutet
schnell und schlecht komprimiert, 9 bedeutet langsam und optimal komprimiert
.SH "SIEHE AUCH"
.BR compress (1),
.BR tar (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Jean-Loup Gailly

