.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH HEAD 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  

.SH BEZEICHNUNG 
.B head
schreibt den Anfang einer Datei auf die Standardausgabe
.SH SYNTAX 
.B head
.RB [ \-c
.I Anzahl
.RB [ bkm ]]
.RB [ \-n
.IR Anzahl ]
.RB [ \-qv ]
.RB [ \-\-bytes=
.I Anzahl
.RB [ bkm ]]
.RB [ \-\-lines=
.IR Anzahl ]
.RB [ \-\-quiet ]
.RB [ \-\-silent ]
.RB [ \-\-verbose ]
.RI [ Datei ...]
.sp
.B head
.RI [ \-nr ]
.RB [ \-bcklmqv ]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B head
schreibt die ersten (10) Zeilen von der \fIDatei\fP auf den Bildschirm. Wenn keine \fIDatei\fP oder \fB\-\fP angegeben wird,
liest \fBhead\fP von der Standardeingabe. Wird mehr als eine \fIDatei\fP
angegeben, so wird der Dateiname, in \fB==>\fP und \fB<==\fP eingeschlossen, der
Ausgabe vorangestellt.
.SH OPTIONEN
.IP "\fB-c \fIAnzahl\fR"
gibt die angegebene \fIAnzahl\fP Bytes aus.
Optional kann die Blockgröße durch einen
der Zahl folgenden Buchstaben verändert werden:
.RS
.IP \fBb\fP
Blocks zu 512 Byte
.IP \fBk\fP
Blocks zu 1 Kilobyte
.IP \fBm\fP
Blocks zu 1 Megabyte
.RE
.IP "\fB-l \fIAnzahl\fR"
gibt die ersten \fIAnzahl\fP Zeilen aus
.IP \fB-q\fP
(quiet) unterdrückt die Ausgabe des Dateinamen
.IP \fB-v\fP
(verbose) gibt die Dateinamen immer aus
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

