.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH HOSTNAME 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch" 
.SH NAME 
hostname \- zeigt oder setzt den Netzwerknamen des Systems
.SH SYNTAX 
.B hostname
.RI [ Name ]
.SH BESCHREIBUNG
Wird 
.B hostname
ohne ein Argument aufgerufen, gibt
es den Netzwerknamen des Systems aus. Anderenfalls wird der Netzwerkname auf 
\fIName\fP gesetzt. Das Setzen ist nur dem Superuser (root) möglich.
.SH SIEHE AUCH
\fBuname\fP(1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Peter Orbaek

