.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH JOIN 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
join \- verknüpft zwei Dateien nach Schlüsselfeldern
.SH SYNTAX 
.B join
.RB [ "\-a  1" | 2 ]
.RB [ "\-v  1" | 2 ]
.RB [ \-e
.IR Zeichenkette ]
.RB [ \-o
.IR Feldliste ...]
.RB [ \-t
.IR Buchstabe ]
.RB [ \-j
.RB [ 1 | 2 ]
.IR Feldnr ]
.RB [ \-1
.IR Feldnr ]
.RB [ \-2
.IR Feldnr ]
.I Datei1 Datei2
.SH BESCHREIBUNG
.B join
verknüpft zwei (alphabetisch) sortierte Dateien, indem je zwei Zeilen
mit identischen Schlüsselfeldern zu einer Ausgabezeile verbunden werden.
.PP
Die Schlüsselfelder sind durch Leerzeichen voneinander getrennt. 
Führende Leerzeichen werden ignoriert.  Wenn nicht anders angegeben,
ist das erste Feld einer jeden Zeile Schlüsselfeld.  Die Ausgabefelder
sind ebenfalls durch Leerzeichen voneinander getrennt.  Die Ausgabe
besteht aus dem Schlüsselfeld, gefolgt von den übrigen Feldern der
Datei1 und schließlich aller Felder der passenden Zeilen von Datei2
ohne das Schlüsselfeld.
.SH OPTIONEN
.TP
.BI -a " Dateinummer"
fügt in die Ausgabe eine Leerzeile ein, wenn eine Zeile aus
.I Dateinummer
(1 oder 2) kein Gegenstück hat.
.TP
.BI -e " Zeichenkette"
ersetzt fehlende Eingabefelder in der Ausgabe durch die
.I Zeichenkette
.TP
.BI -1 " Feldnr"
benutzt in Datei1
.I Feldnr
als Schlüsselfeld
.TP
.BI -2 " Feldnr"
benutzt in Datei2
.I Feldnr
als Schlüsselfeld
.TP
.BI -j " Feldnr"
benutzt
.I Feldnr
als Schlüsselfeld
.TP
.BI -o " Feldliste"
stellt die Ausgabezeilen anhand der
.I Feldliste
zusammen.  Ein Eintrag in der
.I Feldliste
besteht aus einer 
.IR Dateinummer ,
einem Punkt und einer
.IR Feldnr . 
Beliebig viele solcher Paare
.IB Dateinummer . Feldnr
können, durch Komma oder Leerzeichen getrennt, in der
.I Feldliste
stehen.
.TP
.BI -t " Buchstabe"
verwendet
.I Buchstabe
als Feldtrenner
.TP
.BI -v " Dateinummer"
gibt nur die Zeilen aus
.I Dateinummer
aus, die kein Gegenstück haben.
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Mike Haertel

