.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH LESS 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
less \- zeigt Dateien Seitenweise (Pager)
.PP
Diese Handbuchseite ist veraltet. Im Zweifelsfall ziehen Sie
die englischsprachige Handbuchseite zu Rate, indem Sie
.IP
man -LC 1 less
.PP
eingeben.
.SH SYNTAX 
.B less
.RB [{ \- , + } aBcCdeEfHimMnNqQrsSuUw ]
.RB [ \-b
.IR Puffer ]
.RB [ \-h
.IR Zeilen ]
.RB [ \-j 
.IR Zeile ]
.RB [ \-k
.IR Schlüsseldatei ]
.RB [ \- { o , O }
.IR Datei ]
.RB [ \-p
.IR Muster ]
.RB [ \-P
.IR Prompt ]
.RB [ \-t
.IR Tag ]
.RB [ \-T
.IR Tagdatei ]
.RB [ \-x
.IR Tab ]
.RB [ \-y
.IR Zeilen ]
.RB  [ \- [ z ]
.IR Zeilen ]
.RB [ +
.IR Lesskommando ]
.RI [ Dateiname ...]
.SH BESCHREIBUNG
.B less
gibt eine (oder mehrere) Datei(en) seitenweise auf die
Standardausgabe.  Im Unterschied zu
.BR more " erlaubt "less
auch das Zurückblättern in Texten, die aus einer Pipeline gelesen
wurden.  Die voreingestellten Tastaturkommandos sind an die von
.BR more " und " elvis
angelehnt; sie lassen sich aber vom Anwender mit Hilfe des
.B lesskey
Kommandos beliebig neu definieren.
.SS Kommandos:
Die folgenden Tastaturkommandos zur Steuerung der Bildschirmausgabe
sind definiert.  Alle Kommandos können von einer ganzen Zahl N
eingeleitet werden, die die Anzahl der Wiederholungen dieses Kommandos
angibt.
.TP
.BR h " | " H
gibt einen Hilfstext aus
.TP
.BR leerzeichen " | " ctrl-V " | " f " | " ctrl-F
blättert eine Bildschirmseite vorwärts; wenn eine
Zahl vorangestellt ist, werden diese Anzahl Zeilen weitergeblättert
.TP
.B z
wie Leerzeichen; wenn eine Zahl vorangestellt ist, wird diese Zahl
zur neuen Seitenlänge auch für die weiteren Seiten
.TP
.BR return " | " ctrl-N " | " ctrl-E " | " ctrl-J
scrollt den Bildschirm eine (oder die gegebene Anzahl) Zeilen weiter
.TP
.BR d " | " ctrl-D
blättert einen halben Bildschirm (oder die gegebene Anzahl Zeilen)
weiter; wenn eine Zahl angegeben ist, wird sie zur Standardweite für
alle folgenden
.BR ctrl "-D und " ctrl -Us
 Kommandos
.TP
.BR b " | " ctrl-v
blättert einen Bildschirm oder die gegebene Anzahl Zeilen zurück
.TP
.B w
wie
.BR esc -v,
die gegebene Zahl wird aber der neue Standardwert für das Zurückblättern
.TP
.BR y " | " ctrl-Y " | " ctrl-P " | " k " | " ctrl-K
scrollt den Bildschirm um eine (oder die gegebene Anzahl) Zeile(n) zurück
.TP
.BR u " | " ctrl-U
blättert einen halben Bildschirm (oder die gegebene Anzahl Zeilen) zurück
.TP
.BR r " | " ctrl-R " | " ctrl-L
schreibt den aktuellen Bildschirm neu
.TP
.B R
schreibt den Bildschirm neu; dabei wird die gesamte gepufferte Eingabe
verworfen
.TP
.B F
scrollt den Bildschirm vorwärts; dabei wird versucht
weiterzulesen, auch wenn das Dateiende bereits erreicht war
.TP
.BR g " | " < " | " ctrl-<
geht zur ersten Zeile oder der Zeile mit der entsprechenden Zahl
.TP
.BR G " | " > " | " ctrl->
geht zur letzten Zeile oder zu der Zeile mit der entsprechenden
Zahl (vom Dateiende gezählt)
.TP
.BR p " | " %
macht nur Sinn, wenn es von einer Zahl zwischen 0 und 100 eingeleitet
wird, und geht dann zu der dieser Prozentzahl entsprechenden Stelle;
wenn von der Standardeingabe gelesen wird, kann dieses Kommando erst
benutzt werden, wenn die Eingabe abgeschlossen ist
.TP
.B }
wenn eine geschweifte Klammer auf der ersten Bildschirmzeile steht,
wird die Anzeige so gescrollt, dass die dazugehörende schließende
Klammer auf der letzten Bildschirmzeile steht; wenn mehr als eine
geschweifte Klammer auf der ersten Zeile geöffnet wird, kann mit
dem Zahlenargument bestimmt werden, welche Klammer referenziert werden soll
.TP
.B {
wenn die geschweifte Klammer auf der letzten Bildschirmzeile steht,
wird der Bildschirm so gerollt, dass die korrespondierende Klammer
auf der ersten Zeile angezeigt wird
.TP
.B (
das gleiche mit runden Klammern
.TP
.B )
dito
.TP
.B [
diesmal mit eckigen Klammern
.TP
.B ]
auch nichts neues
.TP
.B esc-ctrl-F
wie \{, es werden die dem Kommando folgenden beiden Zeichen als Klammern
interpretiert und entsprechend bearbeitet
.TP
.B esc-ctrl-B
wie \}, es werden die dem Kommando folgenden beiden Zeichen als Klammern
interpretiert und entsprechend bearbeitet
.TP
.B m
gefolgt von einem Kleinbuchstaben, markiert die aktuelle Position mit
diesem Buchstaben
.TP
.BR "' " | " ctrl-X ctrl-X"
gefolgt von einem Kleinbuchstaben kehrt zurück zu der mit diesem
Buchstaben markierten Stelle
.TP
.BI / Muster
sucht vorwärts nach dem
.IR Muster ;
eine passende Zeile wird als erste Bildschirmzeile angezeigt; das
Muster kann reguläre Ausdrücke enthalten (ed-Syntax); mit einem
Zahlenargument N kann auch das N-te auftreten des Musters gesucht
werden; die Suche beginnt in der zweiten Bildschirmzeile, wenn nicht
durch die Kommandozeilenoptionen
.BR -a " oder " -j
ein anderes Verhalten eingestellt ist; für das erste Zeichen vom
Muster stehen folgende Sonderzeichen zur Verfügung:
.TP
.B !
sucht nach einer Zeile, die das Muster nicht enthält
.TP
.B *
durchsucht mehrere Dateien; wenn die Suche bis zum Dateiende erfolglos
ist, wird die nächste Datei aus der Kommandozeilenliste durchsucht
.TP
.B @
beginnt die Suche in der ersten Datei aus der Kommandozeilenliste, unabhängig
davon, welche Datei aktuell angezeigt wird; auch die Kommandozeilenoptionen
.BR -a " und " -j
werden ignoriert
.TP
.BI ? Muster
sucht rückwärts nach einer Zeile mit dem
.IR Muster ;
die Suche beginnt vor der ersten Bildschirmzeile; folgende
Sonderzeichen können als erstes Zeichen vom Muster eingesetzt werden:
.TP
.B !
sucht eine Zeile, die das Muster nicht enthält
.TP
.B *
durchsucht mehrere Dateien; wenn das Muster bis zum Dateianfang erfolglos
ist, wird die der aktuellen Datei vorhergehende aus der Kommandozeilenlistew
durchsucht
.TP
.B @
beginnt die Suche auf der letzten Zeile der letzten Datei aus der
Kommandozeilenliste, unabhängig von der aktuellen Datei und den
Kommandozeilenoptionen
.BR -a " und " -j
.TP
.BI esc-/ Muster
das gleiche wie
.BI /* Muster
.TP
.BI esc-? Muster
das gleiche wie
.BI ?* Muster
.TP
.B n
wiederholt die letzte Suche; die Sonderzeichen
.BR * " und " !
behalten ihre Bedeutung,
.B @
wird ignoriert
.TP
.B N
wiederholt die letzte Suche in umgekehrter Richtung
.TP
.B esc-n
wiederholt die letzte Suche und sucht in der nächsten (vorhergehenden) Datei
weiter, wenn das Dateiende (der Dateianfang) erreicht ist
.TP
.B esc-N
wiederholt die Suche rückwärts und setzt die Suche in weiteren Dateien fort
.TP
"\fB:e\fR [\fIDateiname\fR...]"
zeigt die benannte Datei an; wenn keine Datei angegeben ist, wird
die aktuelle Datei neu angezeigt; ein Prozentzeichen
.B %
im Dateiname wird durch den Namen der aktuellen Datei ersetzt; das
Nummernzeichen
.B #
wird durch den Namen der zuvor angezeigten Datei ersetzt; die neue
Datei wird in die Kommandozeilenliste der Dateien eingereiht, so dass
sie bei den folgenden
.BR :n " und " :p
Befehlen erreicht werden kann; wenn mehrere Dateinamen angegeben
sind, werden alle Dateinamen in die Kommandozeilenliste eingefügt
.TP
.BR "ctrl-X ctrl-V " | " E"
das gleiche wie
.B :e
.TP
.B :n
zeigt die nächste Datei aus der Kommandozeilenliste an
.TP
.B :p
zeigt die vorhergehende Datei aus der Kommandozeilenliste an
.TP
.B :x
zeigt die erste (oder N-te) Datei aus der Kommandozeilenliste an
.TP
.BR = " | " ctrl-G " | " :f
zeigt den Namen der aktuellen Datei und die Position in der Datei
.TP
.B -
,gefolgt von einer der unten aufgeführten Kommandozeilenoptionen,
ändert ebendiese Option und zeigt die neue Einstellung an; wenn zu
einer Option ein Zahlenargument oder eine Zeichenkette angegeben
werden müssen, kann dieses Argument nach dem Optionsbuchstaben
interaktiv angegeben werden
.TP
.B -+
,gefolgt von einer der unten beschriebenen Kommandozeilenoptionen,
setzt diese Option auf ihren voreingestellten Wert zurück; es können
nur die Einstellungen zurückgesetzt werden, die keine Zeichenkette
als Argument benötigen
.TP
.B --
,gefolgt von einer der unten beschriebenen Kommandozeilenoptionen,
setzt diese Option auf das Gegenteil der Standardeinstellung; es
können nur die Einstellungen verändert werden, die keine Argumente
benötigen; im Anschluss an die Änderung wird die aktuelle Einstellung
gezeigt
.TP
.B _
(Unterstrich), gefolgt von einer der unten beschriebenen
Kommandozeilenoptionen, zeigt den aktuellen Wert dieser Einstellung;
die Einstellung wird nicht verändert
.TP
.BI + Lesskommando
führt das angegebene
.I Lesskommando
jedesmal automatisch aus, wenn eine neue Datei angezeigt wird
.TP
.B V
zeigt die Versionsnummer von
.B less
.TP
.BR " q " | " :q " | " :Q " | " ZZ " | " esc esc"
beendet
.B less
.TP
.B v
startet einen Editor mit der aktuellen Datei; wenn in der Shellvariablen
.B EDITOR
nichts anderes bestimmt ist, wird der
.B vi
als Standardeditor benutzt
.TP
.BI ! " Kommandozeile"
startet eine Shell und führt das angegebene externe Kommando aus; in der
.I Kommandozeile
kann der Name der aktuellen Datei mit einem Prozentzeichen
.BR % ,
der Name der zuletzt davor aktuellen Datei mit dem Nummernzeichen
.B #
ersetzt werden; ein doppeltes Ausrufezeichen
.B !!
wiederholt die letzte Kommandozeile; ein einfaches Ausrufezeichen
.B !
startet eine interaktive Shell; in allen Fällen wird die Standardshell
/bin/sh gestartet, wenn in der Umgebungsvariablen
.B SHELL
keine andere Shell bestimmt ist
.TP
.BI | " Marke Kommandozeile"
leitet die Zeilen von der ersten Bildschirmzeile bis zur Marke
durch das in der
.I Kommandozeile
angegebene Kommando
.SH OPTIONEN
die folgenden Optionen und Einstellungen können in der Kommandozeile
beim Aufruf von less gesetzt werden. Es ist außerdem möglich die
entsprechenden Einstellungen mit dem
.B -
Kommando zur Laufzeit von
.B less
vorzunehmen. Zusätzlich bietets
.B less
die Möglichkeit, bestimmte Optionen, die jedesmal gesetzt werden
sollen, in der Umgebungsvariablen
.B LESS
zu speichern.  Die so gesetzten Optionen werden jedesmal gelesen, wenn
.B less
gestartet wird, können aber immer von Kommandozeilenoptionen verdeckt werden.
.TP
.B -?
zeigt eine kurze Übersicht über die Kommandos und Optionen von less
.TP
.B -a
die Vorwärtssuchfunktionen fangen in der letzten Bildschirmzeile
an, überspringen also den aktuellen Bildschirm
.TP
.BI -b " Nr"
veranlaßt
.B less
die mit Nr angegebene Anzahl von Puffern für die Anzeige zu benutzten;
jeder Puffer ist ein Kilobyte groß; wenn
.B less
aus einer Pipe liest, werden die Puffer automatisch angefordert
(siehe die Option
.BR -B )
.TP
.B -B
unterdrückt die automatische Anforderung neuer Puffer; es werden
nur die mit der
.B -b
Option bereitgestellten oder die standardmäßig eingestellten zehn Puffer
für die Speicherung der aus einer Pipeline gelesenen Daten benutzt;
werden mehr Daten gelesen als Pufferplatz frei ist, wird der älteste
Puffer überschrieben
.TP
.B -c
jede neue Bildschirmseite wird von der ersten Zeile an neu aufgebaut;
normalerweise wird jede neue Bildschirmseite durch Scrollen des
Bildschirms angezeigt
.TP
.B -C
der Bildschirm wird vor jeder neuen Seite gelöscht, sonst wie
.B -c
.TP
.B -d
unterdrückt Warnungen bzw. Fehlermeldungen auf ``dummen'' Terminals, wenn
bestimmte Funktionen wie Bildschirmlöschen oder Rückwärtsscrollen nicht
zur Verfügung stehen
.TP
.B -e
.B less
beendet automatisch, wenn das Dateiende zum zweiten mal erreicht wird;
normalerweise kann
.B less
nur ausdrücklich durch ein entsprechendes Kommando verlassen werden
.TP
.B -E
.B less
wird automatisch beim (ersten) Dateiende verlassen
.TP
.B \-f
erzwingt die Anzeige, auch von Dateien mit nichtdruckbaren Zeichen
.TP
.BI \-h " Nr"
es werden höchstens die angegebene Anzahl Zeilen rückwäts gescrollt;
sollen mehr als die angegebene Anzahl Zeilen zurückgeblättert werden,
findet der Bildschirmaufbau wie beim Vorwärtsblättern von der ersten
Zeile an statt; wenn das Terminal kein Rückwärtsscrollen unterstützt, wird
.B \-h0
automatisch angenommen
.TP
.B \-i
Groß- und Kleinschreibung werden beim Suchen nicht unterschieden;
wenn ein Buchstabe im Suchmuster groß geschrieben ist, wird diese
Option ignoriert
.TP
.BI \-j " Nr"
die Zielzeile bei einer Suche oder einer direkten Positionierung wird
an der benannten Stelle angezeigt; eine negative Zahl zählt die Zielzeile
vom unteren Bildschirmrand anstelle des oberen
.TP
.BI \-k " Datei"
liest eine alternative Tastaturbelegung aus der benannten Datei;
wenn keine Datei angegeben ist, wird die Datei
.B .less
im Home-Verzeichnis gelesen; eine Datei mit alternativer
Tastaturbelegung kann mit dem
.B lesskey
Kommando erzeugt werden
.TP
.B \-m
zeigt die aktuelle Dateiposition in Bytes oder Prozent als
Eingabeaufforderung nach jeder Seite; normalerweise dient der Doppelpunkt
.B :
als Eingabeaufforderung
.TP
.B \-M
zeigt die aktuelle Dateiposition in Zeilen und den Dateinamen als
Eingabeaufforderung
.TP
.B \-n
die Zeilennummer wird weder in der Eingabeaufforderung, noch beim
Aufruf des Editors benutzt
.TP
.B \-N
jeder Zeile wird in der Anzeige eine Zeilennummer vorangestellt
.TP
.BI \-o " Datei"
kopiert die gelesene Eingabe in die benannte
.IR Datei ,
wenn aus einer Pipeline gelesen wird; wenn die Datei schon existiert,
muss der Benutzer vor dem Überschreiben die Aktion bestätigen
.TP
.BI \-O " Datei"
wie
.BR \-o ,
es wird aber vor dem Überschreiben einer existierenden Datei nicht nachgefragt
.TP
.BI \-p " Muster"
sucht sofort das erste Auftreten vom
.I Muster
in der ersten angegebenen Datei
.TP
.BI \-P " Prompt"
ändert die Eingabeaufforderung
.RI ( Prompt ) ;
.B \-Pm
ändert den Prompt für die
.B \-m
Option, und
.B \-PM
ändert entsprechend den Prompt für die
.B \-M
Option; die Syntax der Prompt Zeichenkette mit
.B "man less"
in den englischen Manualpages nachzulesen
.TP
.B \-q
der Alarmton des Terminals wird nicht bei kleineren Fehlern, wie
z.B. das Vorwärtsblättern am Dateiende ausgelöst; wenn das Terminal
eine optische Warnung unterstützt, wird diese anstelle des akustischen
Alarms benutzt
.TP
.B \-Q
der Alarmton des Terminals wird unter keinen Umständen ausgelöst
.TP
.B \-r
die Sonderzeichen (Control Sequenzen) werden nicht als Caret-Sequenz
sondern roh angezeigt
.TP
.B \-s
mehrere Leerzeilen werden zu einer einzigen Leerzeile zusammengefasst;
das ist die Standardeinstellung für die Anzeige von groff Ausgabe
.TP
.B \-S
überlange Zeilen werden einfach abgeschnitten; normalerweise wird der
Rest überlanger Zeilen in der nächsten Zeile angezeigt
.TP
.BI \-t " Tag"
zeigt die Datei, in der vom ctags Programm die Marke
.I Tag
gefunden wurde; für diese Option muss eine
.B tags
Datei vom
.B ctags
Programm im aktuellen Verzeichnis angelegt werden
.TP
.BI \-T " Tagdatei"
die benannte Tagdatei wird anstelle der Datei
.B tags
im aktuellen Verzeichnis für die
.B \-t
Option benutzt
.TP
.B \-u
Rückschritt und Wagenrücklauf werden roh (unverändert) an das Terminal
geschickt
.TP
.B \-U
Rückschritt und Wagenrücklauf werden als Control-Sequenzen der Option
.B \-r
entsprechend an das Terminal geschickt; normalerweise werden Rückschritte,
die von einem Unterstrich gefolgt werden, durch einen unterstrichenen
Buchstaben, Rückschritte, die von dem gleichen Buchstaben eingeleitet
wie gefolgt werden, durch einen fettgedruckten Buchstaben dargestellt;
alle anderen Rückschritte und die von einem Zeilenvorschub gefolgten
Wagenrücklaufzeichen werden ignoriert
.TP
.B \-w
die Bildschirmzeilen nach dem Dateiende werden durch Leerzeilen anstelle der
voreingestellten Tilde
.B ~
dargestellt
.TP
.BI \-x " Nr"
die Tabulatorweite wird auf die gegebene Anzahl Stellen gesetzt
.TP
.BI \-y " Nr"
setzt eine Grenze von Zeilen, bis zu der das Vorwärtsscrollen möglich
ist; wenn mehr als die gesetzte Anzahl Zeilen vorwärts geblättert werden
soll, wird der Bildschirm der
.BR \-c " oder " \-C
Option entsprechend neu aufgebaut
.TP
.BI \-z " Nr"
ändert die Schrittweite für das Blättern auf die angegebene Zeilenzahl
.TP
.B +
eine Kommandozeilenoption, die mit einem Pluszeichen beginnt, wird als
Initialisierungskommando für
.B less
interpretiert und als erstes Kommando von
.B less
ausgeführt; wenn anstelle eines einzelnen Pluszeichens zwei Pluszeichen
benutzt werden, wird das darauf folgende Kommando bei allen Dateien der
Kommandozeilenliste als erstes ausgeführt
.SS Umgebungsvariable
.B less
unterstützt die folgenden Umgebungsvariablen:
.TP
.B COLUMNS
die Zeilenlänge für den Ausgabebildschirm
.TP
.B EDITOR
der Editor für das
.B v
Kommando
.TP
.B HOME
das Home-Verzeichnis des Anwenders; hier wird die
.B .less
Datei gesucht
.TP
.B LESS
eine Zeichenkette mit Kommandozeilenoptionen
.TP
.B LESSBINFMT
das Format zur Anzeige binärer Zeichen, die keine Controlzeichen sind
.TP
.B LESSCHARDEF
definiert einen Zeichensatz
.TP
.B LESSCHARSET
wählt einen vorher definierten Zeichensatz aus
.TP
.B LESSEDIT
die Kommandozeile für den Editor
.TP
.B LESSHELP
der absolute Name der Hilfsdatei
.TP
.B LINES
die Anzahl der Bildschirmzeilen
.TP
.B SHELL
die Shell für die externen Kommandos
.TP
.B TERM
die Terminalbezeichnung, wie sie in /etc/termcap zu finden ist
.SH SIEHE AUCH
.BR more (1),
.BR lesskey (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Mark Nudelman

