.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.\"   Modified Tue Aug 04 1998 by Andreas Braukmann <andy@abra.de>
.\"
.TH LOGNAME 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
.B logname
zeigt den Benutzernamen
.SH SYNTAX 
.B logname
.SH BESCHREIBUNG
Das Kommando 
.B logname
zeigt den Benutzernamen, wie er in der Datei
.I /etc/utmp
gespeichert ist. Wenn für das Terminal, von dem aus das Kommando
gestartet wird, kein Eintrag gefunden wird, gibt
.B logname
eine Fehlermeldung aus und beendet mit dem Status 1; sonst wird mit
dem Status 0 beendet.
.SH "SIEHE AUCH"
.BR utmp (5).

