.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH LOGNAME 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH NAME 
.B logname
zeigt den Benutzernamen
.SH SYNTAX 
.B logname
.SH BESCHREIBUNG
Das Kommando 
.B logname
zeigt den Benutzernamen, wie er in der
Datei /etc/utmp gespeichert ist. Wenn für das Terminal, von dem aus das
Kommando gestartet wird, kein Eintrag gefunden wird, gibt \fBlogname\fP
eine Fehlermeldung aus und beendet mit dem Status 1; sonst wird mit
dem Status 0 beendet.

