.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MCOPY 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
mcopy \- kopiert Dateien zwischen DOS und Linux
.SH SYNTAX 
.B mcopy
.RB [ \-tnwm ]
.I Quelldatei Zieldatei
.sp
.B mcopy
.RB [ \-tnwm ]
.I Quelldatei 
.RI [ Quelldatei ...]
.I Zielverzeichnis
.SH BESCHREIBUNG
.B mcopy
kopiert Dateien zwischen MS-DOS und Linux
Dateisystemen. Ein MS-DOS Dateiname muß mit einer Laufwerksbezeichnung
angegeben werden. Wird für eine MS-DOS Datei kein absoluter Pfad
benannt, gilt das aktuelle DOS-Verzeichnis. Dieses Verzeichnis wird in der Datei
\fB~/.mcwd\fP im Heimatverzeichnis des Anwenders bestimmt und durch das \fBmcd\fP Kommando
verändert.
.SH OPTIONEN
.IP \fB-t\fP
konvertiert CR/LF in LF (für Texttransfer)
.IP \fB-n\fP
unterdrückt Warnungen vor dem Überschreiben existierender Dateien
.IP \fB-v\fP
gibt die Dateinamen vor dem Kopieren aus
.IP \fB-m\fP
kopiert die Datei inclusive des Zeitstempels
.SH SIEHE AUCH
\fBmcd\fP(1),
\fBmread\fP(1),
\fBmwrite\fP(1), /etc/mtools, ~/.mcwd, \fBmtools\fP(1)
und das LunetIX Linuxhandbuch

