.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MDEL 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
mdel \- löscht eine Datei in einem MS-DOS Dateisystem
.SH SYNTAX 
.B mdel
.RB [ \-v ]
.I msdosdatei ...
.SH BESCHREIBUNG
.B mdel
löscht eine oder mehrere Dateien in einem
MS-DOS Dateisystem. \fBmdel\fP erwartet eine Bestätigung vor dem Löschen von
``nur Lesen'' Dateien.
.SH OPTIONEN
.IP \fB-v\fP
zeigt den Namen jeder Datei vor dem Löschen noch einmal an
.SH SIEHE AUCH
\fBmtools\fP(1)
und das LunetIX Linuxhandbuch

