.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MDIR 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   \INDEX{VERZEICHNIS!AUF MS-DOS DISKETTEN}
.SH NAME 
mdir \- zeigt den Inhalt eines DOS Verzeichnisses
.SH SYNTAX 
.B mdir
.RB [ \-w ] 
.RI [ Verzeichnis ]
.sp
.B mdir
.RB [ \-w ]
.I Datei ...
.SH BESCHREIBUNG
.B mdir
zeigt den Inhalt eines MS-DOS Verzeichnisses
oder Information über MS-DOS Dateien.
Wird kein \fIVerzeichnis\fP angegeben, so wird der Inhalt des aktuellen DOS
Verzeichnisses angezeigt, das in der Datei \fB~/.mcwd\fP im Heimatverzeichnis des Anwenders
festgelegt ist und mit dem \fBmcd\fP Kommando gewechselt wird.
.SH OPTIONEN
.IP \fB-w\fP
gibt die Dateinamen in Spalten nebeneinander aus
.SH SIEHE AUCH
\fBmtools\fP(1)
und das LunetIX Linuxhandbuch

