.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MDIR 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
mdir \- zeigt den Inhalt eines DOS Verzeichnisses
.SH SYNTAX 
.B mdir
.RB [ \-w ] 
.RI [ Verzeichnis ]
.sp
.B mdir
.RB [ \-w ]
.I Datei ...
.SH BESCHREIBUNG
.B mdir
zeigt den Inhalt eines MS-DOS Verzeichnisses oder Information über MS-DOS
Dateien.  Wird kein
.I Verzeichnis
angegeben, so wird der Inhalt des aktuellen DOS Verzeichnisses angezeigt,
das in der Datei
.B ~/.mcwd
im Home-Verzeichnis des Anwenders festgelegt ist und mit dem
.B mcd
Kommando gewechselt wird.
.SH OPTIONEN
.TP
.B \-w
gibt die Dateinamen in Spalten nebeneinander aus
.SH "SIEHE AUCH"
.BR mtools (1)
und das LunetIX Linuxhandbuch

