.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MFORMAT 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
mformat \- richtet ein MS-DOS Dateisystem ein
.SH SYNTAX   
.B mformat
.RB [ \-t 
.IR Spuren ] 
.RB [ \-h 
.IR Köpfe ] 
.RB [ \-s 
.IR Sektoren ]  
.RB [ \-l 
.IR Label ]
.IB Laufwerk :
.SH BESCHREIBUNG
.B mformat
richtet auf einer roh (low-level) formatierten Diskette ein MS-DOS Dateisystem ein. 
.SH OPTIONEN
.TP
.BI \-t " Anzahl"
die Anzahl der Spuren
.TP
.BI \-h " Anzahl"
die Anzahl der Köpfe (Seiten)
.TP
.BI \-s " Anzahl"
die Anzahl der Sektoren pro Spur
.TP
.BI \-l " Name"
das Label der Diskette
.SH "SIEHE AUCH"
.BR fdformat (1),
.BR mtools (1)
und das LunetIX Linuxhandbuch

