.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MKDIR 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH BEZEICHNUNG 
mkdir \- erzeugt ein leeres Verzeichnis
.SH SYNTAX  
.B mkdir
.RB [ \-p ] 
.RB [ \-m 
.IR Modus ] 
.RB [ \-\-path ]
.RB [ \-\-mode=
.IR Modus ]
.I Verzeichnis ...
.SH OPTIONEN
.IP "\fB-m \fIModus\fR"
setzt die Rechte des Verzeichnisses auf \fIModus\fP;
der \fIModus\fP wird wie beim Kommando \fBchmod\fP angegeben;
der Standard, und damit der Ausgangswert für relative
Modes, ist \fB0777\fP minus der Bits von \fBumask\fP
.IP \fB-p\fP
wenn ein Unterverzeichnis in einem nicht existierenden Verzeichnis angelegt werden
soll, werden alle fehlenden Verzeichnisse angelegt
.SH SIEHE AUCH
\fBln\fP(1), \fBrmdir\fP(1)
und das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

