.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MMD 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
mmd \- erzeugt ein neues MS-DOS Verzeichnis
.SH SYNTAX 
.B mmd
.RB [ \-v ]
.I Verzeichnis ...
.SH BESCHREIBUNG
.B mmd
erzeugt ein oder mehrere neue MS-DOS
Verzeichnisse im aktuellen DOS-Verzeichnis oder in dem absoluten Pfad. Verzeichnisnamen, die
nicht der MS-DOS Konvention entsprechen werden automatisch auf die zulässigen Zeichen
gekürzt.
Existiert bereits eine Datei oder ein Verzeichnis mit dem gleichen Namen, wird
das Kommando nicht ausgeführt. 
.SH OPTIONEN
.IP \fB-v\fP
zeigt die Namen der erzeugten Verzeichnisse an
.SH SIEHE AUCH
\fBmtools\fP(1)
und das LunetIX Linuxhandbuch

