.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MRD 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
mrd \- löscht ein MS-DOS Verzeichnis
.SH SYNTAX 
.B mrd
.I Verzeichnis ...
.SH BESCHREIBUNG
.B mrd
löscht ein oder mehrere MS-DOS
Verzeichnisse.  Das Kommando wird mit Fehlermeldung abgebrochen, wenn
ein Verzeichnis nicht leer ist.
.SH SIEHE AUCH
\fBmtools\fP(1)
und das LunetIX Linuxhandbuch

