.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MREAD 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
mread \- liest eine Datei aus einem MS-DOS Dateisystem
.SH SYNTAX 
.B mread
.RB [ \-tnm ]
.I Msdosdatei Unixdatei
.sp
.B mread
.RB [ \-tnm ] 
.I Msdosdatei ... Unixverzeichnis
.SH BESCHREIBUNG
.B mread
liest eine {\it MS-DOS Datei\/}
und kopiert sie in eine
.IR Unixdatei .
Wird anstelle einer
.I Unixdatei
ein
.I Unixverzeichnis
angegeben, so werden alle MS-DOS Dateien in das
.I Unixverzeichnis
kopiert.
.SH OPTIONEN
.TP
.B \-t
übersetzt CR/LF in LF
.TP
.B \-n
unterdrückt Warnung vor dem Überschreiben einer Datei
.TP
.B \-m
kopiert den Zeitstempel der
.I msdosdatei
.SH SIEHE AUCH
.BR mtools (1)
und das LunetIX Linuxhandbuch

