.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH MV 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"    
.SH NAME 
mv \- (move) verschiebt eine Datei oder benennt sie um
.SH SYNTAX 
.B mv
.RI [ Optionen ]
.I Quelle Ziel
.sp
.B mv
.RI [ Optionen ]
.I Quelle ... Verzeichnis
.SH BESCHREIBUNG
.B mv
verschiebt eine oder mehrere Datei(en) bzw.\
Verzeichnis(se) oder benennt sie um. Ein Verzeichnis
kann nicht über die Grenzen eines Dateisystems hinweg verschoben
werden.
.SH OPTIONEN
.IP \fB-b\fP
sichert Dateien vor dem Überschreiben
.IP \fB-f\fP
überschreibt existierenden Zieldateien rücksichtslos
.IP \fB-i\fP
erwartet interaktiv eine Bestätigung vor dem Überschreiben
existierender Zieldateien
.IP \fB-u\fP
verschiebt Dateien nur, wenn sie neuer sind als die gleichnamigen
Zieldateien
.IP \fB-v\fP
meldet jede Aktion
.IP "\fB-S \fIEndung\fR"
bestimmt die \fIEndung\fP für einfaches Backup.
Voreinstellung ist \fB~\fP
.IP "\fB-V\fR {\fBnumbered\fR, \fBexisting\fR, \fBsimple\fR}"
kontrolliert die Art des Backups. Die
Parameter sind beim Befehl \fBcp\fP(1) erklärt
.SH SIEHE AUCH
\fBln\fP(1), \fBcp\fP(1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Mike Parker und David MacKenzie

