.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH NL 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH BEZEICHNUNG
nl \- nummeriert die Zeilen in einer Datei
.SH SYNTAX 
.B nl
.RB [ \-h  
.IR Stil ]  
.RB [ \-b
.IR Stil ]
.RB [ \-f 
.IR Stil ] 
.RB [ \-p ] 
.RB [ \-d 
.IR "zwei Zeichen" ] 
.RB [ \-v 
.IR Nummer ] 
.RB [ \-i 
.IR Nummer ]  
.RB [ \-l  
.IR Nummer ] 
.RB [ \-s 
.IR Zeichenkette ]  
.RB [ \-w  
.IR Nummer ]  
.RB [ \-n { ln , rn , rz }]
.RB [ \-\-header-numbering=
.IR Stil ]
.RB [ \-\-body-numbering=
.IR Stil ] 
.RB [ \-\-footer-numbering=
.IR Stil ]  
.RB [ \-\-first-page=
.IR Nummer ]
.RB [ \-\-page-increment=
.IR Nummer ] 
.RB [ \-\-no-renumber ] 
.RB [ \-\-join-blank-lines=
.IR Nummer ] 
.RB [ \-\-number-separator=
.IR Zeichenkette ] 
.RB [ \-\-number-width=
.IR Nummer ]
.RB [ \-\-number-format= { ln , rn , rz }]
.RB [ \-\-section-delimiter=
.IR "zwei Zeichen" ] 
.RI [ Datei ...]
.SH BESCHREIBUNG
.B nl
gibt die Zeilen einer oder
mehrerer Dateien (oder der Standardeingabe) mit Zeilennummern auf die
Standardausgabe. Es können dabei die Zeilen einer (logischen) Seite in
einen Kopf, einen Körper und einen Fuß unterteilt werden, die jeweils
einzeln und in unterschiedlichen Stilen nummeriert werden. Jeder Teil
kann auch leer sein.  Wenn vor dem ersten Kopfteil bereits Zeilen
vorhanden sind, werden diese Zeilen wie ein Seitenkörper nummeriert.
.PP
Die Nummerierung beginnt auf jeder Seite neu. Mehrere Dateien werden
als ein einziges Dokument betrachtet, und die Zeilennummer nicht
zurückgesetzt.
.PP
Der Kopfteil wird durch eine Zeile eingeleitet, die nur die Zeichenkette
\fB\\:\\:\\:\fP enthält. Der Körper wird entsprechend durch
\fB\\:\\:\fP und der Fuß durch \fB\\:\fP eingeleitet. In der Ausgabe
werden diese Zeilen als Leerzeilen ausgegeben.
.SH OPTIONEN
.TP
.BI \-h " Stil"
bestimmt die Art der Zeilennummerierung für die Kopfzeile; das
Nummerntrennzeichen wird auch den nicht nummerierten Zeilen
vorangestellt; als
.I Stil
werden folgende Zeichen erkannt
.TP
.B a
alle Zeilen werden nummeriert
.TP
.B t
die leeren Zeilen werden nicht nummeriert (Voreinstellung für den Körper)
.TP
.B n
die Zeilen werden nicht nummeriert (Voreinstellung für Kopf und Fuß)
.TP
.BI p " Ausdruck"
nur die Zeilen, in denen der reguläre
.I Ausdruck
vorkommt, werden nummeriert
.TP
.BI \-b " Stil"
bestimmt die Art der Zeilennummerierung für den Körper
.TP
.BI \-f " Stil"
bestimmt die Art der Zeilennummerierung für den Fuß
.TP
.B \-p
die Zeilen aller Seiten werden fortlaufend nummeriert
.TP
.BI \-v " Nummer"
die erste Zeile jeder logischen Seite bekommt die angegebene Nummer
.TP
.BI \-i " Nummer"
die Schrittweite für die Nummerierung 
.TP
.BI \-l " Nummer"
die angegebene Anzahl aufeinanderfolgender Leerzeilen werden als eine
Zeile angesehen, und die letzte Zeile nummeriert; wenn weniger Leerzeilen
in Folge auftreten, werden sie nicht nummeriert; Leerzeilen dürfen auch
keine Leerzeichen oder Tabulatoren enthalten
.TP
.BI \-s " Zeichenkette"
setzt die
.I Zeichenkette
als Nummerntrennzeichen zwischen Zeilennummer und Text; Voreinstellung ist
.B tab
.TP
.BI \-w " Nummer"
die Zeilennummern erhalten die angegebene Anzahl Stellen; Voreinstellung
ist 6
.TP
.BR \-n " {" ln ", " rn ", " rz "}"
die Zeilennummern werden in dem angegebenen Stil ausgegeben; dabei bedeutet
.TP
.B ln
linksbündig, ohne führende Nullen
.TP
.B rn
rechtsbündig, ohne führende Nullen
.TP
.B rz
rechtsbündig, mit Nullen auf die volle Stellenzahl aufgefüllt
.TP
.BI \-d " zwei Zeichen"
die zwei Zeichen werden zur Trennung von Kopf, Körper und Fußteil
benutzt, Voreinstellung ist \fB\\:\fP
.SH SIEHE AUCH
.BR pr (1).
und das LunetIX Linuxhandbuch
.SH AUTOR
Scott Bartram, David MacKenzie

