.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH NOHUP 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
nohup \- läßt ein Programm die Signale \fBSIGHUP\fP \fBSIGINT\fP \fBSIGQUIT\fP und \fBSIGTERM\fP ignorieren
.SH SYNTAX 
.B nohup
.I Kommando
.RI [ Argument ...]
.SH BESCHREIBUNG
.B nohup
schützt ein Programm vor den Hangup Signalen.
Dadurch kann es im Hintergrund weiterlaufen, auch wenn der Benutzer sich
ausloggt. Normalerweise würden mit der Loginshell alle Prozesse des Anwenders
durch ein \fBSIGHUP\fP beendet.
.PP
Der Prozeß geht nicht automatisch in den
Hintergrund, sondern muß mit einem \fB&\fP am Ende der Kommandozeile dorthin gebracht
werden. Die Schedulerpriorität eines mit \fBnohup\fP gestarteten Programms wird
um 5 erhöht.  Wenn die Standardausgabe des Programms ein Terminal ist, so wird
sie automatisch gemeinsam mit der Standardfehlerausgabe in die Datei
.I nohup.out
umgeleitet.  Ist das aktuelle Verzeichnis schreibgeschützt, wird
die Datei im \fBHOME\fP Verzeichnis angelegt.

