.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH OD 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH BEZEICHNUNG 
od \- (octal dump) zeigt Dateien im oktalen, hexadezimalen oder in anderen Formaten an.
.SH SYNTAX 
.B od
.RB [ \-abcdfhiloxv ] 
.RB [ \-s
.RI [ Länge ]]
.RB [ \-w
.RI [ Anzahl ]]
.RB [ \-A 
.IR Positionsformat ] 
.RB [ \-j 
.IR Anzahl ] 
.RB [ \-N 
.IR Anzahl ]   
.RB [ \-t 
.IR Format ] 
.RB [ \-\-skip-bytes=
.IR Anzahl ] 
.RB [ \-\-address-radix=
.IR Positionsformat ]
.RB [ \-\-read-bytes=
.IR Anzahl ] 
.RB [ \-\-format=
.IR Format ] 
.RB [ \-\-output-duplicates ] 
.RB [ \-\-strings [ =
.IR Anzahl ]]
.RB [ \-\-width [ =
.IR Anzahl ]]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B od
liest die angegebenen Dateien
oder die Standardeingabe (wenn keine Datei oder anstelle einer Datei
\fB-\fP angegeben ist), und gibt die Bytes formatiert und kodiert auf
die Standardausgabe.
.PP
Jede Ausgabezeile enthält in der ersten Spalte die Positionsnummer des
ersten in der Zeile dargestellten Bytes (vom Dateianfang gezählt). In
den darauffolgenden Spalten werden die Daten aus der Datei in einem
durch die Optionen kontrollierten Format angezeigt.
.PP
In der Standardeinstellung ohne Optionen gibt \fBod\fP die Position
als 7-stellige Oktalzahl
und die Daten in 8
Spalten zu je zwei Bytes in oktaler Darstellung aus.
.SH OPTIONEN
.IP "\fB-A \fIPositionsformat\fR"
zeigt die Position des ersten in
einer Zeile dargestellten Bytes im Positionsformat; die folgenden
Formate stehen zur Auswahl:
.IP \fB-d\fP
siebenstellige Dezimalzahl
.IP \fB-o\fP
siebenstellige Oktalzahl (Voreinstellung)
.IP \fB-x\fP
sechsstellige Hexadezimalzahl
.IP \fB-n\fP
keine Positionsangabe
.IP "\fB-j \fIAnzahl\fR"
überspringt die ersten Anzahl Bytes der
Datei und beginnt erst danach mit der Ausgabe; wenn die Zahl mit \fB0x\fP oder \fB0X\fP beginnt, wird sie als Hexadezimalzahl
interpretiert, beginnt sie mit einer Null wird sie als Oktalzahl
behandelt, sonst als Dezimalzahl; der Zahl kann einer der Buchstaben
\fBb\fPi (blocks=512), \fBk\fP (kilo=1024) oder \fBm\fP (mega=1048576)
folgen, die die Anzahl mit den entsprechenden Einheiten multiplizieren
.IP "\fB-N \fIAnzahl\fR"
gibt nur die angegebene Anzahl Bytes
von der Datei aus; die Anzahl kann wie bei der \fB-j\fP Option von
einer Einheit gefolgt werden
.IP "\fB-t \fIFormat\fR"
wählt die Codierung für die
Datenausgabe; wenn die \fB-t\fP Option mehrfach benutzt wird, oder
mehrere Formate gleichzeitig angegeben werden, gibt od für jedes
Format jeweils eine entsprechende Zeile aus; folgende Formate werden
unterstützt
.IP \fBa\fP
(ascii) setzt das achte Datenbit aller Zeichen auf
null, die druckbaren ASCII Zeichen werden als solche ausgegeben, und
die nichtdruckbaren Steuerzeichen werden mit ihren in der ASCII
Tabelle verwendeten ``Namen'' bezeichnet; so wird das Zeilenende als
\fBcr\fP bezeichnet, ein horizontaler Tabulator mit \fBtab\fP und so
weiter
.IP \fBc\fP
(character) gibt die druckbaren ASCII Zeichen als
solche aus, die nichtdruckbaren Zeichen werden, sofern möglich, als
Backslashsequenz ausgegeben; \\f ist hier z.B. 
ein Zeilenende, \\t ein Tabulator und so weiter; Bytes die
nicht druckbar sind und auch nicht als Backslashsequenz ausgegeben
werden können, werden als Oktalzahl dargestellt
.IP \fBd\fP
(decimal) gibt die Daten als vorzeichenbehaftete
Dezimalzahlen aus; voreingestellt sind vier Bytes je Dezimalzahl
.IP \fBf\fP
(float) gibt die Daten als Fließkommazahlen aus;
voreingestellt sind acht Bytes je Fließkommazahl
.IP \fBo\fP
(octal) gibt die Daten als Oktalzahlen aus;
voreingestellt sind vier Bytes je Oktalzahl
.IP \fBu\fP
(unsigned) gibt die Daten als vorzeichenlose
Dezimalzahl aus; voreingestellt sind vier Bytes je Dezimalzahl
.IP \fBx\fP
(heX) gibt die Daten als Hexadezimalzahlen aus;
voreingestellt sind vier Bytes je Hexadezimalzahl
.PP
Außer die Typen \fBa\fP und \fBc\fP, die immer einzelne Bytes
anzeigen, kann die Anzahl der Bytes, die in jeweils eine Zahl des
bestimmten Typs umgewandelt werden sollen, durch eine dem
Typkennzeichner unmittelbar folgende Zahl bestimmt werden. Die Anzahl
der Bytes je Zahl kann auch durch Buchstabenkennungen angegeben
werden, die den C-Datentypen entsprechen. Für die Ganzzahltypen (\fBd\fP, \fBu\fP, \fBx\fP, \fBo\fP) gibt es die folgenden Möglichkeiten:
.IP \fBC\fP
(Char) ist ein Byte lang
.IP \fBS\fP
(Short) ist zwei Bytes lang
.IP \fBI\fP
(Integer) ist vier Bytes lang
.IP \fBL\fP
(Long) ist auch vier Bytes lang
.PP
für Fließkommazahlen können die folgenden Optionen verwendet werden
.IP \fBF\fP
(Float) ist vier Bytes lang
.IP \fBD\fP
(Double) ist acht Bytes lang
.IP \fBL\fP
(Long Double) ist auch acht Bytes lang
.IP \fB-v\fP
gibt auch die doppelten Zeilen aus; normalerweise
werden ganze Zeilen, die der zuletzt angezeigten Zeile vollständig
entsprechen, durch ein Asterisk \fB*\fP dargestellt
.IP "\fB-s \fR[\fILänge\fR]"
gibt nur die
gültigen C-Zeichenketten (Folgen von druckbaren ASCII Zeichen, durch
ein Nullbyte beendet) mit mindestens der angegebenen \fILänge\fP
aus; Voreinstellung für Länge ist drei Zeichen
.IP "\fB-w \fR[\fIAnzahl\fR]"
setzt die
Anzahl der umgewandelten Bytes, die in einer Zeile ausgegeben
werden; die Anzahl muß ein vielfaches der Länge jedes Ausgabetyps
sein; Voreinstellung ist 16
.PP
Die folgenden Optionen übersetzen die nicht dem POSIX Format
entsprechenden alten Optionen in die neuen dem POSIX Standard
entsprechenden Optionen, wie sie oben aufgeführt sind.
.IP \fB-a\fP
gibt benannte ASCII Zeichen aus, wie \fB-t a\fP
.IP \fB-b\fP
gibt die Daten Byteweise als Oktalzahlen aus, wie \fB-t oC\fP
.IP \fB-c\fP
gibt druckbare Zeichen oder Backslashsequenzen aus,
wie \fB-t c\fP
.IP \fB-d\fP
gibt die Daten als vorzeichenlose kurze Dezimalzahlen
aus, wie \fB-t u2\fP
.IP \fB-f\fP
gibt die Daten als Fließkommazahlen mit vier Bytes je
Zahl aus, wie \fB-t fF\fP
.IP \fB-h\fP
gibt die Daten als vierstellige Hexadezimalzahl aus,
wie \fB-t xL\fP
.IP \fB-i\fP
gibt die Daten als vorzeichenbehaftete Dezimalzahl
mit zwei Bytes je Zahl aus, wie \fB-t d2\fP
.IP \fB-l\fP
gibt die Daten als vorzeichenbehaftete Dezimalzahl
mit vier Bytes je Zahl aus, wie \fB-t dL\fP
.IP \fB-o\fP
gibt die Daten als Oktalzahlen mit zwei Bytes je Zahl
aus, wie \fB-t oS\fP
.IP \fB-x\fP
gibt die Daten als Hexadezimalzahlen mit zwei Bytes
je Zahl aus, wie \fB-t x2\fP
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Jim Meyering

