.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH PASTE 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch" 
.SH BEZEICHNUNG 
paste \- fügt die Zeilen von zwei oder mehr Dateien horizontal zusammen
.SH SYNTAX 
.B paste
.RB [ \-s ] 
.RB [ \-d 
.IR Liste ]
.RB [ \-\-serial ] 
.RB [ \-\-delimiters=
.IR \fIListe\fP ] 
.RI [ Datei  ...]
.SH BESCHREIBUNG
.B paste
fügt die Zeilen mehrerer
Dateien zusammen. Die Zeilen werden standardmäßig durch \fBtab\fP
getrennt und die Ausgabe einer kompletten Zeile (das heißt die Ausgabe
der entsprechenden Zeilen aller Dateien) wird mit einem Zeilenende
abgeschlossen.
.SH OPTIONEN
.IP "\fB-d \fIListe\fR"
benutzt die Zeichen aus \fIListe\fP
zur Trennung der Zeilen aus den einzelnen Dateien beim
zusammenfügen; \fIListe\fP ist dabei ein Wort oder eine
Zeichenkette aus beliebigen druckbaren Zeichen oder den
Sonderzeichen \\n \\t \\\\ und
\\0 für Zeilenende, Tabulator, Backslash oder Leerstring;
wenn die \fIListe\fP abgearbeitet ist, wird sie von vorne
angefangen
.IP \fB-s\fP
fügt alle Zeilen einer ganzen Datei zu einer Zeile
zusammen; werden mehrere Dateien angegeben, so werden die Zeilen der
nächsten Dateien als jeweils eine neue Zeile angefügt
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
David M. Ihnat

