.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH PR 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH BEZEICHNUNG 
pr \- formatiert Textdateien zur Druckerausgabe
.SH SYNTAX 
.B pr
.RB [ +
.IR SEITE ]
.RB [ \-
.IR SPALTEN ]
.RB [ \-abcdfFmrtv ] 
.RB [ \-e
.RI [ Eintab
.RI [ Schritt ]]] 
.RB [ /$-$h 
.IR Kopf ]
.RB [ \-i
.RI [ Austab
.RI [ Schritt ]]] 
.RB [ \-l 
.IR Seitenlänge ]
.RB [ \-n
.RI [ Separator
.RI [ Stellen ]]] 
.RB [ \-o 
.IR Lrand ]
.RB [ \-s
.RI [ Separator ]] 
.RB [ \-w 
.IR Breite ] 
.RI [ Datei ...] 
.SH BESCHREIBUNG
.B pr
produziert seitenweise
nummerierte und einfach formatierte Ausgabe von Textdateien.
.SH OPTIONEN
.TP
.BI + Seite\
beginnt die Ausgabe mit der angegebenen
.I Seite
.TP
.BI \- Spalten
setzt den Text in die angegebene Anzahl
.IR Spalten . 
Ein Zeilenumbruch findet nicht statt; die Spaltenbreite wird an die
Seitenbreite angepaßt
.TP
.B \-a
teilt den Text zeilenweise in die Spalten anstatt seitenweise
.TP
.B \-b
schließt die letze Seite mit balancierten Spalten ab, das heißt alle
Spalten sind gleichlang
.TP
.B \-c
zeigt Controlzeichen als Caretsequenz
.RB ( ^G
für Control-G)
.TP
.B \-d
gibt den Text mit doppeltem Zeilenabstand aus
.TP
.BI \-e " Eintab Schritt"
übersetzt das Zeichen
.IR Eintab " in " Schritt
Leerzeichen; Voreinstellungen sind
.BR tab " für " Eintab " und 8 für " Schritt
.TP
.B \-f
gibt einen Seitenvorschub anstelle von Zeilenvorschüben am Seitenende
.TP
.BI \-h " Kopf"
schreibt die Zeichenkette
.I Kopf
anstelle des Dateinamen als Seitenkopf
.TP
.BI \-i " Austab Schritt"
ersetzt Folgen von
.I Schritt
Leerzeichen durch ein
.I Austab
Zeichen; voreingestellt sind
.BR tab " für " Austab " und 8 für " Schritt
.TP
.BI \-l " Seitenlänge"
setzt die Druckseitenlänge; Voreinstellung ist 66; bei einer
Seitenlänge unter 10 Zeilen werden die Kopf- und Fußzeilen weggelassen
.TP
.B \-m
gibt alle Dateien parallel in Spalten aus
.TP
.BI \-n " Separator Stellen"
setzt Zeilennummern vor jede Spalte; werden Dateien parallel angezeigt,
bekommt jede Zeile nur eine Nummer; der
.I Separator
steht zwischen der Nummer und der Zeile, Voreinstellung ist
.BR tab ;
die Zeilennummer hat die angegebene Anzahl
.IR Stellen ,
Voreinstellung ist 5
.TP
.BI \-o " Lrand"
setzt den linken Rand auf
.IR Lrand ;
die Seitenbreite ist die Summe von
.IR Lrand " und " Breite
von Option
.B \-w
.TP
.B \-r
gibt keine Fehlermeldung für Dateilesefehler aus
.TP
.BI \-s " Separator"
trennt die Spalten durch den Buchstaben
.IR Separator ; Voreinstellung ist
.B tab
.TP
.B \-t
Der 5-zeilige Kopf und der 5-zeilige Fußbereich werden nicht ausgegeben,
und die Seiten werden nicht durch Leerzeilen oder mit einem Seitenvorschub
aufgefüllt
.TP
.B \-v
gibt nichtdruckbare Sonderzeichen als Oktalzahl aus
.TP
.BI \-w " Breite"
setzt die druckbare
.IR Breite ,
Voreinstellung ist 72 Zeichen 
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Pete TerMaat

