.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH PS 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"    
.SH BEZEICHNUNG 
ps \- (process status) zeigt die Prozesse mit ihrem Status an
.SH SYNTAX 
.B ps
[-acehjlmnrsuvwxS] [-t
.IR xx ]
.RB [ \-U
.RI [ Systempfad
.RI [ Swappfad ]]
.SH BESCHREIBUNG
Mit 
.B ps
lassen sich Daten über die Prozesse in der Prozeßtabelle anzeigen. 
Die Prozeßtabelle wird mit einer Titelzeile ausgegeben.  Die Spalten
haben folgende Bedeutung:
.TP
.B PRI
ist die Priorität eines Prozesses; je niedriger der Wert ist, desto
mehr Rechenzeit bekommt der Prozeß
.TP
.B NI
ist der Nicewert des Prozesses;  Nice erhöht die Priorität des
Prozesses und gibt damit Prozessorzeit für andere Prozesse frei
.TP
.B SIZE
ist die Größe von Text, Daten und Stack
.TP
.B WCHAN
ist der Name der Kernelfunktion, in der der Prozeß
schläft
.TP
.B STAT
ist der Status des Prozesses
.TP
.B R
lauffähig
.TP
.B S
schlafend
.TP
.B D
nicht störbarer Schlaf
.TP
.B T
angehalten
.TP
.B Z
Zombie
.TP
.B W
der Prozeß belegt keine Seiten im Arbeitsspeicher
.TP
.B %CPU
Anteil an der Prozessorzeit
.TP
.B TT
die Nummer des kontrollierenden Teminal
.TP
.B TPGID
Gruppen ID des kontrollierenden Terminal
.TP
.B PAGEIN
Anzahl der Seitenfehler (das ist der Versuch auf eine
ausgelagerte Seite zuzugreifen)
.TP
.B TRS
Größe des Textsegments (enhält keine shared Librarys)
.TP
.B DRS
Größe des Datensegments (enthält benutzte Libraryseiten)
.TP
.B SWAP
ausgelagerte Speicherseiten in Kilobyte (oder Seiten mit
.BR \-p )
.TP
.B SHRD
shared Memory
.TP
.B DT
benutzte Libraryseiten in Kilobyte (oder Seiten mit
.BR \-p )
.TP
.B F
Flags
.TP
.B 04
Prozeß hat die Mathe Emulation benutzt
.TP
.B 10
Der Prozeß wurde verfolgt (traced)
.PP
Es gibt zwei unterschiedliche Versionen von
.BR ps . 
Die eine greift direkt auf den Kernelspeicher zu, aus dem sie die
Prozeßtabelle ausliest.  Dazu braucht
.B ps
die Datei
.IR /etc/psdatabase ,
in der die Speicheradressen für die entsprechenden Kernelvariablen
abgelegt sind.  Diese Datei muß für jeden Kernel mit dem Kommando
.B ps -U
neu erzeugt werden.  Bei größeren Veränderungen am Kernel (in der
Regel bei neuen Kernelversionen) wird auch ein Neuübersetzen von
.B ps
notwendig.
.PP
Das andere
.B ps
hat die gleiche Funktionalität und mit Ausnahme der
.B \-U
Option auch die gleichen Optionen, es arbeitet aber mit dem
Prozeßdateisystem. Dieses Dateisystem enthält Verzeichnisse für alle
Prozesse des Systems, in deren Unterverzeichnissen und Dateien alle für
.B ps
interessanten Daten zu finden sind.  Das
.B ps
Kommando bereitet diese Daten auf und zeigt sie dem Anwender in genau
der gleichen Weise an wie die andere Version.  Der Vorteil der Methode
mit dem Prozeßdateisystem besteht in der Unabhängigkeit von der
Kernelversion.
.PP
Das Verzeichnis, auf dem das Prozeßdateisystem aufgesetzt ist, kann in
der aktuellen Version des
.B procps
nicht angegeben werden.  Es erwartet das Prozeßdateisystem unter dem
Verzeichnis
.IR /proc .
.SH OPTIONEN
.TP
.B \-a
zeigt die Prozesse aller User
.TP
.B \-c
zeigt den Namen des Kommandos
.TP
.B \-e
zeigt die Prozeßumgebung
.TP
.B \-h
unterdrückt die Kopfzeile
.TP
.B \-j
jobs Format:
.BR PGID " und " SID
.TP
.B \-l
langes Format:
.B FLAGS WCHAN NICE PRIO
.TP
.B \-m
zeigt Speichernutzung
.TP
.B \-X
zeigt
.BR "EIP ESP TIMEOUT " und " ALARM"
.TP
.B \-n
gibt numerische Werte für
.BR USER " und " WCHAN
.TP
.B \-r
zeigt nur die laufenden Prozesse
.TP
.B \-s
zeigt die Signale
.TP
.B \-u
zeigt die Besitzer der Prozesse 
.TP
.B \-v
vm Format
.TP
.B \-w
ausführliche Ausgabe, kann mehrmals angegeben werden
.TP
.B \-x
zeigt Prozesse, die von keinem Terminal kontrolliert werden
.TP
.B \-S
addiert die Prozessorzeit der Kindprozesse zu den Eltern
.TP
.B \-U
aktualisiert die Datei
.IR /etc/psdatebase ,
die den Zugang zu den Kerneldaten vermittelt;  diese Aktualisierung
muß immer durchgeführt werden, nachdem der Kernel neu übersetzt wurde;
diese Option fällt bei dem
.B ps
Programm, das mit dem Procdateisystem arbeitet, weg
.TP
.BI t " xx"
zeigt nur die Prozesse die von Terminal
.I xx
kontrolliert werden
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Branko Lankester

