.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH PS 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"    
.SH NAME 
ps \- (process status) zeigt die Prozesse mit ihrem Status an
.SH SYNTAX 
.B ps
[-acehjlmnrsuvwxS] [-t
.IR xx ]
.RB [ \-U
.RI [ Systempfad
.RI [ Swappfad ]]
.SH BESCHREIBUNG
Mit 
.B ps
lassen sich Daten über
die Prozesse in der Prozeßtabelle anzeigen. Die Prozeßtabelle wird
mit einer Titelzeile ausgegeben. Die Spalten haben folgende Bedeutung:
.IP \fBPRI\fP
ist die Priorität eines Prozesses; je niedriger der
Wert ist, desto mehr Rechenzeit bekommt der Prozeß
.IP \fBNI\fP
ist der Nicewert des Prozesses; Nice erhöht die Priorität des
Prozesses und gibt damit Prozessorzeit für andere Prozesse frei
.IP \fBSIZE\fP
ist die Größe von Text, Daten und Stack
.IP \fBWCHAN\fP
ist der Name der Kernelfunktion, in der der Prozeß
schläft
.IP \fBSTAT\fP
ist der Status des Prozesses
.IP \fBR\fP
lauffähig
.IP \fBS\fP
schlafend
.IP \fBD\fP
nicht störbarer Schlaf
.IP \fBT\fP
angehalten
.IP \fBZ\fP
Zombie
.IP \fBW\fP
der Prozeß belegt keine Seiten im Arbeitsspeicher
.IP \fB%CPU\fP
Anteil an der Prozessorzeit
.IP \fBTT\fP
die Nummer des kontrollierenden Teminal
.IP \fBTPGID\fP
Gruppen ID des kontrollierenden Terminal
.IP \fBPAGEIN\fP
Anzahl der Seitenfehler (das ist der Versuch auf eine
ausgelagerte Seite zuzugreifen)
.IP \fBTRS\fP
Größe des Textsegments (enhält keine shared Librarys)
.IP \fBDRS\fP
Größe des Datensegments (enthält benutzte Libraryseiten)
.IP \fBSWAP\fP
ausgelagerte Speicherseiten in Kilobyte (oder Seiten mit \fB-p\fP)
.IP \fBSHRD\fP
shared Memory
.IP \fBDT\fP
benutzte Libraryseiten in Kilobyte (oder Seiten mit \fB-p\fP)
.IP \fBF\fP
Flags
.IP \fB04\fP
Prozeß hat die Mathe Emulation benutzt
.IP \fB10\fP
Der Prozeß wurde verfolgt (traced)
.PP
Es gibt zwei unterschiedliche Versionen von \fBps\fP. Die eine greift
direkt auf den Kernelspeicher zu, aus dem sie die Prozeßtabelle
ausliest. Dazu braucht \fBps\fP die Datei /etc/psdatabase , in der die
Speicheradressen für die entsprechenden Kernelvariablen abgelegt sind.
Diese Datei muß für jeden Kernel mit dem Kommando \fBps -U\fP neu
erzeugt werden. Bei größeren Veränderungen am Kernel (in der Regel bei
neuen Kernelversionen) wird auch ein Neuübersetzen von \fBps\fP
notwendig.
.PP
Das andere \fBps\fP hat die gleiche Funktionalität und mit Ausnahme
der \fB-U\fP Option auch die gleichen Optionen, es arbeitet aber mit
dem Prozeßdateisystem. Dieses Dateisystem enthält Verzeichnisse für
alle Prozesse des Systems, in deren Unterverzeichnissen und Dateien
alle für \fBps\fP interessanten Daten zu finden sind. Das \fBps\fP
Kommando bereitet diese Daten auf und zeigt sie dem Anwender in genau
der gleichen Weise an wie die andere Version. Der Vorteil der Methode
mit dem Prozeßdateisystem besteht in der Unabhängigkeit von der
Kernelversion.
.PP
Das Verzeichnis, auf dem das Prozeßdateisystem aufgesetzt ist, kann in
der aktuellen Version des \fBprocps\fP nicht angegeben werden. Es
erwartet das Prozeßdateisystem unter dem Verzeichnis \fB/proc\fP.
.SH OPTIONEN
.IP \fB-a\fP
zeigt die Prozesse aller User
.IP \fB-c\fP
zeigt den Namen des Kommandos
.IP \fB-e\fP
zeigt die Prozeßumgebung
.IP \fB-h\fP
unterdrückt die Kopfzeile
.IP \fB-j\fP
jobs Format: \fBPGID\fP und \fBSID\fP
.IP \fB-l\fP
langes Format: \fBFLAGS\fP \fBWCHAN\fP \fBNICE\fP \fBPRIO\fP
.IP \fB-m\fP
zeigt Speichernutzung
.IP \fB-X\fP
zeigt \fBEIP\fP \fBESP\fP \fBTIMEOUT\fP und \fBALARM\fP
.IP \fB-n\fP
gibt numerische Werte für \fBUSER\fP und \fBWCHAN\fP
.IP \fB-r\fP
zeigt nur die laufenden Prozesse
.IP \fB-s\fP
zeigt die Signale
.IP \fB-u\fP
zeigt die Besitzer der Prozesse 
.IP \fB-v\fP
vm Format
.IP \fB-w\fP
ausführliche Ausgabe, kann mehrmals angegeben werden
.IP \fB-x\fP
zeigt Prozesse, die von keinem Terminal kontrolliert werden
.IP \fB-S\fP
addiert die Prozessorzeit der Kindprozesse zu den Eltern
.IP \fB-U\fP
aktualisiert die Datei /etc/psdatebase, die den Zugang zu den
Kerneldaten vermittelt; diese Aktualisierung muß immer durchgeführt
werden, nachdem der Kernel neu übersetzt wurde; diese Option fällt bei
dem \fBps\fP Programm ,das mit dem Prozessdateisystem arbeitet,
weg
.IP "\fBt \fIxx\fR"
zeigt nur die Prozesse die von Terminal
\fIxx\fP kontrolliert werden
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Branko Lankester

