.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH PWD 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"  
.SH NAME 
.B pwd
gibt den Namen des aktuellen Verzeichnisses aus
.SH SYNTAX 
.B pwd
.SH BESCHREIBUNG
.B pwd
ist in den meisten Shells ein integriertes Kommando
(z.B. in der \fBbash\fP(1))

