.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH RM 1 "1. Juli 1993" LunetIX "Linux Anwenderhandbuch"   
.SH BEZEICHNUNG 
rm \- löscht Dateien
.SH SYNTAX 
.B rm
.RB [ \-dfirvR ]   
.RB [ \-\-directory ]  
.RB [ \-\-force ]
.RB [ \-\-interactive ] 
.RB [ \-\-recursive ] 
.RB [ \-\-verbose ]
.I Pfad ...
.SH BESCHREIBUNG
.B rm
löscht Dateien. Normalerweise werden die
Verzeichnisse nicht mitgelöscht. Wenn eine Datei gelöscht werden soll,
für die keine Schreibberechtigung besteht, muß der Befehl für diese
Datei extra bestätigt werden. In Verzeichnissen, bei denen das
Stickybit gesetzt ist, kann eine Datei nur von ihrem Eigentümer
gelöscht werden.
.PP
Die Option \fB--\fP zeigt an, daß die folgenden Argumente keine Optionen
mehr sind.  Dadurch ist es möglich auch Dateinamen, die mit einem
\fB-\fP anfangen, zu löschen.
.SH OPTIONEN
.IP \fB-d\fP
löscht Verzeichnisse mit dem \fBunlink\fP Systemaufruf, anstelle von \fBrmdir\fP (nur für
den Superuser \fBroot\fP); weil die in einem so gelöschten Verzeichnis
enthaltenen Dateien nicht mitgelöscht werden, ist eine anschließende Reparatur
des Dateisystems angesagt
.IP \fB-f\fP
keine Nachfragen, keine Fehlermeldungen
.IP \fB-i\fP
vor dem Löschen jeder Datei wird nochmal nachgefragt
.IP \fB-r\fP
der Inhalt aller Unterverzeichnisse und die Verzeichnisse werden mitgelöscht
.IP \fB-v\fP
zeigt die Namen aller Dateien noch ein letztes mal an, bevor sie gelöscht
werden
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Paul Rubin, David MacKenzie und Richard Stallman

