.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH RMDIR 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
rmdir \- löscht Verzeichnisse
.SH SYNTAX 
.B rmdir
.RB [ \-p ] 
.RB [ \-\-path ]
.I Verzeichnis ...
.SH BESCHREIBUNG
.B rmdir
löscht leere Verzeichnisse. Es gibt keine
Möglichkeit, Verzeichnisse zu löschen, die noch normale Dateien enthalten.
.SH OPTIONEN
.TP
.B \-p
löscht mehrere Verzeichnisse rekursiv, wenn alle Verzeichnisse leer sind
(nachdem das Verzeichnis im Verzeichnis gelöscht ist)
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

