.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH SORT 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
sort \- sortiert die Zeilen einer Textdatei
.SH SYNTAX 
.B sort
.RB [ \-cmus ] 
.RB [ \-t  
.IR Separator ] 
.RB [ \-o 
.IR Ausgabedatei ] 
.RB [ \-bdfiMnr ] 
.RB [ +
.I POS1
.RB [ \-
.IR POS2 ]]
.RB [ \-k
.I POS1
.RB [ ,
.IR POS2 ]]
.RI [ Datei ...]
.SH BESCHREIBUNG
.B sort
wird normalerweise zum Sortieren von Dateien verwendet.  Es kann aber
auch Dateien daraufhin überprüfen, ob sie sortiert sind; oder mehrere
sortierte (oder unsortierte) Dateien zu einer sortierten zusammenfügen.
.PP
Dazu existieren drei Modi:
.RS
.IP
- der
.B check
Modus, der prüft, ob eine Datei bereits sortiert ist.  Dieser Modus
wird durch die Option
.B \-c
eingeleitet
.IP
- der
.B merge
Modus, der mehrere vorsortierte Dateien zusammenfügt.  Die Dateien so
zusammenzufügen ist schneller, als sie komplett sortierten zu lassen. 
Dieser Modus wird durch die Option
.B \-m
eingeleitet
.IP
- der Standardmodus ist
.B sort
.RE
Wenn Schlüsselfelder bezeichnet sind, vergleicht
.B sort
die Schlüsselfelder in der Reihenfolge ihrer Bezeichnung, bis ein
Unterschied gefunden wurde oder keine weiteren Felder vorhanden sind.
.PP
Wenn eine der globalen Optionen
.B Mbdfinr
benutzt wird, und kein Schlüsselfeld angegeben ist, vergleicht
.B sort
die ganzen Zeilen.
.SH OPTIONEN
.TP
.B \-b
ignoriert führende Leerzeichen
.TP
.B \-c
stellt fest, ob die Dateie(en) bereits sortiert
ist/sind; wenn eine Datei nicht sortiert ist, wird eine
Fehlermeldung ausgegeben und mit dem Status 1 abgebrochen
.TP
.B \-d
sortiert in alphabetischer Reihenfolge
.TP
.B \-f
unterscheidet nicht zwischen Groß- und Kleinschreibung
.TP
.B \-i
ignoriert alle nicht druckbaren Zeichen (außerhalb 040-126 ASCII)
.TP
.B \-M
sortiert die (amerikanischen) Monate jan feb mar ...  dec in der
korrekten Reihenfolge; führende Leerzeichen werden wie bei
.B \-b
ignoriert
.TP
.B \-m
fügt bereits sortierte Dateien Zeilenweise zusammen
.TP
.B -n
sortiert Zeilen mit Zahlen; ignoriert führende Leerzeichen und behandelt
.B \-
als Vorzeichen
.TP
.B \-r
sortiert in umgekehrter Reihenfolge
.TP
.BI \-o " Datei"
schreibt in die
.I Datei
anstelle der Standardausgabe; wenn eine der Eingabedateien als
Ausgabedatei bestimmt wird, legt
.B sort
erst eine Kopie der Eingabedatei an und sortiert dann in die Ausgabedatei
.TP
.BI \-t " Separator"
benutzt
.I Separator
als Feldtrenner für die Suchschlüssel; Standard ist der Leerstring
zwischen einem Nichtblank und einem Blank; Der Trenner ist nicht
Teil eines der getrennten Felder
.TP
.B \-u
im merge Modus wird nur die erste von einer Reihe
gleichwertiger Zeilen ausgegeben; im check Modus wird geprüft, ob
nicht zwei Zeilen gleichwertig sind
.TP
.BI + POS1 " [-" POS2 ]
bestimmt die Zeichen zwischen
.IR POS1 " und " POS2
zum Sortierschlüssel; wenn
.I POS2
fehlt, werden alle Zeichen bis zum Zeilenende zum Schlüssel;
Positionen der Felder und Buchstaben zählen von 0
.TP
.BI \-k " POS1" [, POS2 ]
bestimmt die Zeichen zwischen
.IR POS1 " und " POS2
zum Sortierschlüssel; wird das Schlüsselfeld so spezifiziert, zählen die
Felder und Buchstaben von 1
.PP
Eine Position hat die Form
.I feld.buchstabe
.SH SIEHE AUCH
das LunetIX Linuxhandbuch
.SH AUTOR
Mike Haertel

