.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH SPLIT 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
split \- spaltet eine Datei in mehrere kleinere
.SH SYNTAX 
.B split
.RB [ \-
.IR Zeilen ]
.RB [ \-l 
.IR Zeilen ] 
.RB [ \-b
.I Bytes
.RB [ bkm ]
.RB [ \-C 
.I Bytes 
.RB [ bkm ]]
.RB [ \-\-lines=
.IR \fIZeilen\fP ]
.RB [ \-\-bytes=
.I Bytes
.RB [ bkm ]]
.RB [ \-\-line-bytes=
.I Bytes
.RB [ bkm ]] 
.RI [ Datei  
.RI [ Prefix ]]
.SH BESCHREIBUNG
.B split
teilt eine Datei in mehrere Teile. Wenn keine weiteren Optionen gegeben
sind, wird die
.I Datei
in Teile zu je 1000 Zeilen aufgeteilt.  Die Ausgabe erfolgt in Dateien
mit der Endung
.I Prefix
oder
.B x
wenn kein Prefix angegeben wird.
.SH OPTIONEN
.TP
.BI \- Zeilen
die Ausgabedateien sind
.I Zeilen
lang
.TP
.BI \-l " Zeilen"
die Ausgabedateien sind
.I Zeilen
lang
.TP
\fB-b \fIBytes\fR[\fBbkm\fR]
die Ausgabedateien sind
.I Bytes
lang; die optionale Endung setzt die Einheit auf 
.RS
.TP
.B b
512 Byte Blöcke
.TP
.B k
1 Kilobyte (1024) Blöcke
.TP
.B m
1 Megabyte Blöcke
.RE
.TP
\fB-C \fIBytes\fR[\fBbkm\fR]
schreibt so viele Zeilen wie möglich in die Ausgabedatei, ohne
.I Bytes
zu überschreiten; ist eine Zeile länger als
.IR Bytes ,
wird die Zeile auf mehrere Dateien aufgeteilt, bis der Rest weniger als
.I Bytes
lang ist; die Optionen
.B bkm
werden benutzt wie bei
.B \-b
.SH "SIEHE AUCH"
.BR csplit (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
tege@sics.se

