.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH SYNC 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
.B sync
schreibt die gepufferten Blöcke auf die Platte
.SH SYNTAX 
.B sync
.SH BESCHREIBUNG
Linux unterhält zur Optimierung der
Festplatten und Diskettenzugriffe ein sogenanntes Blockdepot, in dem
wie in einem Cache einige Datenblöcke des Massenspeichers
im Arbeitsspeicher bereitgehalten werden.  Veränderungen an diesen
Daten werden zuerst nur im Arbeitsspeicher vorgenommen.  Mit dem
.B sync
Befehl können die veränderten Daten sofort auf den Massenspeicher gesichert
werden.  Normalerweise wird in regelmäßigen Abständen automatisch vom
.BR update "-Prozeß ein " sync
Systemaufruf ausgeführt.
.PP
Gelegentlich, zum Beispiel vor dem Ausschalten des Rechners, ist es
sinnvoll, ein manuelles
.B sync
vorzunehmen. Wird der Rechner z.B. infolge eines Defektes ohne
Datensynchronisation abgeschaltet, kommt es meist zu Datenverlusten
und Fehlern im Dateisystem.

