.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH TAR 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
tar \- (tape archiver) verwaltet Dateiarchive
.SH SYNTAX 
.B tar
.RB [ \-Acdrtux ] 
.RB [ +delete ] 
.RB [ \-b 
.IR N ]
.RB [ \-BgGhiklmMoOpPPsSvwWz ] 
.RB [ \-C 
.IR Verzeichnis ] 
.RB [ \-f 
.IR Datei ] 
.RB [ \-F 
.IR Datei ]
.RB [ \-K 
.IR Datei ] 
.RB [ \-L 
.IR Länge ]  
.RB [ \-N 
.IR Datum ] 
.RB [ \-T 
.IR Datei ] 
.RB [ \-V 
.IR Name ] 
.RB [ \-X 
.IR Datei ] 
.RB [ 0 - 7 ]
.RB [{ lmh }]
.SH BESCHREIBUNG
.B tar
ist ursprünglich ein Tool zur Verwaltung von Bandarchiven.  Das
.B "GNU tar"
kann aber auch auf rohen Disketten oder in normalen Dateien Archive im
.B tar
Format anlegen und verwalten.  Normalerweise werden Archive mit
.B tar
nicht komprimiert.  Das GNU
.B tar
kann aber die Ein- und Ausgabe durch einen Kompressor leiten.  Die
neuen Versionen (ab 1.11.2) unterstützen sowohl
.B compress
als auch
.BR gzip .
.PP
Linux kann alle SCSI Streamer und mit Kernelpatches auch QIC-02 Streamer
betreiben.  Wenn keine Datei und kein Gerät angegeben ist, versucht
.B tar
auf einen Streamer zuzugreifen.  Je nach Konfiguration ist das meist
/dev/tape oder /dev/rmt0.
.SH OPTIONEN
.TP
.B -A
hängt ein komplettes Archiv an ein anderes Archiv an
.TP
.B -c
erzeugt ein neues Archiv
.TP
.B -d
vergleicht das Archiv mit dem Dateisystem
.TP
.BI -D " Datei"
löscht die
.I Datei
aus dem Archiv (für Bandarchive nicht empfehlenswert)
.TP
.B -r
hängt Dateien an das Archiv an
.TP
.B -t
zeigt den Inhalt des Archivs
.TP
.B -u
ersetzt Dateien, die neuer als eine bereits archivierte Version
sind.  Ist eine Datei noch nicht archiviert, so wird sie eingefügt
.TP
.B -x
kopiert
.I Datei
oder alle Dateien aus dem Archiv
.PP
Weitere Optionen
.TP
.BI -b " N"
setzt die Blockgröße auf
.IR N =x512
Bytes (Voreinstellung ist N=20)
.TP
.B -B
unterdrückt den Abbruch von
.B tar
beim Lesen unvollständiger Blöcke; zum Lesen von 4.2BSD Pipes
.TP
.BI -C " Verzeichnis"
wechselt während der Ausführung in das
.IR Verzeichnis ,
um von dort weitere Dateien zu archivieren
.TP
.BI -f " Datei"
benutzt
.I Datei
oder das damit verbundenen Gerät als Archiv
.TP
.BI -F " Datei"
bei mehrteiligen Archiven (Option -M) wird das Shellscript
.I Datei
ausgeführt, wenn das Medium voll ist
.TP
.B -G
erzeugt einen speziellen Eintrag für jedes archivierte Verzeichnis;
spezielles GNU Format (alt)
.TP
.B -g
erzeugt auch einen Eintrag für jedes Verzeichnis, auch spezielles
GNU Format (neu)
.TP
.B -h
archiviert die referenzierten Dateien anstelle der Links
.TP
.B -i
ignoriert Blöcke mit Nullbytes im Archiv
.TP
.B -k
existierende Dateien werden nicht überschrieben
.TP
.BI -K " Datei"
beginnt eine Aktion bei
.I Datei
im Archiv
.TP
.B -l
verhindert Archivierung von Dateien aus anderen Dateisystemen
.TP
.BI -L " Länge"
wartet auf Medienwechsel nach
.IR Länge Bytes
.TP
.B -m
das Datum der letzten Änderung wird nicht mit archiviert
.TP
.B -M
das Archiv ist auf mehrere Medien verteilt (Multi-Volume)
.TP
.BI -N " Datum"
archiviert nur Dateien, die neuer sind als
.I Datum
.TP
.B -o
benutzt das alte V7 tar-Format anstelle des ANSI Formates
.TP
.B -O
schreibt die Dateien in die Standardausgabe
.TP
.B -p
erhält die Zugriffsrechte der Dateien
.TP
.B -P
archiviert mit absoluten Dateinamen
.TP
.B -R
gibt zu jeder Meldung die Blocknummer des Archivblocks aus, von dem
die Meldung verursacht wurde
.TP
.B -s
zeigt an, daß die Liste von Dateien im Argument die gleiche Reihenfolge
hat, wie die Dateien im Archiv
.TP
.BI -T " Datei"
holt die Namen der zu archivierenden Dateien aus
.I Datei
.TP
.B -v
meldet jede Aktion
.TP
.BI -V " Name"
erzeugt ein Archiv mit dem (internen) Label
.I Name
.TP
.B -w
erwartet interaktiv Bestätigung jeder Aktion
.TP
.B -W
verifiziert die geschriebenen Daten im Archiv
.TP
.BI -X " Datei"
liest aus der
.I Datei
Namen oder reguläre Ausdrücke von bzw. für Dateien, die nicht
archiviert werden sollen
.TP
.B -z
erzeugt ein mit
.B gzip
komprimiertes Archiv
.TP
.B -Z
erzeugt ein mit
.B compress
komprimiertes Archiv
.TP
.B -{0..7}{lmh}
spezifiziert das Gerät und die Dichte
des Speichermediums (für Diskettenarchive ohne Bedeutung); 0 ist der
erste Streamer, 1 der zweite und so weiter; die Dichte bestimmt den
Bandtyp
.SH SIEHE AUCH
.BR cpio (1),
.BR mt (1),
.BR shar (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
John Gilmore

