.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH TTY 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
tty \- gibt die Bezeichnung des aktuellen Terminals aus
.SH SYNTAX 
.B tty
.RB [ \-s ] 
.RB [ \-\-silent ] 
.RB [ \-\-quiet ]
.SH BESCHREIBUNG
.B tty
gibt den Namen des Terminals inclusive Pfad aus, das die Standardeingabe
repräsentiert.  Der Status wird dabei wie folgt gesetzt:
.TP
.B 0
wenn die Standardeingabe ein Terminal ist
.TP
.B 1
wenn die Standardeingabe nicht ein Terminal ist
.TP
.B 2
wenn ein anderer Fehler aufgetreten ist
.SH OPTIONEN
.TP
.B \-s
keine Ausgabe. Nur der Status wird gesetzt
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

