.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH UNAME 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
uname \- gibt Auskunft über Betriebssystem und Hardware
.SH SYNTAX 
.B uname
.RB [ \-snrvma ] 
.RB [ \-\-sysname ] 
.RB [ \-\-nodename ] 
.RB [ \-\-release ] 
.RB [ \-\-version ] 
.RB [ \-\-machine ] 
.RB [ \-\-all ]
.SH OPTIONEN
.TP
.B \-s
zeigt den Betriebssystemnamen (Voreinstellung wenn keine Option angegeben wird)
.TP
.B \-n
zeigt den Netzwerknamen des Systems
.TP
.B \-r
zeigt die Release (Versionsnummer) des Betriebssystems
.TP
.B \-v
zeigt das Erstellungsdatum des Betriebssystems
.TP
.B \-m
zeigt den Prozessortyp
.TP
.B \-a
zeigt alle der oben genannten Daten
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
David MacKenzie

