.\" {PTM/TW/0.1/19-06-1999/"X11 ICQ klient"}
.\" Translation (c) 1999 Tomasz Wendlandt <juggler@cp.pl>.
.\" Kosmetyka stylistyczna - PB.
.TH licq 1
.SH NAZWA
licq \- klient ICQ dla X11
.PP
.SH SKŁADNIA
.B licq
[\-h] [\-b dir] [\-d #]
.SH OPIS
Licq jest klientem ICQ dla X11 zbudowanym wg interfejsu bibliotek QT. Posiada
większość cech oryginalnego klienta Mirabilis, w tym wysyłanie wiadomości,
chat i przekaz plikowy.
.SS OPIS
.TP
.I "\-h"
Drukuje na standardowym wyjściu informacje użycia i wychodzi.
.TP
.I "\-b katalog"
Wskazuje na bazowy katalog, zawierający konfigurację i pliki
(standardowo: $HOME/.licq)
.TP
.I "\-d #"
Ustawia poziom debuga.
.br
1 - pokazuje informacje startowe.
.br
2 - zrzuca każdy nadesłany pakiet.
.SH PLIKI
.TP 5
$HOME/.licq
katalog z danymi o konfiguracji.
.SH PRAWA AUTORSKIE
Copyright (C) 1998 Graham Roff i wielu innych
.br
Program jest rozpowszechniany na warunkach Powszechnej Licencji GNU (GPL).
Zobacz pliki CREDITS i COPYING w źródłach dystrybucji, aby dowiedzieć się
więcej.
