.\" {PTM/WK/2000-VI}
.ds VE LPRng-3.6.13
.TH MONITOR 1 \*(VE "LPRng"
.ig
monitor.1,v 3.40 1998/03/29 18:37:49 papowell Exp
..
.SH NAZWA
monitor \- otrzymuj informację logu z LPD
.SH SKŁADNIA
.B monitor
.RB [ \-u ]
.RB [ \-t ]
.RI [ port ]
.SH OPIS
Program
.B monitor
jest szablonem programu monitorującego status drukarki.
Otwiera podany port TCP i/lub UDP, a następnie oczekuje na przesłanie
informacji rozliczeniowych lub innych.
Wypisuje te informacje na swym standardowym wyjściu.
.SH OPCJE
.TP
.B \-u
Czeka na połączenia na porcie UDP.
.TP
.B \-t
Czeka na połączenia na porcie TCP.
.TP
.I port
Posługuje się podanym numerem portu.
.SH "ZOBACZ TAKŻE"
.BR lpd.conf (5),
.BR lpc (8),
.BR lpd (8),
.BR lpr (1),
.BR lpq (1),
.BR lprm (1),
.BR printcap (5),
.BR lpd.conf (5),
.BR pr (1).
.SH "HISTORIA"
LPRng jest rozszerzonym systemem buforowania wydruku o funkcjonalności podobnej
do oprogramowania Berkeley LPR. Listą dyskusyjną o LPRng jest lprng@lprng.com;
subskrypcja przez wysłanie listu do lprng-request@lprng.com ze słowem
`subscribe` w treści.
Oprogramowanie to jest dostępne z ftp://ftp.astart.com/pub/LPRng.
.SH "AUTOR"
Patrick Powell <papowell@astart.com>.
