.\" {PTM/WK/1999-XII}
.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH SETFDPRM 1 "20 listopada 1993" "Linux 0.99" "Podręcznik Programisty Linuksa"
.SH NAZWA
setfdprm \- ustawia zadane przez użytkownika parametry dyskietki
.SH SKŁADNIA
.B setfdprm
.RB [ \-p ]
.I device nazwa
.br
.B setfdprm
.RB [ \-p ]
.I device size sectors heads tracks stretch gap rate spec1 fmt_gap
.br
.B setfdprm
.RB [ \-c ]
.I device
.br
.B setfdprm
.RB [ \-y ]
.I device
.br
.B setfdprm
.RB [ \-n ]
.I device
.SH OPIS
.B setfdprm
jest narzędziem, które można wykorzystać do ładowania (odtwarzania) parametrów
dysku dla urządzeń dyskietkowych o automatycznie wykrywanych parametrach
nośnika. Można nim również czyścić stare ustawienia parametrów oraz wyłączać
i włączać komunikaty diagnostyczne.
.PP
Bez podanych opcji
.B setfdprm
ładuje urządzenie
.I device
(zwykle
.I /dev/fd0
lub
.IR /dev/fd1 )
nowymi ustawieniami parametrów z pozycji o zadanej
.I nazwie
znalezionej w
.I /etc/fdprm
(zwykle są to nazwy 360/360, itd.). Parametry te działają aż do wymiany
nośnika.
.SH OPCJE
.TP
.BI \-p " device nazwa"
Ładuje na stałe nowe ustawienia parametrów dla zadanego auto-konfigurowanego
urządzenia dyskietek. Ładowana jest konfiguracja o zadanej
.I nazwie
z
.IR /etc/fdprm .
Parametry mogą też zostać podane wprost z wiersza poleceń.
.TP
.BI \-c " device"
Czyści ustawienia parametrów dla zadanego auto-konfigurowanego urządzenia
dyskietek.
.TP
.BI -y " device"
Włącza komunikaty rozpoznawania formatu dla automatycznie konfigurowanego
urządzenia dyskietek.
.TP
.BI -n " device"
Wyłącza komunikaty rozpoznawania formatu dla automatycznie konfigurowanego
urządzenia dyskietek.
.SH BŁĘDY
Ta dokumentacja jest całkiem niepełna.
.SH PLIKI
.I /etc/fdprm
.SH AUTOR
Werner Almesberger (almesber@nessie.cs.id.ethz.ch)
