.\" 2000 PTM Przemek Borys <pborys@dione.ids.pl>
'\" t
.\"***************************************************************************
.\" Copyright (c) 1998 Free Software Foundation, Inc.                        *
.\"                                                                          *
.\" Permission is hereby granted, free of charge, to any person obtaining a  *
.\" copy of this software and associated documentation files (the            *
.\" "Software"), to deal in the Software without restriction, including      *
.\" without limitation the rights to use, copy, modify, merge, publish,      *
.\" distribute, distribute with modifications, sublicense, and/or sell       *
.\" copies of the Software, and to permit persons to whom the Software is    *
.\" furnished to do so, subject to the following conditions:                 *
.\"                                                                          *
.\" The above copyright notice and this permission notice shall be included  *
.\" in all copies or substantial portions of the Software.                   *
.\"                                                                          *
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *
.\" IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *
.\" DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *
.\" OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *
.\" THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
.\"                                                                          *
.\" Except as contained in this notice, the name(s) of the above copyright   *
.\" holders shall not be used in advertising or otherwise to promote the     *
.\" sale, use or other dealings in this Software without prior written       *
.\" authorization.                                                           *
.\"***************************************************************************
.\"
.\" $Id: tput.1,v 1.1 2000/02/15 20:15:08 pborys Exp $
.TH tput 1 ""
.ds d /usr/share/terminfo
.ds n 5
.SH NAZWA
\fBtput\fR - inicjalizuj terminal lub pytaj bazę terminfo
.SH SKŁADNIA
\fBtput\fR [\fB-T\fR\fItyp\fR] \fInazwawłaściwości\fR [\fIparm\fR ... ]
.br
\fBtput\fR [\fB-T\fR\fItyp\fR] \fBinit\fR
.br
\fBtput\fR [\fB-T\fR\fItyp\fR] \fBreset\fR
.br
\fBtput\fR [\fB-T\fR\fItyp\fR] \fBlongname\fR
.br
\fBtput \-S\fR  \fB<<\fR
.br
.SH OPIS
Narzędzie \fBtput\fR robi użytek z bazy \fBterminfo\fR, dając możlwiość
dojścia do zależnych od terminala właściwości z poziomu powłoki (zobacz
\fBsh\fR(1)), a także inicjalizowania lub resetowania terminala, lub
zwracania długiej nazwy żądanego typu terminala. 
.PP
Jeśli atrybut
(\fInazwawłaściwości\fR) jest typu łańcuchowego, \fBtput\fR wydaje wartość
łańcuchową, a jeśli jest typu całkowitego, wydaje liczbę całkowitą.
Jeśli atrybut jest wartością logiczną, \fBtput\fR po prostu ustawia kod
wyjścia (\fB0\fR to prawda, jeśli terminal ma daną właściwość, a \fB1\fR to
fałsz, jeśli terminal żądanej właściwości nie posiada) i nie wydaje żadnego
wyjścia tekstowego. 
.PP
Przed użyciem zwróconej wartości, użytkownik powinien
przetestować kod wyjscia i upewnić się, że wynosi on \fB0\fR.
(Zobacz sekcje \fBKODY WYJŚCIA\fR i \fBDIAGNOSTYKA\fR.)
Dla kompletnej listy właściwości i \fInazwwłaściwości\fR związanych z każdą
z nich, zobacz \fBterminfo\fR(\*n).
.TP
\fB-T\fR\fItyp\fR
określa typ terminala. Normalnie opcja ta jest niepotrzebna, gdyż wartość
domyślna jest pobierana ze zmiennej środowiskowej \fBTERM\fR. Jeśli podane
jest \fB-T\fR, zmienne powłoki \fBLINES\fR i \fBCOLUMNS\fR będą ignorowane,
a system operacyjny nie będzie zapytywany o rzeczywisty rozmiar ekranu.
.TP
\fInazwawłaściwości\fR
określa atrybut z bazy \fBterminfo\fR. Gdy wkompilowana jest obsługa
\fBtermcap\fR, można podawać również termcapowe nazwy atrybutów.
.TP
\fIparm\fR
Jeśli atrybut jest łańcuchem, który wymaga parametrów, argumenty
\fIparam\fR zostaną przeniesione do tego łańcucha. Wszystkie argumenty
numeryczne zostaną atrybutowi przekazane jako liczby.
.TP
\fB-S\fR
umożliwiwa używanie więcej niż jednej właściwości na jedno wywołanie
\fBtput\fR. Właściwości muszą być przekazywane do \fBtput\fR ze
standardowego wejścia, a nie przez linię poleceń (zobacz przykład). Na linię
dozwolona jest tylko jedna \fInazwawłaściwości\fR. Opcja \fB-S\fR zmienia
znaczenie kodów wyjścia \fB0\fR i \fB1\fR (zobacz sekcję KODY WYJŚCIA).
.TP
\fBinit\fR
Jeśli baza \fBterminfo\fR istnieje i znajduje się w niej opis dla terminala
użytkownika (zobacz wyżej \fB-T\fItyp\fR), to stanie sie co następuje:
(1) jeśli istnieją łańcuchy inicjalizacyjne, to zostaną one wysłane
(\fBis1\fR, \fBis2\fR, \fBis3\fR, \fBif\fR, \fBiprog\fR), (2)
wszelkie opóźnienia (np. nowej linii), podane w opisie zostaną ustawione w
sterowniku tty, (3) rozszerzanie tabulacji zostanie włączone lub wyłączone,
zależnie od specyfikacji w opisie i (4) jeśli tabulacje nie są rozszerzane,
ustawione zostaną standardowe tabulacje (co 8 spacji).
Jeśli opis nie zawiera informacji wymaganej dla któregoś z tych czterech
działań, to zostanie ono cicho pominięte.
.TP
\fBreset\fR
Zamiast wystawiania łańcuchów inicjalizacji, wysłane zostaną (o ile są
obecne) łańcuchy resetowania (\fBrs1\fR, \fBrs2\fR, \fBrs3\fR, \fBrf\fR).
Jeśli łańcuchy resetowania nie są zdefiniowane, lecz zdefiniowane są
łańcuchy inicjalizacji, to wysłane zostaną łańcuchy inicjalizacji. W
przeciwnym wypadku, \fBreset\fR działa analogicznie do \fBinit\fR.
.TP
\fBlongname\fR
Jeśli obecna jest baza terminfo i istnieje w niej opis dla terminala
użytkownika (zobacz wyżej \fB-T\fItyp\fR), to wyświetlona zostanie długa
nazwa terminala. Długa nazwa jest ostatnią nazwą w pierwszej linii opisu
terminala w bazie terminfo [zobacz \fBterm\fR(5)].
.SH PRZYKŁADY
.TP 5
\fBtput init\fR
Inicjalizuj terminal według typu terminala ze zmiennej środowiskowej
\fBTERM\fR. Komenda ta powinna być załączona do .profile każdego użytkownika
po wyeksportowaniu zmiennej środowiskowej \fBTERM\fR, jak pokazano w
podręczniku \fBprofile\fR(4).
.TP 5
\fBtput \-T5620 reset\fR
Resetuj terminal AT&T 5620, przeciążając rodzaj terminala ze zmiennej
środowiskowej \fBTERM\fR.
.TP 5
\fBtput cup 0 0\fR
Wyślij sekwencję do przesunięcia kursora do wiersza \fB0\fR, kolumny \fB0\fR
(lewy górny narożnik ekranu, znany zwykle jako "domowa" (home) pozycja
kursora).
.TP 5
\fBtput clear\fR
Wyślij na bieżący terminal sekwencję czyszczącą ekran.
.TP 5
\fBtput cols\fR
Wydrukuj liczbę kolumn w bieżącym terminalu.
.TP 5
\fBtput \-T450 cols\fR
Wydrukuj liczbę kolumn terminala 450.
.TP 5
\fBbold=`tput smso` offbold=`tput rmso`\fR
Ustaw zmienne powłoki \fBbold\fR na początek sekwencji trybu standout i
\fBoffbold\fR na koniec sekwencji trybu standout bieżącego terminala. Może
to być użyte w znaku zachęty:
\fBecho "${bold}Proszę wpisać imię: ${offbold}\\c"\fR
.TP 5
\fBtput hc\fR
Ustaw kod wyjścia, określający czy terminal jest terminalem hard copy.
.TP 5
\fBtput cup 23 4\fR
Wyślij sekwencję przesuwającą kursor do wiersza 23 w 4 kolumnie.
.TP 5
\fBtput longname\fR
Wydrukuj długą nazwę terminala \fBTERM\fR, określoną w bazie \fBterminfo\fR.
.TP 0
\fBtput \-S <<!\fR
.br
\fB> clear\fR
.br
\fB> cup 10 10\fR
.br
\fB> bold\fR
.br
\fB> !\fR
.TP 5
\&
Ten przykład pokazuje przetwarzania przez tput kilku właściwości w jednym
wywołaniu. Przykład ten czyści ekran, przesuwa kursor do pozycji 10, 10 i
włącza tryb wytłuszczenia. Lista jest kończona znakiem wykrzyknika,
znajdującym się w osobnej linii.
.SH PLIKI
.TP
\fB\*d\fR
skompilowana baza opisu terminala
.TP
\fB/usr/include/curses.h\fR
plik nagłówkowy \fBcurses\fR(3X)
.TP
\fB/usr/include/term.h\fR
plik nagłówkowy \fBterminfo\fR
.TP
\fB/usr/share/tabset/*\fR
ustawienia tab dla niektórych terminali w formacie odpowiednim do wysyłania
na terminal (sekwencje specjalne, ustawiające marginesy i tabulacje); dla
dalszych informacji, zobacz sekcję "Tabs and Initialization"
\fBterminfo\fR(4).
.SH ZOBACZ TAKŻE
\fBclear\fR(1), \fBstty\fR(1), \fBtabs\fR(\*n).  \fBprofile\fR(\*n),
\fBterminfo\fR(4) w podręczniku \fISystem\fR \fIAdministrator\fR'\fIs\fR
\fIReference\fR \fIManual\fR.  Rozdział 10 podręcznika
\fIProgrammer\fR'\fIs\fR \fIGuide\fR.
.SH KODY WYJŚCIA
Jeśli \fInazwawłaściwości\fR jest typu logicznego, dla prawdy zwracana jest
wartość \fB0\fR, a dla fałszu \fB1\fR. Wyjątkiem jest użycie opcji \fB-S\fR.

Jeśli \fInazwawłaściwości\fR jest typu łańcuchowego, zwracane jest \fB0\fR,
gdy własciwość jest zdefiniowana dla tego terminala (wartość
\fInazwywłaściwości\fR jest zwracana na standardowe wyjście); zwracane jest
\fB1\fR jeśli właściwość \fInazwawłaściwości\fR nie jest zdefiniowana dla
tego terminala (na stdout nie jest nic wypisywane).

Jeśli \fInazwawłaściwości\fR jest typu logicznego, lub łańcuchowego i użyto
opcji \fB-S\fR, w wypadku gdy wszystkie linie były pomyślne zwracane jest
\fB0\fR. Ponieważ nie można określić, która z linii się nie powiodła, nie
jest zwracana wartość \fB1\fR. Kody wyjścia \fB2\fR, \fB3\fR i \fB4\fR mają
swoją tradycyjną interpretację.

Jeśli \fInazwawłaściwości\fR jest typu całkowitego, zwracane jest zawsze
\fB0\fR. Aby określić czy własciwość jest zdefiniowana, użytkownik musi
testować wartość standardowego wyjścia. Wartość \fB-1\fR oznacza, że
własciwość nie jest zdefiniowana dla tego terminala.

Wszystkie inne kody wyjścia oznaczają błędy; zobacz sekcję DIAGNOSTYKA.
.SH DIAGNOSTYKA
\fBtput\fR drukuje następujące komunikaty o błędach i ustawia odpowiednie
kody błędów:

.TS
l l.
kod błędu	komunikat błędu
\fB0\fR	(\fInazwawłaściwości\fR jest zmienną numeryczną, która nie jest
	podana w bazie \fBterminfo\fR(\*n) tego typu terminala, np.
	\fBtput \-T450 lines\fR i \fBtput \-T2621 xmc\fR)
\fB1\fR	nie jest drukowany żaden komunikat błędu, zobacz sekcję
	\fBKODY WYJŚCIA\fR.
\fB2\fR	błąd użycia.
\fB3\fR	nieznany typ terminala, lub brak bazy \fBterminfo\fR.
\fB4\fR	nieznana własciwość \fInazwawłaściwości\fR \fBterminfo\fR
.TE
.SH PRZENOŚNOŚĆ
Opcje \fBlongname\fR i \fB\-S\fR oraz właściwości podstawiania parametrów,
używane w przykładzie \fBcup\fR nie są obsługiwane w BSD curses i w
AT&T/USL curses przed SVr4.
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
