.\" $Id: isdnlog.5,v 1.2 2001-12-31 15:05:01 joey Exp $
.\"
.\" German translation by Holger Jannsen <hollysoft@gmx.de> and Martin Schulze <joey@infodrom.org>
.\"
.TH isdnlog 5 "6. November 2000" "ISDN 4 Linux 3.1pre1" "Dateiformate"
.SH BEZEICHNUNG
/var/lib/isdn/calls \- isdn log file
.SH BESCHREIBUNG
Das Programm
.B isdnlog
wurde hauptsächlich dafür erstellt, um den ein- und ausgehenden
Verkehr über die ISDN-Karte in eine Protokolldatei zu schreiben.
Standardmäßig ist das diese Datei unter
.IR /var/log/isdn.log .

Die Datei hat in jeder Protokollzeile 19 Felder, die durch das
PIPE-Zeichen "|" getrennt werden.  Die Felder sind folgendermaßen
definiert:

.PD 0
.TP 4
 1
Zeitstempel der Verbindung (Monat Tag Uhrzeit Jahr)
.TP
 2
Nummer des Anrufers (sofern übermittelt)
.TP
 3
Angerufende Nummer
.TP
 4
Dauer der Verbindung in Sekunden
.TP
 5
Dauer der Verbindung in Hundertstel-Sekunden
.TP
 6
Zeitstempel der Verbindung (in Sekunden seit 1970)
.TP
 7
Anzahl der empfangenen Einheitensignale (-1 when keine
Einheitensignale empfangen wurden)
.TP
 8
I = "Einkommende Anrufe" (Incoming) oder
.br
O = "Ausgehende Anrufe" (Outgoing)
.TP
 9
Fehlernummer, die angibt, warum eine Verbindung nicht
aufgebaut werden konnte
.TP
10
Anzahl der empfangenen Bytes (incoming
.TP
11
Anzahl der gesendeten Bytes (outgoing)
.TP
12
Versionsnummer von
.B isdnlog
.TP
13
Nummer des in Anspruch genommenen ISDN-Services
.TP
14
1 = Anruf von einem ISDN-Anschluß,
.br
0 = Anruf von einem analogen Anschluß
.TP
15
Kosten einer Einheit (z.B. 0.12 in Deutschland)
.TP
16
Währungseinheit (z.B. EUR in weiten Teilen Europas)
.TP
17
Gesamtkosten der Verbindung
.TP
18
Provider
.TP
19
Zone

.SH DATEIEN
.TP
.I /var/lib/isdn/calls
Diese Protokolldatei.

.SH "SIEHE AUCH"
.BR isdnlog (8).

.SH AUTOR
Das englische Original wurde von Andreas Jellinghaus <aj@debian.org>
für Debian GNU/Linux und isdn4linux geschrieben.  Die deutsche
Übersetzung stammt von Holger Jannsen <hollysoft@gmx.de> und Martin
Schulze <joey@infodrom.org>.
