.TH "libalpm" 3 "Wed Jul 20 2022" "libalpm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libalpm \- The libalpm Public API
.PP
 \- libalpm is a package management library, primarily used by pacman\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBFiles\fP"
.br
.RI "Functions for package files\&. "
.ti -1c
.RI "\fBGroups\fP"
.br
.RI "Functions for package groups\&. "
.ti -1c
.RI "\fBError Codes\fP"
.br
.RI "Error codes returned by libalpm\&. "
.ti -1c
.RI "\fBHandle\fP"
.br
.RI "Functions to initialize and release libalpm\&. "
.ti -1c
.RI "\fBSignature checking\fP"
.br
.RI "Functions to check signatures\&. "
.ti -1c
.RI "\fBDependency\fP"
.br
.RI "Functions dealing with libalpm's dependency and conflict information\&. "
.ti -1c
.RI "\fBCallbacks\fP"
.br
.RI "Functions and structures for libalpm's callbacks\&. "
.ti -1c
.RI "\fBDatabase\fP"
.br
.RI "Functions to query and manipulate the database of libalpm\&. "
.ti -1c
.RI "\fBLogging Functions\fP"
.br
.RI "Functions to log using libalpm\&. "
.ti -1c
.RI "\fBOptions\fP"
.br
.RI "Libalpm option getters and setters\&. "
.ti -1c
.RI "\fBPackage Functions\fP"
.br
.RI "Functions to manipulate libalpm packages\&. "
.ti -1c
.RI "\fBTransaction\fP"
.br
.RI "Functions to manipulate libalpm transactions\&. "
.ti -1c
.RI "\fBMiscellaneous Functions\fP"
.br
.RI "Various libalpm functions\&. "
.ti -1c
.RI "\fBlibalpm_list(3)\fP"
.br
.RI "Functions to manipulate \fBalpm_list_t\fP lists\&. "
.in -1c
.SH "Detailed Description"
.PP 
libalpm is a package management library, primarily used by pacman\&. 

For ease of access, the libalpm manual has been split up into several sections\&.
.SH "See Also"
.PP
\fBlibalpm_list(3)\fP, \fBlibalpm_cb(3)\fP, \fBlibalpm_databases(3)\fP, \fBlibalpm_depends(3)\fP, \fBlibalpm_errors(3)\fP, \fBlibalpm_files(3)\fP, \fBlibalpm_groups(3)\fP, \fBlibalpm_handle(3)\fP, \fBlibalpm_log(3)\fP, \fBlibalpm_misc(3)\fP, \fBlibalpm_options(3)\fP, \fBlibalpm_packages(3)\fP, \fBlibalpm_sig(3)\fP, \fBlibalpm_trans(3)\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for libalpm from the source code\&.
