.\" Copyright (C) 1996 Free Software Foundation, Inc.
.\" This file is distributed accroding to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.\"
.\" Translation (c) 1998 Przemek Borys <pborys@p-soft.silesia.linux.org.pl>
.TH CREATE_MODULE 2 "26 grudnia 1996" Linux "Wsparcie dla modułów"
.SH NAZWA
create_module \- tworzy wpis ładowalnego modułu
.SH SKŁADNIA
.nf
.B #include <linux/module.h>
.sp
.BI "caddr_t create_module(const char *" name ", size_t " size );
.fi
.SH OPIS
.B create_module
próbuje utworzyć wpis ładowalnego modułu i zarezerwować pamięć jądra,
której moduł będzie wymagał. Ta funkcja jest przeznaczona jedynie dla
superużytkownika.
.SH "WARTOŚĆ ZWRACANA"
W przypadku sukcesu, zwraca adres z przestrzeni jądra, pod którym znajduje
się moduł. W przypadku błędu zwracane jest \-1 i odpowiednio ustawiane
\fIerrno\fP .
.SH BŁĘDY
.TP
.B EPERM
Użytkownik nie jest superużytkownikiem.
.TP
.B EEXIST
Moduł o takiej nazwie już istnieje.
.TP
.B EINVAL
Żądany rozmiar jest zbyt mały, nawet na informacje z nagłówka modułu.
.TP
.B ENOMEM
Kernel nie mógł przydzielić dostatecznie dużego, ciągłego bloku pamięci by
pomieścić moduł.
.TP
.B EFAULT
.I name 
jest poza dostępną przestrzenią adresową.
.SH "ZOBACZ TAKŻE
.BR init_module "(2), " delete_module "(2), " query_module "(2)."
