.\" Copyright (C) 1996 Free Software Foundation, Inc.
.\" This file is distributed accroding to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.\"
.\" Translation (c) 1998 Przemek Borys <pborys@p-soft.silesia.linux.org.pl>
.TH DELETE_MODULE 2 "26 grudnia 1996" Linux "Wsparcie dla modułów"
.SH NAZWA
delete_module \- usuwa wpis ładowalnego modułu.
.SH SKŁADNIA
.nf
.B #include <linux/module.h>
.sp
.BI "int delete_module(const char *" name );
.fi
.SH OPIS
.B delete_module
próbuje usunąć wpis nieużywanego ładowalnego modułu. Jeśli \fIname\fP jest
równe \fBNULL\fP, to zostaną usunięte wszystkie nieużywane moduły zaznaczone
jako usuwalne automatycznie. Tę funkcję może wywoływać tylko superużytkownik.
.SH "WARTOŚĆ ZWRACANA"
W przypadku sukcesu zwracane jest zero. W przypadku błędu, \-1 i odpowiednio
ustawiane jest \fIerrno\fP.
.SH BŁĘDY
.TP
.B EPERM
Użytkownik nie jest superużytkownikiem.
.TP
.B ENOENT
Nie istnieje moduł o tej nazwie.
.TP
.B EINVAL
\fIname\fP był pustym ciągiem znaków.
.TP
.B EBUSY
Moduł jest używany.
.TP
.B EFAULT
.I name 
jest poza dostępną przestrzenią adresową.
.SH "ZOBACZ TAKŻE
.BR create_module "(2), " init_module "(2), " query_module "(2).
