.TH NAMEIF 8 "2008\-10\-03" "net\-tools" "Linux System Administrator's Manual"
.SH NAME
nameif \- name network interfaces based on MAC addresses
.SH SYNOPSIS
.B "nameif [\-c configfile] [\-s]"
.br
.B "nameif [\-c configfile] [\-s] [interface macaddress]"
.br
.B "nameif [-c configfile] [-r] [newifname oldifname]"
.SH DESCRIPTION
.B nameif
renames network interfaces based on mac addresses or interface names.
When no arguments are given
.I /etc/mactab
is read. Each line  of it contains an interface name and a Ethernet MAC
address. Comments are allowed starting with #.
Otherwise the interfaces specified on the command line are processed.
.I nameif
looks for the interface with the given MAC address or old interface name
and renames it to the name given.
.SH OPTIONS
.TP
.B "[-s|--syslog]"
Log all error messages to syslog.
.TP
.B "[-r|--rename]"
Rename the interface given by
.I oldifname
to the new name
.I newifname
without consulting any macaddress.
.TP
.B "[-c|--config-file configfile]"
Read
.I configfile
instead of
.I /etc/mactab.

.SH NOTES
.I nameif
should be run before the interface is up, otherwise it'll fail.

.SH FILES
/etc/mactab
.SH BUGS
Only works for Ethernet currently.
