.TH leaftoppm 1 "01 June 2000"
.IX leaftoppm
.SH NAME
leaftoppm - convert Interleaf image format to a portable anymap
.SH SYNOPSIS
.B leaftoppm
.RI [ leaffile ]

.SH DESCRIPTION
Reads a portable pixmap (PPM file) as input.
Generates an Interleaf image file as output.

Interleaf is a now-defunct (actually purchased ca. 2000 by BroadVision)
technical publishing software company.


.SH "SEE ALSO"
.BR ppm (5)

.SH AUTHOR
The program is copyright (C) 1994 by Bill O'Donnell.
