.TH pgmkernel 1 "10 December 1992"
.IX pgmkernel
.SH NAME
pgmkernel - generate a convolution kernel
.SH SYNOPSIS
.B pgmkernel
[
.B \-weight
.I w
]
.I width 
[ 
.I height 
]
.SH DESCRIPTION
Generates a portable graymap array of size
.I width 
x 
.I height 
(or 
.I width 
x 
.I width 
if 
.I height 
is not specified) to be used as a convolution file by
.BR pnmconvol .
The data in the convolution array K are computed according to the
formula:
.PP
K(i,j) = 1 / ( 1 + w * sqrt((i-width/2)^2 + (j-height/2)^2)) 
.PP
where 
.I w 
is a coefficient specified via the 
.I \-weight 
flag, and
.I width 
and 
.I height
are the X and Y filter sizes.
.PP
The output PGM file is always written out in ASCII format.
.SH OPTIONS
The optional 
.I -weight 
flag should be a real number greater than -1.
The default value is 6.0.
.SH BUGS
The computation time is proportional to 
.I width 
* 
.IR height .
This increases rapidly with the increase of the kernel size.  
A better approach could be using a FFT in these cases.
.SH "SEE ALSO"
pnmconvol(1), pnmsmooth(1)
.SH AUTHOR
Alberto Accomazzi (alberto@cfa.harvard.edu).

