.TH pnmtosir 1 "20 March 1991"
.SH NAME
pnmtosir - convert a portable anymap into a Solitaire format
.SH SYNOPSIS
.B pnmtosir
.RI [ pnmfile ]
.SH DESCRIPTION
Reads a portable anymap as input.
Produces a Solitaire Image Recorder format.
.PP
pnmtosir produces an MGI TYPE 17 file for
.I pbm
and
.I pgm
files.
For
.IR ppm ,
it writes a MGI TYPE 11 file.
.SH "SEE ALSO"
sirtopnm(1), pnm(5)
.SH BUGS

.SH AUTHOR
Copyright (C) 1991 by Marvin Landis.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.

