.TH ppmmix 1 "16 November 1993"
.IX ppmmix
.SH NAME
ppmmix - blend together two portable pixmaps
.SH SYNOPSIS
ppmmix 
.I fadefactor 
.I ppmfile1 ppmfile2
.SH DESCRIPTION
Reads two portable pixmaps as input. Mixes them together using the
specified fade factor. The fade factor may be in the range from 0.0
(only ppmfile1's image data) to 1.0 (only ppmfile2's image data).
Anything in between gains a smooth blend between the two images.
.PP
The two pixmaps must have the same size.
.PP
.B pnmcomp
is a more general alternative.  It allows you to mix images of different
size and to have the fade factor vary throughout the image (through the
use of an alpha mask).

.SH SEE ALSO
.BR pnmcomp (5),
.BR ppm (5)
.SH AUTHOR
Copyright (C) 1993 by Frank Neumann
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
