.TH sbigtopgm 1 "23 January 98"
.IX sbigtopgm
.SH NAME
sbigtopgm \- convert an SBIG CCDOPS file into a portable graymap
.SH SYNOPSIS
.B sbigtopgm
.RI [ sbigfile ]
.SH DESCRIPTION
Reads an an image file in the native format used by the Santa Barbara
Instrument Group (SBIG) astronomical CCD cameras, and
produces a portable graymap as output.  Additional information
on SBIG cameras and documentation of the file format is available
at the Web site:
.ce 1
.B http://www.sbig.com/
.SH "SEE ALSO"
.BR pgm (5)
.SH AUTHOR
John Walker 
.RB ( http://www.fourmilab.ch/ ),
January 1998.
This program is in the public domain.
