.TH BINKDLOGSTAT "8" "July 2005"
.SH NAME
Binkdlogstat \- binkd log analyser and statistic generator
.SH SYNOPSYS
\fBbinkdlogstat < \fP<\fIbinkd-log-file\fP>

.SH DESCRIPTION
\fBbinkdlogstat\fP is a program which generates reports of the activity
of the binkd daemon. It analyzes binkd log files and prints to stdout a
formatted report with the following information for each node:
.P
- number of successful incoming sessions
.P
- number of failed incoming sessions
.P
- number of successful outgoing sessions
.P
- number of failed outgoing sessions
.P
- outgoing traffic in bytes
.P
- incoming traffic in bytes
.P
- number of sent files
.P 
- number of received files
.P 
- average CPS with node
.P

It also provides total information for these categories for the log
file.
.P

\fBbinkdlogstat\fR uses stdin as a source and stdout as a result
file, so it can be used as a filter.

.SH SEE ALSO
binkd(8)
.SH AUTHOR
Binkdlogstat was written by Pavel Gulchouck <gul@lucky.net>  2:463/68
.P
This manual page was written by Kaliuta Yauheni <y.kaliuta@gmail.com>

This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
