.\" Process this file with
.\" groff -man -Tascii sgmlcheck.1
.\"
.TH SGMLCHECK 1 "16 May 2000"
.SH NAME
sgmlcheck \- check the syntax of an LinuxDoc DTD sgml source file 
.SH SYNOPSIS
.B sgmlcheck
.IR file [.sgml]
.SH DESCRIPTION
.B sgmlcheck
is an old and obsoleted form of the SGML source checker command
of LinuxDoc-Tools.  It is recommended to switch the new form
.B linuxdoc -B check
now.
It runs an SGML parse on the specified document source.  Any errors
are reported to standard output.  No formatted version of the source
is produced.
.LP
Note that 
.B sgmlcheck
preprocesses the LinuxDoc DTD SGML source, doing the conditionalization
described by any <#if></#if> and <#unless></#unless> tags.
Document sources containing these tags will confuse a standalone SGML parser.
.SH OPTIONS
None.  The generic options described in
.BR linuxdoc (1)
are accepted, but have no effect (except for \-D).
.SH FILES
Many files and executables in /usr/share/linuxdoc-tools and /usr/bin are used. 
.SH BUGS
None known.
.SH AUTHOR
Originally written by Cees de Groot <cg@cdegroot.com> as sgmlcheck
for SGML-Tools v1.
Currently maintained by Taketoshi Sano <sano@debian.org> for Linuxdoc-Tools.
.SH "SEE ALSO"
.BR linuxdoc (1),
.BR sgml2html (1),
.BR sgml2info (1),
.BR sgml2latex (1), 
.BR sgml2rtf (1), 
.BR sgml2txt (1).
