.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 21 Aug 1994 by Michael Chastain (mec@shell.portal.com):
.\"   Removed note about old libc (pre-4.5.26) translating to 'sync'.
.\" Modified 15 Apr 1995 by Michael Chastain (mec@shell.portal.com):
.\"   Added 'see also' section.
.\" Translated into german bz Martin Schulze (joey@infodrom.north.de).
.\" Modified Mon Jun 10 12:14:11 1996 by Martin Schulze (joey@linux.de)
.\"
.TH FSYNC 2 "29. März 1996" "Linux 1.2.4" "Systemaufrufe"
.SH BEZEICHNUNG
fsync \- synchronisiert den Dateiinhalt mit der Platte
.SH SYNTAX
.B #include <unistd.h>
.sp
.BI "int fsync(int " fd );
.SH BESCHREIBUNG
.B fsync
kopiert alle Kernteile einer Datei auf die Platte (Festplatt oder
Diskette).
.SH "RÜCKGABEWERT"
Bei Erfolg wird Null zurückgegeben, bei Fehlern \-1 und
.I errno
wird entsprechend gesetzt.
.SH FEHLER
.TP 0.8i
.B EBADF
.I fd
ist kein gültiger offener Dateideskriptor.
.TP
.BR EROFS ", " EINVAL
.I fd
ist mit einer Spezialdatei verbunden, die keine Synchronisation
unterstützt.
.TP
.B EIO
Während der Synchronisation ist ein Fehler aufgetreten.
.SH "SIEHE AUCH"
.BR bdflush "(2), " fsync "(2), " update "(8), " sync "(8)."

