.\" Copyright (c) 1983, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)setregid.2	6.4 (Berkeley) 3/10/91
.\"
.\" Modified Sat Jul 24 09:08:49 1993 by Rik Faith (faith@cs.unc.edu)
.\" Portions extracted from linux/kernel/sys.c:
.\"             Copyright (C) 1991, 1992  Linus Torvalds
.\"             May be distributed under the GNU General Public License
.\" Changes: Fri Jul 29 10:56:01 BST 1994 by Wilf. (G.Wilford@ee.surrey.ac.uk)
.\"          Tue Aug  2 14:56:48 BST 1994 by Wilf due to changes in kernel.
.\" Translated to German Sun Oct 20 1996 by Patrick Rother (krd@gulu.net)
.\"
.TH SETREGID 2 "20. Oktober 1996" "Linux 1.1.38" "Systemaufrufe"
.SH NAME
setregid, setegid \- setze reale und/oder effektive Gruppenkennung
.SH ÜBERSICHT
.B #include <unistd.h>
.sp
.BI "int setregid(gid_t " rgid ", gid_t " egid );
.br
.BI "int setegid(gid_t " egid );
.SH BESCHREIBUNG
.B setregid
setzt die reale und effektive Gruppenkennung (Group ID) des aktuellen Prozesses.
Unprivilegierte Benutzer dürfen die reale Gruppenkennung auf die
effektive Gruppenkennung ändern und umgekehrt.

Seit 1.1.38 ist es auch möglich, die effektive Gruppenkennung aus der
gesicherten Gruppenkennung zu setzen.

Nur der Superuser darf andere Änderungen machen.

Angeben des Wertes \-1 für entweder die reale oder effektive Gruppenkennung
weist das System an, diese Kennung unverändert zu lassen.

Im Moment (libc-4.x.x) is
.BI setegid( egid )       
funktionell äquivalent zu
.BI setregid(  -1  , " egid" ) \fR.

Wenn die reale Gruppenkennung geändert wird, oder wenn die effektive 
Gruppenkennung auf einen Wert gesetzt wird, der nicht gleich der vorherigen
realen Gruppenkennung ist, so wird die gesicherte Gruppenkennung 
auf die neue effektive Gruppenkennung gesetzt.
.SH "RÜCKGABEWERT"
Bei Erfolg wird Null zurückgegeben.  Im Fehlerfall wird \-1 zurückgegeben und
.I errno
entsprechend gesetzt.
.SH FEHLER
.TP
.TP
.B EPERM
Der aktuelle Prozeß gehört nicht dem Superuser und eine andere Änderung als (i) das
Vertauschen der effektiven mit der realen Gruppenkennung oder (ii) Setzen
einer dieser auf den Wert den anderen oder (iii) Setzen der effektiven 
Gruppenkennung auf den Wert der gesicherten Gruppenkennung wurde angestrebt.
.SH GESCHICHTE
Die Funktion
.B setregid
erschien in BSD 4.2.
.SH "KONFORM ZU"
BSD 4.3
.SH "SIEHE AUCH"
.BR getgid (2),
.BR setgid (2).
