.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 1992 Drew Eckhardt;
.\"                               1993 Michael Haardt, Ian Jackson.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified Sat Jul 24 13:35:59 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Nov 28 17:19:01 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sat Jan 13 12:58:08 MET 1996 by Michael Haardt (michael@cantor.informatik.rwth-aachen.de)
.\"
.TH WRITE 2 "13. Januar 1996" Linux "Systemaufrufe"
.SH BEZEICHNUNG
write \- in eine Datei schreiben
.SH ÜBERSICHT
.B #include <unistd.h>
.sp
.BI "ssize_t write(int " fd ", const char *" buf ", size_t " count );
.SH BESCHREIBUNG
.B write
versucht
.I count
Bytes vom Puffer, auf den
.I buf
zeigt, in die zu
.I fd
gehörende Datei zu schreiben.  POSIX fordert, dass ein nachweisbar nach
der Rückkehr von
.B write()
liegendes
.B read()
die neuen Daten liefern muss.  Es sollte jedoch beachtet
werden, dass nicht alle Dateisysteme POSIX konform sind.
.SH "RÜCKGABEWERT"
Bei Erfolg wird die Anzahl von geschriebenen Bytes zurückgegeben (null heißt,
dass nichts geschrieben wurde).  Im Fehlerfalle wird \-1 zurückgegeben und
.I errno
wird entsprechend gesetzt.  Wenn
.I count
0 ist, dann wird 0 zurückgegeben und sonst geschieht nichts.
Bei anderen Dateien sind die Ergebnisse nicht portabel.
.SH FEHLER
.TP
.B EBADF
.I fd
ist keine gültige Dateikennzahl oder die Datei wurde nicht zum Schreiben
geöffnet.
.TP
.B EINVAL
.I fd
gehört zu einer Datei, welche nicht zum Schreiben geeignet ist.
.TP
.B EFAULT
.I buf
ist außerhalb deines ansprechbaren Adressraumes.
.TP
.B EPIPE
.I fd
ist mit einer pipe oder einem socket verbunden, deren lesendes Ende geschlossen ist.
In diesem Falle empfängt der schreibende Prozess ein
.B SIGPIPE
Signal.  Wird dieses abgefangen, blockiert oder ignoriert, wird
.B EPIPE
zurückgegeben.
.TP
.B EAGAIN
Mit 
.B O_NONBLOCK
wurde nicht-blockierende Ein-/Ausgabe gewählt, aber in der mit 
.I fd
verbundenen pipe oder dem Socket war kein Platz mehr, um die Daten
sofort zu schreiben.
.TP
.B EINTR
Der Aufruf wurde durch ein Signal unterbrochen, bevor Daten geschrieben 
werden konnten.  
.TP
.B ENOSPC
Das Gerät, welches die Datei enthält, welche durch
.I fd
referenziert ist, hat keinen Platz für die Daten.
.PP
Abhängig vom Objekt, welches mit
.I fd
verbunden ist, können auch andere Fehler auftreten.  
.SH "KONFORM ZU"
SVID, AT&T, POSIX, X/OPEN, BSD 4.3
.SH "SIEHE AUCH"
.BR open (2),
.BR read (2),
.BR fcntl (2),
.BR close (2),
.BR lseek (2),
.BR select (2),
.BR ioctl (2),
.BR fwrite (3).

