.TH bioradtopgm 1 "28 June 1993"
.SH NAME
bioradtopgm - convert a Biorad confocal file into a portable graymap
.SH SYNOPSIS
.B bioradtopgm
.RB [ -image# ]
.RI [ imagedata ]
.SH DESCRIPTION
Reads a Biorad confocal file as input.
Produces a portable graymap as output.
If the resulting image is upside down, run it through
.B "pnmflip -tb" .
.SH OPTIONS
.TP
.B -image#
A Biorad image file may contain more than one image.  With this flag,
you can specify which image to extract (only one at a time).  The first
image in the file has number zero.  If no
image number is supplied, only information about the image size and
the number of images in the input is printed out.  No output is produced.
.SH "SEE ALSO"
pgm(5), pnmflip(1)
.SH AUTHORS
Copyright (C) 1993 by Oliver Trepte
.br
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
