.TH pbmtoepsi 1 "1992"
.IX pbmtoepsi
.SH NAME
pbmtoepsi - convert a portable bitmap into an encapsulated PostScript
style preview bitmap
.SH SYNOPSIS
.B pbmtoepsi
.RB [ -bbonly ]
.RI [ pbmfile ]
.SH DESCRIPTION
Reads a portable bitmap as input.
Produce an encapsulated Postscript style bitmap as output. The output
is not a stand alone postscript file, it is only a preview bitmap,
which can be included in an encapsulated PostScript file.
Note that there is no epsitopbm tool - this transformation is one way.

This utility is a part of the pstoepsi tool by Doug Crabill
(dgc@cs.purdue.edu).
.SH OPTIONS
.TP
.B -bbonly
Only create a boundary box, don't fill it with the image.
.SH "SEE ALSO"
.BR pbm (5), 
.BR pnmtops (1), 
.BR pstopnm (1),
.BR psidtopgm (1),
.BR pbmtolps (1),
.BR ps (1)
.SH AUTHOR
Copyright (C) 1988 Jef Poskanzer, modified by Doug Crabill 1992
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
