# Create header, using MET/MEST
timestamp=$(TZ='Europe/Amsterdam' date "+%d.%m.%Y, %H:%M")

# Name of Columns
cname_name="Naam"
cname_percent="Percentage"
cname_missing_strings="Vertalingen tot 80%"
cname_statistics="Statistiek"
cname_packet="Pakket"
cname_manpages="Man Pagina's"

cname_onepageuntranslated="1 bestand is niet volledig vertaald."
cname_severalpagesuntranslated="bestanden zijn niet volledig vertaald."

cname_intotal1="Totaal zijn "
cname_intotal2=" bestanden niet volledig vertaald."

cname_webtitle="Nederlandse vertaling van man pages"
cname_overviewlink="Overzicht"
# For overview of (untranslated) pages
cname_nottranslated="List of files which are not translated into Dutch"
cname_explanation="The following pages are translated into some other language(s), but not into Dutch"
