# Create header, using MET/MEST
timestamp=$(TZ='Europe/Helsinki' date "+%d. %m %Y, %H:%M")

# Name of Columns
cname_name="Name"
cname_percent="Percent"
cname_missing_strings="Translations until 80%"
cname_statistics="Statistics"
cname_packet="Package"
cname_manpages="Man pages"

cname_onepageuntranslated="1 file is not completely translated."
cname_severalpagesuntranslated="files are not completely translated."

cname_intotal1="Totally "
cname_intotal2=" files are not translated."
