# Create header, using MET/MEST
timestamp=$(TZ='America/Sao_Paulo' date "+%d %m %Y, %H:%M")

# Name of Columns
cname_name="Nome"
cname_percent="Porcentagem"
cname_missing_strings="Traduções até 80%"
cname_statistics="Estatísticas"
cname_packet="Pacote"
cname_manpages="Páginas man"

cname_onepageuntranslated="1 arquivo não está completamente traduzido."
cname_severalpagesuntranslated="arquivos não estão completamente traduzidos."

cname_intotal1="No total, "
cname_intotal2=" arquivos não estão traduzidos."

cname_webtitle="Tradução para português brasileiro de páginas man"
cname_overviewlink="Visão geral de português brasileiro"
# For overview of (untranslated) pages
cname_nottranslated="Lista de arquivos que não estão traduzidos para português brasileiro"
cname_explanation="The following pages are translated into some other language(s), but not into Brazilian Portuguese"
