# Create header, using MET/MEST
timestamp=$(TZ='Europe/Warsaw' date "+%d %m %Y, %H:%M")

# Name of Columns
cname_name="Nazwa"
cname_percent="Postęp"
cname_missing_strings="Pozostało do osiągnięcia 80%"
cname_statistics="Statystyki"
cname_packet="Pakiet"
cname_manpages="Strony podręcznika"

cname_onepageuntranslated="1 plik jest nie w pełni przetłumaczony."
cname_severalpagesuntranslated="pliki/plików nie w pełni przetłumaczonych."

cname_intotal1="W sumie "
cname_intotal2=" plików jest nieprzetłumaczonych."

cname_webtitle="Polskie tłumaczenie stron podręcznika systemowego"
cname_overviewlink="Przegląd dla języka polskiego"
# For overview of (untranslated) pages
cname_nottranslated="Lista plików nieprzetłumaczonych na język polski"
cname_explanation="Następujące podręczniki nie są przetłumaczone na polski, ale ich tłumaczenie istnieje w przynajmniej jednym innym języku"
