# Create header, using MET/MEST
timestamp=$(TZ='Europe/Berlin' date "+%d.%m.%Y, %H:%M Uhr")

# Name of Columns
cname_name="Name"
cname_percent="Prozent"
cname_missing_strings="Übersetzungen bis 80%"
cname_statistics="Statistik"
cname_packet="Paket"
cname_manpages="Handbuchseiten"

cname_onepageuntranslated="1 Datei ist nicht vollständig übersetzt."
cname_severalpagesuntranslated="Dateien sind nicht vollständig übersetzt."

cname_intotal1="Insgesamt sind "
cname_intotal2=" Dateien nicht übersetzt."

cname_webtitle="Deutsche Übersetzung der Handbuchseiten"
cname_overviewlink="Deutsche Übersicht"
# For overview of (untranslated) pages
cname_nottranslated="Liste der Dateien, die nicht ins Deutsche übersetzt sind"
cname_explanation="Die folgenden Handbuchseiten sind in andere Sprachen übersetzt, aber nicht auf Deutsch"
