# Create header, using MET/MEST
timestamp=$(TZ='Asia/Jakarta' date "+%d %m %Y, %H:%M")

# Name of Columns
cname_name="Name"
cname_percent="Percent"
cname_missing_strings="Translations until 80%"
cname_statistics="Statistics"
cname_packet="Package"
cname_manpages="Man pages"

cname_onepageuntranslated="1 file is not completely translated."
cname_severalpagesuntranslated="files are not completely translated."

cname_intotal1="Totally "
cname_intotal2=" files are not translated."

cname_webtitle="Indonesian translation of manual pages"
cname_overviewlink="Indonesian overview"
# For overview of (untranslated) pages
cname_nottranslated="List of files which are not translated into Indonesian"
cname_explanation="The following pages are translated into some other language(s), but not into Indonesian"
