# Create header, using MET/MEST
timestamp=$(TZ='Europe/Paris' date "+%d.%m.%Y, %H:%M")

# Name of Columns
cname_name="Nom"
cname_percent="Pourcentage"
cname_missing_strings="Traductions jusqu'à 80%"
cname_statistics="Statistiques"
cname_packet="Paquet"
cname_manpages="Pages de manuel"
cname_date="Heure"

cname_onepageuntranslated="1 fichier n'est pas complètement traduit."
cname_severalpagesuntranslated="fichiers ne sont pas complètement traduits."

cname_intotal1="Au total, "
cname_intotal2=" ne sont pas complètement traduits."

cname_webtitle="Traduction française des pages de manuel"
cname_overviewlink="Aperçu"
# For overview of (untranslated) pages
cname_nottranslated="Liste des fichiers non traduits"
cname_explanation="The following pages are translated into some other language(s), but not into French"
