# Create header, using MET/MEST
timestamp=$(TZ='Europe/Madrid' date "+%d %m %Y, %H:%M")

# Name of Columns
cname_name="Nombre"
cname_percent="Porcentaje"
cname_missing_strings="Traducciones pendientes para completar el 80%."
cname_statistics="Estadísticas"
cname_packet="Paquete"
cname_manpages="Páginas de manual"
cname_date="Fecha"

cname_onepageuntranslated="1 archivo no está totalemente traducido."
cname_severalpagesuntranslated="archivos no están totalemente traducidos."

cname_intotal1="Totalmente"
cname_intotal2="archivos sin traducir."

cname_webtitle="Traducción de páginas de manual al español"
cname_overviewlink="Estado de las traducciones al español"
# For overview of (untranslated) pages
cname_nottranslated="Lista de páginas sin traducir al castellano"
cname_explanation="Estas páginas de manual no están traducidas al español pero sí en algún otro idioma."
