.\" -*- nroff -*- 
.\"
.\" This man-page is Copyright (C) 1997 John S. Kallal 
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" correction, aeb, 970825
.\"
.\" German translation by Martin Schmitt (martin@schmitt.li) 01/2001
.\"
.TH FULL 4 "23. Januar 2001" "Linux" "Gerätedateien"
.SH BEZEICHNUNG
full \- Gerätedatei, Gerät, das immer "voll" ist
.SH BESCHREIBUNG
Bei
.BR /dev/full
handelt es sich um eine Datei, die immer voll ist.
.LP 
Der Versuch, auf
.BR /dev/full
schreibend zuzugreifen, schlägt mit dem Fehler ENOSPC fehl.

Der Versuch, auf 
.BR /dev/full
lesend zuzugreifen, liefert die Zeichenfolge \\0.

Seek-Zugriffe auf 
.BR /dev/full
haben immer Erfolg.
.SH KONFIGURATION
Wenn
.BR /dev/full
auf dem System nicht bereits vorhanden ist, kann es mit den folgenden 
Befehlen erzeugt werden:
.nf

        mknod -m 666 /dev/full c 1 7
        chown root:root /dev/full

.fi
.SH DATEIEN
.I /dev/full
.SH "SIEHE AUCH"
.BR mknod (1),
.BR null (4),
.BR zero (4).
