.\" Copyright (c) 1999 Herbert Xu (herbert@gondor.apana.org.au),
.\" Copyright (c) 1994 Peter Tobias (tobias@server.et-inf.fho-emden.de),
.\" This file may be distributed under the GNU General Public License.
.TH FTPCHROOT 5 "1999 April 1st" "Linux" "Linux Programmer's Manual"
.SH NAME
ftpchroot \- file which lists users who need to be chrooted
.SH DESCRIPTION
\fB/etc/ftpchroot\fP is used by
.BR ftpd(8);
the file contains a list of users who need to be chrooted before the ftp
service is offered.  Blank lines and lines beginning with "#" are ignored.
Remember that the whole line will be used for the username, so please
don't use the "#" character after a name to comment this entry.
.SH EXAMPLES
.B /etc/ftpchroot
may contain the following entries:
.sp
#
.br
# /etc/ftpusers
.br
#
.br
not_so_anonymous
.SH FILES
/etc/ftpchroot
.SH "SEE ALSO"
.BR ftp "(1), " ftpd "(8)"
