'\" t
.\"     Title: pacdiff
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2022-05-21
.\"    Manual: Pacman-contrib Manual
.\"    Source: Pacman-contrib 1.5.2
.\"  Language: English
.\"
.TH "PACDIFF" "8" "2022\-05\-21" "Pacman\-contrib 1\&.5\&.2" "Pacman\-contrib Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pacdiff \- pacorig, pacnew and pacsave maintenance utility
.SH "SYNOPSIS"
.sp
\fIpacdiff\fR [options]
.SH "DESCRIPTION"
.sp
pacdiff is a script which looks for pacorig, pacnew and pacsave files from the backup entries found in the local Pacman db\&. For every found file the option is given to view, merge, skip, diff, remove or overwrite the found pacorig, pacnew or pacsave file\&.
.SH "ENVIRONMENT"
.PP
\fBDIFFPROG\fR
.RS 4
Override the default
\fIvim \-d\fR
merge program\&.
.RE
.PP
\fBDIFFSEARCHPATH\fR
.RS 4
Override the default search path
\fI/etc\fR, only when using find\&.
.RE
.PP
\fBMERGEPROG\fR
.RS 4
Override the default
\fIdiff3 \-m\fR
3\-way merge program\&. One possible alternative is
\fIgit merge\-file \-p\fR\&.
.RE
.SH "OPTIONS"
.PP
\fB\-l, \-\-locate\fR
.RS 4
Scan using locate\&.
.RE
.PP
\fB\-f, \-\-find\fR
.RS 4
Scan using find\&.
.RE
.PP
\fB\-p, \-\-pacmandb\fR
.RS 4
Scan active config files from Pacman database\&. (default)
.RE
.PP
\fB\-o, \-\-output\fR
.RS 4
Print files instead of merging them\&.
.RE
.PP
\fB\-\-nocolor\fR
.RS 4
Remove colors from output\&.
.RE
.PP
\fB\-c, \-\-cachedir <dir>\fR
.RS 4
Scan
\fIdir\fR
instead as the pacman cache for 3\-way merge base candidates\&.
.RE
.PP
\fB\-s, \-\-sudo\fR
.RS 4
Use sudo to merge/remove files\&.
.RE
.SH "SEE ALSO"
.sp
\fBpacman\fR(8), \fBpacman.conf\fR(5)
.SH "BUGS"
.sp
Bugs? You must be kidding; there are no bugs in this software\&. But if we happen to be wrong, file an issue with as much detail as possible at https://gitlab\&.archlinux\&.org/pacman/pacman\-contrib/\-/issues/new\&.
.SH "AUTHORS"
.sp
Current maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Johannes Löthberg <johannes@kyriasis\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Daniel M\&. Capella <polyzen@archlinux\&.org>
.RE
.sp
For additional contributors, use git shortlog \-s on the pacman\-contrib\&.git repository\&.
