.\" This file is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
.\" the GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this file; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston,
.\" MA 02111-1307 USA
.\"
.\" HISTORY:
.\" 2006-05-16, created by Rodrigo Rubira Branco <rrbranco@br.ibm.com>
.TH cons.saver 8 "May 16, 2006" Linux "User Manuals"
.SH NAME
cons.saver \- general-purpose Linux console screen save and restore server
.SH SYNOPSIS
.nf
.fam C
cons.saver \fITTY\fP
.fam T
.fi
.SH DESCRIPTION
.TP
Invoke this helper program with the Ctrl-o key combination to save and restore the user session on the screen.
.SH OPTIONS
cons.saver takes only one argument, the \fITTY\fP \fINAME\fP from which the system  will save and restore.
.SH SECURITY
Cons.saver does not need to be invoked by root.  It only needs read and write access to /dev/vcsa*, which is a priviledged operation.  You should create an unprivileged user, make cons.saver setuid to that user, and assure that all the vcsa* are owned by that user too.
.SH AUTHOR
Manpage written by Rodrigo Rubira Branco <rrbranco@br.ibm.com>
.SH SEE ALSO
\fBmc\fP(1), \fBmcserv\fP(8)
