.\" Copyright (C) 2000 Stein Gjoen
.\" 
.\" Permission is granted to make and distribute verbatim copies of
.\" this manual provided the copyright notice and this permission notice
.\" are preserved on all copies.
.\" 
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that this permission notice may be included in
.\" translations approved by the Free Software Foundation instead of in
.\" the original English.
.\"
.\" Translated into German by Walter Holzer <holzerwoerth@web.de>
.\"
.TH "TLDP-Einführung" "TLDP" "15. November 2001" "TLDP"
.SH BEZEICHNUNG
LDP \- Einführung ins Linux-Dokumentations-Projekt, mit Hilfe, Anleitungen und Dokumenten
.SH ÜBERSICHT
Das Linux-Dokumentations-Projekt (TLDP) bietet eine Vielzahl von freien
Dokumentationsquellen einschließlich Handbüchern, FAQs und Manpages
für die GNU/Linux-Community.
.SH AUTOREN
Die unterschiedlichen Dokumente im TLDP-Verzeichnis werden von
verschiedenen Autoren betreut, die am Anfang jedes HOWTOs aufgeführt
sind.  Wenn Sie irgendwelche Fragen oder Beiträge zu einem Dokument
haben, ermutigen wir Sie, sich direkt an die Autoren zu wenden.
.SH "WEBSEITEN"
Das TLDP hat seine eigene zugeordnete Website wie viele der
verschiedenenen Übersetzungs-Projekte, die von der TLDP-Hauptseite
unter
.RS
\fBhttp://www\&.tdlp\&.org/\fP
.RE
verlinkt sind, die sie vielleicht in Ihre Bookmarks aufnehmen möchten.
.SH "MANPAGES"
Eine Webseite mit Status-Informationen für Manpages und Übersetzungen
steht bereit unter:
.RS
\fBhttp://www\&.win\&.tue\&.nl/~aeb/linux/man/\fP
.RE
.SH "MAILINGLISTEN"
TLDP hat eine Anzahl von Mailinglisten, die hauptsächlich von den Autoren
benutzt werden:
.PP
.PD 0
.TP
.PD
\fB<announce@en\&.tldp\&.org>\fP
Ankündigungen des TLDP-Projektes
.TP
\fB<discuss@en\&.tdlp\&.org>\fP
Generelle Diskussionen über das TLDP-Projekt
.PP
Um sich auf diesen Listen anzumelden, senden Sie eine leere Mail an
\fB<announce\-subscribe@en\&.tdlp\&.org>\fP oder 
\fB<discuss\-subscribe@en\&.tdlp\&.org>\fP respektive.
Diese Mailinglisten werden zusätzlich auf \fBhttp://www\&.tdlp\&.org/\fP archiviert.
.SH DATEIEN
Die meisten Distributionen enthalten die HOWTOs und mini-HOWTOs in
folgenden Verzeichnissen:
.PD 0
.TP
\fB/usr/doc/\fP                   (alter Ort für Dokumentation)
.TP
\fB/usr/share/doc/\fP             (neuer Ort für Dokumentation)
.TP
\fB/usr/share/doc/HOWTO/\fP       (HOWTO-Dateien)
.TP
\fB/usr/share/doc/HOWTO/mini/\fP  (mini-HOWTO-Dateien)
.PD
.SH "SIEHE AUCH"
.BR man (1),
.BR xman (1x),
.BR info (1).
.PP
\fBinfo\fP-Seiten werden mit
.BR emacs (1)
oder
.BR pinfo (1)
oder
.BR info (1)
gelesen.
