'\" t
.\" (c) 1993 by Thomas König (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sat Jul 24 17:35:15 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Feb 19 22:02:32 1995 by Rik Faith (faith@cs.unc.edu)
.\" Translated to german Thu Jan 04 00:20:02 1996 by
.\"   Norbert Kümin (norbert.kuemin@lugs.ch)
.\"   Modified Mon Aug 03 1998 by Andreas Braukmann <andy@abra.de>
.\"
.\" 
.TH SUFFIXES 7  "25. April 1993" "Linux" "Verschiedenes"
.SH BEZEICHNUNG
suffixes \- Liste der Dateiendungen
.SH BESCHREIBUNG
Es ist üblich den Inhalt von Dateien mit den Endungen der Dateinamen zu
kennzeichnen.  Die Endungen bestehen aus einem Punkt gefolgt von einem oder
mehreren Buchstaben.  Viele Standart-Werkzeuge, wie Kompiler erkennen den Typ
mit dem gerade gearbeitet wird und das make(1) Werkzeug enthält viele Regeln um
Dateien gemäß ihren Endungen zu bearbeiten.
.PP
Es folgt eine Liste der Endungen welche auf einem Linux-System gefunden
werden können.
.PP
.TS 
l | l
_ | _
lI |  l .
Endung	Dateityp
 ,v	Dateien für RCS (Revision Control System)
 \-	Sicherungsdateien
 .C	C++ Sourcecode
 .F	FORTRAN Sourcecode mit
.BR cpp "(1) Direktiven"
 .S	Assembler Sourcecode mit
.BR cpp "(1) Direktiven"
 .Z	Komprimierte Datei mit
.BR compress (1)
 .[0-9]+pk	TeX-Font Dateien
 .[1-9]	Hilfeseiten (MAN-Page) für die entsprechenden Sektion
 .[1-9][a-z]	Hilfeseiten (MAN-Page) für Sektion und Subsektion
 .a	statische Objektcode-Bibliothek
 .afm	PostScript Zeichensatz-Metrik
 .arc	ARC Archivedatei
 .awk	
.BR AWK "(1) Programm"
 .bak	Sicherungsdatei
 .bm	Bitmap Sourcecode
 .c	C Sourcecode
 .cat	Nachrichten Katalogdatei
 .cf	Konfigurationsdatei
 .conf	Konfigurationsdatei
 .config	Konfigurationsdatei
 .cweb	Donald Knuth's WEB für C
 .dat	Datenfile
 .def	Modula-2 Sourcecode für Definitionsmodule
 .def	andere Definitionsdateien
 .diff	ASCII Datei Differenzen
 .doc	Dokumentationsdatei
 .dvi	TeX geräteunabhängige Ausgabe
 .el	EMACS Lisp Sourcecode
 .elc	Kompiliertes EMACS Lisp
 .eps	Encapsulated PostScript
 .f	FORTRAN Sourcecode
 .fas	vorkompilierter allgemeiner Lispcode
 .fi	FORTRAN Include-Dateien
 .gif	Graphics Interchange Format
 .gsf	Ghostscript Zeichensätze
 .gz	Komprimierte Dateien unter Verwendung von
.BR gzip (1)
 .h	C oder C++ Header-Dateien
 .hlp	Hilfe-Dateien
 .i	C Sourcecode nach Vorbehandlung
 .icon	Bitmap Sourcecode
 .image	Bitmap Sourcecode
 .in	Eingabe-Date für einige Werkzeuge
 .info	Dateien für den EMACS Info Auswahlliste
 .jpg	JPEG komprimiertes Grafikformat
 .jpeg	JPEG komprimiertes Grafikformat
 .l	
.BR lex "(1) oder"
.BR flex "(1) Dateien"
 .lib	Allgemeine Lisp Bibliothek
 .ln	Datei für
.BR lint (1)
 .lsp	Allgemeiner Lisp Sourcecode
 .man	Hilfeseiten (MAN pages)
 .mf	Metafont (Zeichensatz-Generator für TeX) Sourcecode
 .mm	Sourcecode für
.BR groff "(1) im MM - Format"
 .mod	Modula-2 Sourcecode für Implementationsmodulen
 .o	Objektdateien
 .old	alte oder Sicherheitsdateien
 .out	Ausgabedatei, oftmals ausfürbare Programme (a.out)
 .p	Pascal Sourcecode
 .patch	Datei Differenzen von
.BR patch (1)
 .pcf	X11 Zeichensatzdateien (???)
 .pfa	PostScript Zeichensatz Definitionsdatei
 .pid	Dateien für Dämon-PIDs (z.B. crond.pid)
 .pl	Perl Script
 .pr	Bitmap Sourcecode
 .ps	PostScript Datei
 .r	RATFOR Sourcecode
 .rules	Regeln für irgendwas
 .s	Assembler Sourcecode
 .sa	Hat irgendwas mit "shared libraries" zu tun (???)
 .sc	
.BR sc "(1) Tabellenkalkulation Kommandos"
 .sh	
.BR sh "(1) Script"
 .shar	Archiv erstellt mit dem
.BR shar "(1) Werkzeug"
 .so	DLL dynamische Bibliothek
 .sty	LaTeX Stildateien
 .sym	Modula-2 kompilierte Definitionsmodule
 .tar	Archiv erstellt mit dem
.BR tar "(1) Werkzeug"
 .tar.Z	tar Archiv komprimiert mit
.BR compress (1)
 .taz	tar Archiv komprimiert mit
.BR compress (1)
 .tar.gz	tar Archiv komprimiert mit
.BR gzip (1)
 .tgz	tar Archiv komprimiert mit
.BR gzip (1)
 .tpz	tar Archiv komprimiert mit
.BR gzip (1)
 .tex	TeX oder LaTeX Sourcecode
 .texi	Equivalent zu
.I .texinfo
 .texinfo	TeXinfo Dokumentation Sourcecode
 .tfm	TeX Zeichensatz Metrik
 .tmpl	Template Dateien
 .txt	Text Datei
 .uue	Binäre Datei codiert mit
.BR uuencode (1)
 .web	Donald Knuth's WEB
 .y	
.BR yacc "(1) oder
.BR bison "(1) (Parser Generator) Dateien"
 .z	Datei komprimiert mit
.BR pack "(1) (der ein altes"
.BR gzip "(1))"
 .zoo	ZOO Archiv
 ~	EMACS oder patch Sicherungsdatei
 rc	Startdatei, z.B. .newsrc
.TE
.SH "KONFORM ZU"
Generellen UNIX Konventionen
.SH BUGS
Diese Liste ist nicht komplett.
.SH "SIEHE AUCH"
.BR file (1),
.BR make (1).

