.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Mon Mar 29 22:39:24 1993, David Metcalfe
.\" Modified Sat Jul 24 21:39:22 1993, Rik Faith (faith@cs.unc.edu)
.\" Translated into german by Stefan Janke (gonzo@burg.studfb.unibw-muenchen.de)
.\"
.TH ATOF 3 "12. September 1996" "GNU" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
atof \- wandelt einen String in einen Double-Zahl um
.SH "‹BERSICHT"
.nf
.B #include <stdlib.h>
.sp
.BI "double atof(const char *" nptr );
.fi
.SH BESCHREIBUNG
Die  
.B atof()
Funktion wandelt den Beginn eines Strings, der durch
.IR nptr
angegeben wird, in eine Double-Zahl um. Es wird also die
gleiche Aufgabe, wie durch
.sp
.RS
.B strtod(nptr, (char **)NULL);
.RE
.sp
erledigt, auﬂer daﬂ
.B atof()
keine Fehler entdeckt.
.SH "R‹CKGABEWERT"
Der umgewandelte Wert
.SH "KONFORM ZU"
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH "SIEHE AUCH"
.BR atoi (3),
.BR atol (3),
.BR strtod (3),
.BR strtol (3),
.BR strtoul (3).
