.\" Copyright 1995 Jim Van Zandt <jrv@vanzandt.mv.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" changed `square root' into `cube root' - aeb, 950919
.\"
.\" Translated into german by Markus Schmitt (fw@math.uni-sb.de)
.\"
.TH CBRT 3 "30. Mai 1996" "" "Bibliotheksfunktionen"
.\"
.SH BEZEICHNUNG
cbrt - die kubische Wurzelfunktion
.SH "ÜBERSICHT"
.nf
.B #include <math.h>
.sp
.BI "double cbrt ( double " x " );"
.fi
.SH BESCHREIBUNG
Die Funktion
.B cbrt()
berechnet die kubische Wurzel von 
.IR x .
Da jede reelle Zahl eine reelle, kubische Wurzel hat, ist jeder
Funktionsaufruf korrekt.
.SH "KONFORM ZU"
.B cbrt 
der GNU - Erweiterungen
.SH "SIEHE AUCH"
.BR sqrt (3),
.BR pow (3).




