.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Translated into German by Maik Messerschmidt (Maik.Messerschmidt@gmx.net)
.\"
.TH CIMAG 3 "6. April 2006" "" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
cimag, cimagf, cimagl \- den Imaginärteil einer komplexen Zahl bestimmen
.SH "ÜBERSICHT"
.B #include <complex.h>
.sp
.BI "double cimag(double complex " z ");" 
.br
.BI "float cimagf(float complex " z ");"
.br
.BI "long double cimagl(long double complex " z ");"
.sp
Mit der Option \-lm linken.
.SH BESCHREIBUNG
Die Funktion
.BR cimag ()
gibt den Imaginärteil einer komplexen Zahl z zurück.
.LP
Es ergibt sich z = creal(z) + I*cimag(z).
.SH ANMERKUNG
Der gcc unterstützt auch __imag__.  Dies ist eine GNU-Erweiterung.
.SH KONFORM ZU
C99
.SH SIEHE AUCH
.BR cabs (3),
.BR creal (3),
.BR complex (5).
