.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Translated into German by Maik Messerschmidt (Maik.Messerschmidt@gmx.net)
.\"
.TH CREAL 3 "6. April 2006" "" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
creal, crealf, creall \- den Realteil einer komplexen Zahl bestimmen
.SH "ÜBERSICHT"
.B #include <complex.h>
.sp
.BI "double creal(double complex " z );
.br
.BI "float crealf(float complex " z );
.br
.BI "long double creall(long double complex " z );
.sp
Mit der Option \-lm linken.
.SH BESCHREIBUNG
Die Funktion
.BR creal()
gibt den Realteil einer komplexen Zahl z zurück.
.LP
Es ergibt sich z = creal(z) + I*cimag(z).
.SH ANMERKUNG
Der gcc unterstützt auch __real__.  Dies ist eine GNU-Erweiterung.
.SH KONFORM ZU
C99
.SH SIEHE AUCH
.BR cabs (3),
.BR cimag (3),
.BR complex (5).
