.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Translated into German by Maik Messerschmidt (Maik.Messerschmidt@gmx.net)
.\"
.TH CSIN 3 "6. April 2006" "" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
csin, csinf, csinl \- die komplexe Sinusfunktion
.SH "ÜBERSICHT"
.B #include <complex.h>
.sp
.BI "double complex csin(double complex " z ");"
.br
.BI "float complex csinf(float complex " z );
.br
.BI "long double complex csinl(long double complex " z ");"
.sp
Mit der Option \-lm linken.
.SH BESCHREIBUNG
Der komplexe Sinus
csin(z)
ist definiert durch
(exp(i*z)-exp(-i*z))/(2*i).
.SH KONFORM ZU
C99
.SH SIEHE AUCH
.BR cabs (3),
.BR csin (3),
.BR ctan (3),
.BR complex (5).
