.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:48:17 1993 by Rik Faith (faith@cs.unc.edu)
.\" German translation Jens Püschel (jepu0000@stud.uni-sb.de)
.\" Modified Sun Jan  7 16:44:02 CET 2001 by Martin Schulze <joey@infodrom.north.de>
.\"
.TH DIFFTIME 3  "July 2, 1993" "GNU" "Bibliotheksfunktionen"
.SH Bezeichnung
difftime \- berechnet Zeitdifferenzen
.SH Übersicht
.nf
.B #include <time.h>
.sp
.BI "double difftime(time_t " time1 ", time_t " time0 );
.fi
.SH Beschreibung
Die \fBdifftime()\fP Funktion gibt die verstrichene Zeit zwischen Zeit \fItime1\fP
und Zeit \fItime0\fP in Sekunden an.  Die beiden Zeiten sind in Kalenderzeiten
angegeben, d.h. die verstrichene Zeit wird ab dem 1. Januar 1970, 00:00:00 Uhr,
nach Koordinierter Weltzeitskala (UTC), gerechnet.
.SH "Konform Zu"
SVID 3, BSD 4.3,ISO 9899 
.SH "Siehe Auch"
.BR date (1),
.BR gettimeofday (2),
.BR time (2),
.BR ctime (3),
.BR gmtime (3),
.BR localtime (3).
