.\"  Copyright (c) 2001 Walter Harms <walter.harms@informatik.uni-oldenburg.de>
.\"
.\"  This program is free software; you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation; version 2 dated June, 1991.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program;  if not, write to the Free Software
.\"  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111, USA.
.\"
.TH dysize 3
.SH NAME
dysize \- berechne die Anzahl der Tage in Jahr
.SH SYNOPSIS
.sp
.BR "#define __USE_MISC"
.br
.BR "#include <time.h>
.sp
.BI "int dysize(year)"
.sp
.SH DESCRIPTION
Die Funktion ergibt 365 fuer normale Jahre und 366 fuer Schaltjahre.
Die Berechnen der Schaltjahren durch:
.br
(year) %4 == 0 && ((year) %100 != 0 || (year) %400 == 0)
.br
Die Formel findet sich im Macro  __isleap(year), welches eberfalls in
<time.h> definiert ist.

.SH "SEE ALSO"
.BR strftime (3),
.BR time (3)
