.\"  Copyright 2001 walter harms (walter.harms@informatik.uni-oldenburg.de)
.TH dysize 3
.SH NAME
dysize \- berechne die Anzahl der Tage in Jahr
.SH SYNOPSIS
.sp
.BR "#define __USE_MISC"
.br
.BR "#include <time.h>
.sp
.BI "int dysize(year)"
.sp
.SH DESCRIPTION
Die Funktion ergibt 365 fuer normale Jahre und 366 fuer Schaltjahre.
Die Berechnen der Schaltjahren durch:
.br
(year) %4 == 0 && ((year) %100 != 0 || (year) %400 == 0)
.br
Die Formel findet sich im Macro  __isleap(year), welches eberfalls in
<time.h> definiert ist.

.SH "SEE ALSO"
.BR strftime (3),
.BR time (3)
