.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:32:25 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into german Wed 1 Jan 13:30:25 1997 by Martin Schulze (joey@linux.de)
.\"
.TH GCVT 3 "1. Januar 1997" "" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
gcvt \- convert a floating-point number to a string.
.SH ÜBERSICHT
.nf
.B #include <stdlib.h>
.sp
.BI "char *gcvt(double " number ", size_t " ndigit ", char *" buf );
.fi
.SH BESCHREIBUNG
Die Funktion
.B gcvt()
wandelt
.I number
in eine NULL-terminierte ASCII-Zeichenkette minimaler Länge um und speichert
diesen in
.IR buf .
Die Funktion erzeugt
.I ndigit
Nachkommastellen im F oder E format von 
.BR printf (3).
.SH RÜCKGABEWERT
Die Funktion
.B gcvt()
gibt die Adresse der Zeichenkette zurück, auf die
.I buf
zeigt.
.SH "SIEHE AUCH"
.BR ecvt (3),
.BR fcvt (3),
.BR sprintf (3).
