.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:29:54 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated to German Thu Oct 31 1996 by Patrick Rother (krd@gulu.net)
.\"
.TH GETGRENT 3  "31. Oktober 1996" "GNU" "Bibliotheksfunktionen"
.SH NAME
getgrent, setgrent, endgrent \- hole Eintrag aus Gruppendatei
.SH ÜBERSICHT
.nf
.B #include <grp.h>
.B #include <sys/types.h>
.sp
.B struct group *getgrent(void);
.sp
.B void setgrent(void);
.sp
.B void endgrent(void);
.fi
.SH BESCHREIBUNG
Die Funktion \fBgetgrent()\fP gibt einen Zeiger auf eine Struktur zurück,
die die Gruppeninformationen aus \fI/etc/group\fP enthält.  Beim ersten Aufruf
gibt sie den ersten Eintrag zurück, danach bei jedem weiteren Aufruf die
folgenden Einträge.
.PP
Die Funktion \fBsetgrent()\fP setzt den Dateizeiger auf den Anfang der
Datei \fI/etc/group\fP zurück.
.PP
Die Funktion \fBendgrent()\fP schließt die Datei
.IR /etc/group .
.PP
Die Struktur \fIgroup\fP ist in \fI<grp.h>\fP wie folgt definiert:
.sp
.RS
.nf
.ta 8n 16n 32n
struct group {
        char    *gr_name;        /* Gruppenname */
        char    *gr_passwd;      /* Gruppenpaßwort */
        gid_t   gr_gid;          /* Gruppenkennung */
        char    **gr_mem;        /* Gruppenmitglieder */
};
.ta
.fi
.RE
.SH "RÜCKGABEWERT"
Die Funktion \fBgetgrent()\fP gibt die Gruppeninformationstuktur zurück,
oder NULL wenn es keine weiteren Einträge mehr gibt oder ein Fehler auftritt.
.SH FEHLER
.TP
.B ENOMEM
Zu wenig Speicher um die Gruppeninformationsstruktur zu belegen.
.SH DATEIEN
.TF
.I /etc/group
Gruppendatenbankdatei
.fi
.SH "KONFORM ZU"
SVID 3, BSD 4.3
.SH "SIEHE AUCH"
.BR fgetgrent (3),
.BR getgrnam (3),
.BR getgrgid (3).
