.\" Copyright (c) 1989, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)getpass.3	6.5 (Berkeley) 5/21/91
.\"
.\" Converted for Linux, Mon Nov 29 14:41:51 1993, faith@cs.unc.edu
.\" Translated into german (16.11.1996) by Andreas D. Preissig <andreas@sanix.ruhr.de>
.\"
.TH PRINTF 3  "29 November 1993" "BSD MANPAGE" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
getpass \- Ein Passwort abfragen
.SH "ÜBERSICHT"
.B #include <pwd.h>
.br
..B #include <unistd.h>
.sp
.B "char *getpass( const char *" prompt );
.SH BESCHREIBUNG
Die Funktion
.B getpass
zeigt einen Prompt auf und liest das Passweort von 
.IR /dev/tty .
Falls auf diese Datei nicht zugegriffen werden kann, schreibt 
.B getpass
den Prompt auf die Standard - Fehler - Ausgabe und liest das Passwort
von der Standardeingabe.
.PP
Das Passwort kann bis zu _PASSWORD_LEN (zur Zeit 128) Zeichen lang sein.
Alle überzähligen Zeichen und das abschliessende Newline - Zeichen werden
verworfen. ( Dies kann unter Linux anders sein .)
.PP
.B Getpass
schaltet das Echo ab, während es ein Passwort einliest.
.PP
.SH "RÜCKGABEWERT"
.B Getpass
gibt einen Zeiger auf das mit einem Null-Zeichen terminierte Passweot zurück.
.SH DATEIEN
.I /dev/tty
.SH "SIEHE AUCH"
.BR crypt (3)
.SH GESCHICHTE
Eine
.B getpass
Funktion erschien in Version 7 AT&T UNIX.
.SH BUGS
Die Funktion 
.B getpass
speichert ihr Resultat in einem internen statischen Objekt und gibt nur den
Zeiger auf dieses Objekt zurück. Weitere Aufrufe von 
.B getpass
werden dieses gleiche Objekt verändern.
.PP
Der aufrufende Prozess sollte das Passwort so schnell wie möglich auf Null
setzen, um zu vermeiden, das das Passwort weiter sichtbar in dem Addressraum
dieses Prozesses ist.


