.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:10:36 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into german (16.11.1996) by Andreas D. Preissig <andreas@sanix.ruhr.de>
.TH INITGROUPS 3  "April 5, 1993" "GNU" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
initgroups \- Initialisieren der zusätzliche Gruppenzugriffsliste
.SH "ÜBERSICHT"
.nf
.B #include <grp.h>
.B #include <sys/types.h>
.sp
.BI "int initgroups(const char *" Benutzer ", gid_t " Gruppe );
.fi
.SH DESCRIPTION
Die Funktion \fBinitgroups()\fP initialisiert die
Gruppenzugriffsliste, indem sie die Gruppendatenbank
\fI/etc/group\fP liest und alle Gruppen benutzt, bei denen der 
\fIBenutzer\fP Mitglied ist.  Die zusätzliche Gruppe \fIGruppe\fP
wird auch an die Liste angehängt.
.SH "RÜCKGABEWERT"
Bei Erfolg gibt die Funktion \fBinitgroups()\fP 0 zurück, bei
Mißerfolg ist der Rückgabewert \-1 .
.SH "FEHLER"
.TP
.B EPERM
Der aufrufende Prozeß hat nicht ausreichende Privilegien.
.TP
.B ENOMEM
Nicht genügend Speicher, um die Gruppeninformationsstruktur anzulegen.
.SH DATEIEN
.nf
/etc/group		Gruppendatenbank
.fi
.SH "KONFORM ZU"
SVID 3, BSD 4.3
.SH "SIEHE AUCH"
.BR getgroups "(2), " setgroups (2)
