.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:08:17 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Translated into German by Ralf Demmer, Translation & Consulting
.\" rdemmer@rdemmer.de, http://www.rdemmer.de, Berlin, 24.05.99
.\"
.TH J0 3 "26. Juni 1993" "GNU" "Bibliotheksfunktionen"
.SH BEZEICHNUNG
j0, j1, jn, y0, y1, yn \- Bessel-Funktionen
.SH "ÜBERSICHT"
.nf
.B #include <math.h>
.sp
.BI "double j0(double " x );
.sp
.BI "double j1(double " x );
.sp
.BI "double jn(int " n ", double " x );
.sp
.BI "double y0(double " x );
.sp
.BI "double y1(double " x );
.sp
.BI "double yn(int " n ", double " x );
.fi
.SH BESCHREIBUNG
Die Funktionen
.B j0()
und
.B j1()
geben die Bessel-Funktion von
.I x
der ersten Art der jeweiligen Ordnung 0 und 1 zurück. Die Funktion
.B jn()
gibt die Bessel-Funktion von
.I x
der ersten Art und der Ordnung
.I n
zurück.
.PP
Die Funktionen
.B y0()
und
.B y1()
geben die Bessel-Funktion von
.I x
der zweiten Art der jeweiligen Ordnung 0 und 1 zurück. Die Funktion
.B yn()
gibt die Bessel-Funktion von
.I x
der zweiten Art und der Ordnung
.I n
zurück.
.PP
Für die Funktionen
.BR y0() ", " y1() " und " yn()
muss der Wert von
.I x
positiv sein. Für negative Werte von
.I x
geben diese Funktionen
\-HUGE_VAL 
zurück.
.SH "KONFORM ZU"
SVID 3, BSD 4.3
.SH BUGS
Es treten Fehler von bis zu 2e\-16 bei den Rückgabewerten von
.BR j0() ", " j1() " und " jn()
im Wertebereich von
.I x
zwischen \-8 und 8 auf.

