.TH BZNEW 1
.SH NAME
bznew \-   recompress .gz or .tgz files to .bz2 files
.SH SYNOPSIS
.B bznew
[ -ftv9PK] [ name.gz ...  ]
.SH DESCRIPTION
.I  Bznew
recompresses files from .gz (gzip) format to .bz2 (bzip2) format.
If you want to recompress a file already in bzip2 format, rename the file
to force a .bz2 extension then apply bznew.
.SH OPTIONS
.TP
.B \-f
Force recompression from .gz to .bz2 format even if a .bz2 file already exists.
.TP
.B \-t
Tests the new files before deleting originals.
.TP
.B \-v
Verbose. Display the name and percentage reduction for each file compressed.
.TP
.B \-9
Use the slowest compression method (optimal compression).
.TP
.B \-P
Use pipes for the conversion to reduce disk space usage.
.TP
.B \-K
Keep a .gz file when it is smaller than the .bz2 file
.SH "SEE ALSO"
bzip2(1), gzip(1)
.SH BUGS
.I Bznew
does not maintain the time stamp with the -P option if
.I cpmod(1)
is not available and
.I touch(1)
does not support the -r option.
