.\" {PTM/PB/0.1/01-06-1999/"drukuj statystyki ppp"}
.\" Translation (c) 1999 Przemek Borys <pborys@dione.ids.pl>
.\"	@(#) $Id: pppstats.8,v 1.3 1999/08/18 08:13:03 wojtek2 Exp $
.TH PPPSTATS 8 "2 Maj 1995"
.SH NAZWA
pppstats \- drukuj statystyki PPP
.SH SKŁADNIA
.B pppstats
.RB [ -v ]
.RB [ -r ]
.RB [ -c ]
.RB [ -i
.IR sec ]
.RI [ unit# ]
.ti 12
.SH OPIS
.B pppstats
drukuje statystyki związane z PPP.
.PP
Flaga
.B -v
powoduje, że
.B pppstats
wyświetla dodatkowe statystyki, takie jak liczba przetossowanych pakietów
(to znaczy, które odrzucił kod dekompresji nagłówka VJ TCP).
.PP
Flaga
.B -r
powoduje, że
.B pppstats
wyświetla ogólny stopień kompresji pakietów. Stopień jest między 0 a 1,
gdzie zero oznacza, że dane są niekompresowalne.
.PP
Flaga
.B -c
jest używana do podawania alternatywnego trybu wyświetlania, który pokazuje
statystyki kompresji pakietów: ilość pakietów i bajtów przed kompresją (lub po
dekompresji), po kompresji, a także niekompresowalnych (pakietów, które nie
skurczyły się podczas kompresji i zostały przetransmitowane w postaci
nieskompresowanej); pokazuje też najaktualniejszy stopień kompresji. Stopień ten
odzwierciedla chwilową wydajność kodu kompresji zamiast ogólnego stopinia,
osiągnięty od włączenia kompresji.
.PP
Flaga
.B -i
jest używana do podawania interwałów między drukami. Domyślnym jest 5
sekund.
.PP
\fIunit#\fR określa, z którego interfejsu generować statystyki.
