.\" Translated into finnish by Sami Louko (slouko@dlc.fi)
.\"
.TH allcm 1 "7. Huhtikuuta 1998" "teTeX" "K‰ytt‰j‰n sovellusohjelmat"
.SH NIMI
allneeded \- pakottaa laskennan kaikille nyt tarvittaville fonteille
.SH "YLEISKATSAUS"
.B allneeded [\-r] tiedostot ...
.SH KUVAUS
.I allneeded
pakottaa laskennan kaikille fonteille joita tarvitaan mink‰ tahansa asiakirjan
esikatseluun /usr tai /home hakemistojen alta.
T‰m‰ tehd‰‰ ajamalla
.IR dvips:in (1)
kautta kaikki avattavat dvi\-tiedostot. N‰inollen, fontit luodaan dvipsin
tarvitsemalla erottelutarkkuudella.

.I allneeded
ei laske jo olemassa olevia fontteja uudelleen (niin kauan kunnes Metafont-moodi
ei muutu).

.SH AUTHOR
Dirk Hillbrecht (dh@informatik.uni\-hannover.de)
.SH "KATSO MY÷S"
alldc(1) allcm(1) fontimport(1) fontexport(1). 
