.\" $Id: $
.\" Translated into Finnish by RenÈ Gauffin (rene.gauffin@lc.fi)
.\"
.TH GROUPS 1 "13. Huhtikuuta 1999" "FSF" "Kıyttıjın sovellusohjelmat"
.SH NIMI
groups \- print the groups a user is in
.SH "YLEISKATSAUS"
.B groups
[k‰ytt‰j‰...]
.br
.B groups
{\-\-help,\-\-version}
.SH KUVAUS
T‰t‰ dokumentaatiota ei en‰‰ yll‰pidet‰ ja se voi olla ep‰t‰sm‰llist‰ tai ep‰t‰ydellist‰.  Texinfosssa oleva dokumentointi on nykyisin viralllnen l‰hdeteksti.
.PP
T‰ll‰ man-sivulla on k‰skyn
.BR groups .
GNU version dokumentointi
.B groups
tulostaa niiden lis‰ryhmien nimet. joihin annettu 
.IR k‰ytt‰j‰ ,
kuuluu, tai jos k‰ytt‰j‰‰ ei ole annettu, ne ryhm‰t johon k‰ynniss‰ oleva prosessi kuuluu.
Jos k‰ytt‰j‰n (tai useamman k‰ytt‰j‰n) nimi on annettu, joka k‰ytt‰j‰n nimi tulostetaan ennen niiden ryhmien nimi‰, joihin kyseinen k‰ytt‰j‰ kuuluu
.PP
Ryhm‰luettelot ovat samat kuin ne jotka tulostuvat k‰skyll‰ `id \-Gn'.
.SS OPTIONS
Kun GNU
.B groups
k‰ynnistet‰‰‰n vain yhdell‰ valitsimella, ohjelma tunnistaa seuraavat:
.TP
.I "\-\-help"
Tulostaa k‰yttˆopasteen vakiotulostimelle ja poistuu ohjelmasta
.TP
.I "\-\-version"
Tulostaa versiotiedot vakiotulostimelle ja poistuu ohjelmasta
.SH "KATSO MY÷S"
 
