.\" $Id: $
.\" Translated into finnish by root (root@rk2)
.\"
.TH LATEX 7 "" "K‰ytt‰j‰n sovellusohjelmat" ""
.\"=====================================================================
.if t .ds TX \fRT\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X\fP
.if n .ds TX TeX
.ie t .ds OX \fIT\v'+0.25m'E\v'-0.25m'X\fP\" for troff
.el .ds OX TeX\" for nroff
.\" the same but obliqued
.\" BX definition must follow TX so BX can use TX
.if t .ds BX \fRB\s-2IB\s0\fP\*(TX
.if n .ds BX BibTeX
.\" LX definition must follow TX so LX can use TX
.if t .ds LX \fRL\\h'-0.36m'\\v'-0.15v'\s-2A\s0\\h'-0.15m'\\v'0.15v'\fP\*(TX
.if n .ds LX LaTeX
.\"=====================================================================
.SH NIMI
latex \- rakenteellinen tekstin muotoilu ja ladonta
.SH "YLEISKATSAUS"
.B latex
[ ensimm‰inen rivi ]
.\"=====================================================================
.SH KUVAUS
\*(LX-kieli on kuvattu kirjassa 
.IR "\*(LX \- A Document Preparation System" .
\*(LX on \*(TX-makropaketti, eik‰ muunnelma \*(TX-ohjelmasta
joten kaikki
.BR tex (1):ss‰
kuvatut ominaisuudet ovat k‰ytett‰viss‰.
.PP
\*(LX-makrot rohkaisevat kirjoittajaa ajattelemaan dokumenttinsa sis‰ltˆ‰
muodon sijaan. Vaikeasti saavutettavissa oleva ihanne on, ett‰ kirjoittajan
ei tarvitsisi k‰ytt‰‰ mink‰‰nlaisia muotoilukomentoja dokumenteissaan (
kuten ``vaihda kursiiville'' tai ``hypp‰‰ kahden pisteen yli''), vaan kaikki
tehd‰‰n spesifisill‰ merkint‰komennoilla: ``painota'', ``aloita kappale''.
.PP
\*(LX:n p‰‰asiallinen dokumentaation l‰hde on \*(LX-manuaali
joka mainitaan alla, ja paikallinen opas tiedostossa
.I local-guide.tex 
tai
.I local.tex
tai jokin vastaava, yleens‰ hakemistossa /usr/lib/texmf/temxf/tex.
.\"=====================================================================
.SH "KATSO MY÷S"
.BR amslatex (1),
.BR amstex (1),
.BR slitex (1),
.BR tex (1),
.br
Leslie Lamport,
.IR "\*(LX \- A Document Preparation System" ,
Addison-Wesley, 1985, ISBN 0-201-15790-X.
