.if n \{\
.	ds ct "
.\}
.if t \{\
.	ds ct \\(co
.\}
.\" Translated into finnish by Juha-Pekka Syrj‰l‰ (jsyrjala@iki.fi)
.\"
.TH MESSAGES 1 "7. Huhtikuuta 1998" "USENET Community Trust" "K‰ytt‰j‰n sovellusohjelmat"
.SH NIMI
messages - nopea lasku mailien lukum‰‰r‰st‰ postilaatikossa tai kansiossa
.SH "YLEISKATSAUS"
.B messages
.br
.B messages
kansionnimi
.SH KUVAUS
.I Messages
laskee rivit, jotka sis‰lt‰v‰t "^From\ " kohdan joko inboxista
tai annetusta kansiosta.
.P
Faktana, t‰m‰ on pieni shelli skripta!!
.SH AUTHOR
Elm Development Group
.SH "KATSO MY÷S"
from(1L), elm(1L)
.SH BUGIT
El‰ ole typer‰...
.SH BUG REPORTS TO
Syd Weinstein	elm@DSI.COM	(dsinc!elm)
.SH COPYRIGHTS
\fB\*(ct\fRCopyright 1988-1992 by The USENET Community Trust
.br
Johdettu Elm 2.0:sta, \fB\*(ct\fR Copyright 1986, 1987 by Dave Taylor
.SH "KATSO MY÷S"
