.\" $Id: $
..\" Copyright (c) 1983, 1997 Eric P. Allman
.\" Copyright (c) 1985, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)newaliases.1	8.5 (Berkeley) 2/1/97
.\"
.Dd February 1, 1997
.\" Translated into finnish by Lasse Heikkilä (raccoon@sci.fi)
.\"
.TH NEWALIASES 7 "" "Käyttäjän sovellusohjelmat" ""
.Os BSD 4
.SH NIMI
.Nm newaliases
.Nd uudelleenrakentaa tietokannan postialiastiedostoa varten
.SH "YLEISKATSAUS"
.Nm newaliases
.SH KUVAUS
.Nm Newaliases
rakentaa hajasaantitietokannan postialiastiedostolle
.Pa /etc/aliases .
Se täytyy suorittaa joka kerta kun tätä tiedostoa muutetaan jotta muutos
tulisi voimaan.
.Pp
.Nm Newaliases
on identtinen komennon 
.Dq Li "sendmail -bi" 
kanssa.
.Pp
Apuohjelma
.Nm newaliases
palauttaa 0 onnistuessaan, ja >0 mikäli virhe kohdataan.
.SH TIEDOSTOT
.Bl -tag -width /etc/aliases -compact
.It Pa /etc/aliases
Postialiastiedosto
.El
.SH "KATSO MYÖS"
.Xr aliases 5 ,
.Xr sendmail 8
.SH HISTORIA
Komento
.Nm newaliases
ilmestyi
.Bx 4.0 :ssä.
