.\" $Id: $
.\" Translated into finish by Tuukka Forssell (taf@jytol.fi)
.\"
.TH RDATE 3 "7. Huhtikuuta 1998" "" "Käyttäjän sovellusohjelmat"
.CM 1
.SH NIMI
rdate \- hakee päiväyksen ja ajan verkosta
.SH "YLEISKATSAUS"
.B rdate
[\-p] [\-s] [palvelin...]
.SH KUVAUS
.B Rdate
käyttää TCP:tä vastaanottaakseen ajan etäpalvelimesta käyttäen protokollaa,
joka on kuvattu RFC 868:ssa. Komento palauttaa jokaisen halutun
palvelimen ajan ctime(3) formaatissa. Seuraavassa esimerkki:
.nf
.IP ""
% rdate uci mc
[uci]   Sun Mar 24 20:35:41 1985
[mc]    Sun Mar 24 20:36:19 1985
.fi
.SS OPTIONS
.TP
.I \-p
Tulostaa etäkoneen ajan näytölle. (oletusarvo)
.TP
.I \-s
Root käyttäjä voi asettaa palautetun ajan oman koneen systeemikelloon.  
.SH TIEDOSTOT
.nf
/etc/services	socket numeroita vastaavien palveluiden nimet
/etc/hosts	palvelimien nimiä vastaavat internet osoitteet
.fi
.SH HISTORIA
.TP
24. maaliskuuta 1985 Lee Moore (University of Rochester)
.TP
10. lokakuuta 1994 Andy Tefft <teffta@crypt.erie.ge.com>
päivitti Linux versiolle 1.1.52. Asettaa systeemi kellon roottina ajettaessa.
.TP
23. syyskuuta 1996  Richard Henderson <rth@tamu.edu>
Korjasi 32-bittisen oletuksen ja lisäsi moodi optiot.
.SH "KATSO MYÖS"
