.\" $Id: $
.\" Translated into Finnish by Tommi Vainikainen (mucus@pcuf.fi)
.\"
.TH zplay 7 "" "Käyttäjän sovellusohjelmat" ""
.IX zplay
.SH NIMI
zplay \- ohjelma modeemin äänitiedostojen nauhoittamiseen ja soittamiseen
.sp 0
.SH KUVAUS
\fBzplay\fP on vanhentunut. Käytä mieluummin uutta \fBvm\fP-ohjelmaa.
.SH TEKIJÄ
Original version from Klaus Weidner.
Copyright (C) 1995 by Marc Eberhard <Marc.Eberhard@Uni-Duesseldorf.DE>
.SH "KATSO MYÖS"
