'\" t
.\"     Title: arch-nspawn
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/12/2022
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ARCH\-NSPAWN" "1" "10/12/2022" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
arch-nspawn \- Run a command or OS in a light\-weight namespace container
.SH "SYNOPSIS"
.sp
arch\-nspawn [options] working\-dir [systemd\-nspawn arguments]
.SH "DESCRIPTION"
.sp
\fIarch\-nspawn\fR is a wrapper around systemd\-nspawn to run command or OS in a namespace container such as a directory including base utilities of a OS\&. It is used to build package(s) in given clean and defined environment\&.
.SH "OPTIONS"
.PP
\fB\-C\fR <file>
.RS 4
Location of a pacman config file
.RE
.PP
\fB\-M\fR <file>
.RS 4
Location of a makepkg config file
.RE
.PP
\fB\-c\fR <dir>
.RS 4
Set pacman cache, if no directory is specified the passed pacman\&.conf\(cqs cachedir is used with a fallback to
\fI/etc/pacman\&.conf\fR
.RE
.PP
\fB\-f\fR <file>
.RS 4
Copy file from the host to the chroot
.RE
.PP
\fB\-s\fR
.RS 4
Do not run setarch
.RE
.PP
\fB\-h\fR
.RS 4
Show this usage message
.RE
.SH "BUGS"
.sp
Bugs can be reported on the project\(cqs GitLab bug tracker \fIhttps://gitlab\&.archlinux\&.org/archlinux/devtools\fR
.SH "AUTHORS"
.sp
Maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aaron Griffin <aaronmgriffin@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Allan McRae <allan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Bartłomiej Piotrowski <bpiotrowski@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dan McGee <dan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dave Reisner <dreisner@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Evangelos Foutras <evangelos@foutrelis\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Jan Alexander Steffens (heftig) <jan\&.steffens@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Jelle van der Waa <jelle@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Levente Polyak <anthraxx@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pierre Schmitz <pierre@archlinux\&.de>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Sébastien Luttringer <seblu@seblu\&.net>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Sven\-Hendrik Haase <svenstaro@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Thomas Bächler <thomas@archlinux\&.org>
.RE
.sp
For additional contributors, use git shortlog \-s on the devtools\&.git repository\&.
