'\" t
.\"     Title: netctl-auto
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/06/2022
.\"    Manual: \ \&
.\"    Source: \ \& 1.28
.\"  Language: English
.\"
.TH "NETCTL\-AUTO" "1" "03/06/2022" "\ \& 1\&.28" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
netctl-auto \- Control automatic selection of wireless netctl profiles
.SH "SYNOPSIS"
.sp
\fBnetctl\-auto\fR {\fBCOMMAND\fR} \&...
.sp
\fBnetctl\-auto\fR [\-\-help | \-\-version]
.SH "DESCRIPTION"
.sp
\fBnetctl\-auto\fR may be used to control the automatic network profile selection offered by the \fInetctl\-auto@\&.service\fR file\&. See \fBnetctl\&.special\fR(7) for details about the service file\&.
.SH "OPTIONS"
.sp
The following commands are understood:
.PP
\fBlist\fR
.RS 4
List all profiles which are currently available for automatic selection\&. Active profiles will be marked with a \(oq*\(cq, disabled profiles will be marked with a \(oq!\(cq\&.
.RE
.PP
\fBswitch\-to [\fR\fBPROFILE\fR\fB]\fR
.RS 4
Switch to the network profile specified on the command line\&. The specified profile will be enabled if necessary, the state of all other profiles is not changed\&. This command does not force
\fBnetctl\-auto\fR
to use the specified profile\&. If a disconnect occurs,
\fBnetctl\-auto\fR
may select an alternative profile\&.
.RE
.PP
\fBis\-active [\fR\fBPROFILE\fR\fB]\fR
.RS 4
Check whether the network profile specified on the command line is active\&. Prints the current state\&.
.RE
.PP
\fBenable [\fR\fBPROFILE\fR\fB]\fR
.RS 4
Enable a previously disabled network profile for automatic selection\&. Every time the
\fBnetctl\-auto\fR
service is started, all available profiles are enabled by default\&.
.RE
.PP
\fBdisable [\fR\fBPROFILE\fR\fB]\fR
.RS 4
Disable the specified profile for automatic selection\&. This will only take effect until the
\fBnetctl\-auto\fR
service is stopped\&. To permanently exclude a profile from automatic selection, use the
\fIExcludeAuto=yes\fR
option in the profile\&.
.RE
.PP
\fBenable\-all\fR
.RS 4
Enable all profiles for automatic selection\&.
.RE
.PP
\fBdisable\-all\fR
.RS 4
Disable all profiles for automatic selection\&.
.RE
.PP
\fBis\-enabled [\fR\fBPROFILE\fR\fB]\fR
.RS 4
Check whether the specified profile is enabled for the
\fBnetctl\-auto\fR
service that is currently running\&. Prints the current enable status\&.
.RE
.PP
\fBstart [\fR\fBINTERFACE\fR\fB]\fR
.RS 4
Start automatic profile selection on the specified interface\&.

This command should not be invoked directly, use the following command instead:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
    systemctl start netctl\-auto@<interface>
.fi
.if n \{\
.RE
.\}
.PP
\fBstop [\fR\fBINTERFACE\fR\fB]\fR
.RS 4
Stop automatic profile selection on the specified interface\&. This will disconnect the currently active profile on the interface\&.

This command should not be invoked directly, use the following command instead:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
    systemctl stop netctl\-auto@<interface>
.fi
.if n \{\
.RE
.\}
.SH "EXIT STATUS"
.sp
On success 0 is returned, a non\-zero failure code otherwise\&.
.SH "ENVIRONMENT"
.PP
\fI$NETCTL_DEBUG\fR
.RS 4
If set to
"yes", debugging output is generated\&.
.RE
.SH "SEE ALSO"
.sp
\fBnetctl\fR(1), \fBnetctl\&.profile\fR(5), \fBnetctl\&.special\fR(7)
