'\" t
.\"     Title: offload-build
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/12/2022
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OFFLOAD\-BUILD" "1" "10/12/2022" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
offload-build \- Build a PKGBUILD on a remote server using makechrootpkg
.SH "SYNOPSIS"
.sp
offload\-build [OPTIONS] \(em [ARCHBUILD_OPTIONS]
.SH "DESCRIPTION"
.sp
Build a PKGBUILD on a remote server using makechrootpkg\&. Requires a remote user that can run archbuild in a non\-interactive manner, e\&.g\&. must be able to elevate permissions using passwordless sudo\&.
.SH "OPTIONS"
.PP
\fB\-r, \-\-repo\fR <reponame>
.RS 4
Build against a specific repository\&. The default is
extra, to build packages using the stable repositories via extra\-x86_64\-build\&.
.RE
.PP
\fB\-a, \-\-arch\fR <architecture>
.RS 4
Build against a specific architecture\&. The default is
x86_64, the only architecture officially supported by Arch Linux\&.
.RE
.PP
\fB\-s, \-\-server\fR <hostname>
.RS 4
Offload to a specific build server\&. The default is build\&.archlinux\&.org which is used as part of the build toolchain for the official Arch Linux repos\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Show a help text\&.
.RE
.SH "PASSING OPTIONS TO ARCHBUILD"
.sp
Options after a delimiting \(em are passed on to archbuild on the remote\&. archbuild in turn supports passing arguments on to makechrootpkg, which in turn supports passing options to makepkg\&. Since each uses \(em to delimit options that are forwarded, make sure to escape them properly:
.sp
.if n \{\
.RS 4
.\}
.nf
`offload\-build offload\-args \-\- archbuild\-args \-\- makechrootpkg\-args \-\- makepkg\-args`
.fi
.if n \{\
.RE
.\}
.sp
Example: To use a second testing\-x86_64\-build instance with another copydir:
.sp
.if n \{\
.RS 4
.\}
.nf
`offload\-build \-r testing \-\- \-\- \-l <chroot_copy>`
.fi
.if n \{\
.RE
.\}
.SH "BUGS"
.sp
Bugs can be reported on the project\(cqs GitLab bug tracker \fIhttps://gitlab\&.archlinux\&.org/archlinux/devtools\fR
.SH "AUTHORS"
.sp
Maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aaron Griffin <aaronmgriffin@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Allan McRae <allan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Bartłomiej Piotrowski <bpiotrowski@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dan McGee <dan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dave Reisner <dreisner@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Evangelos Foutras <evangelos@foutrelis\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Jan Alexander Steffens (heftig) <jan\&.steffens@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Jelle van der Waa <jelle@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Levente Polyak <anthraxx@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pierre Schmitz <pierre@archlinux\&.de>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Sébastien Luttringer <seblu@seblu\&.net>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Sven\-Hendrik Haase <svenstaro@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Thomas Bächler <thomas@archlinux\&.org>
.RE
.sp
For additional contributors, use git shortlog \-s on the devtools\&.git repository\&.
