'\" t
.\"     Title: sogrep
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/12/2022
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SOGREP" "1" "10/12/2022" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sogrep \- Find shared library links in an Arch Linux repository
.SH "SYNOPSIS"
.sp
sogrep [options] repo libname
.SH "DESCRIPTION"
.sp
Check the soname links database for Arch Linux repositories containing packages linked to a given shared library\&. If the repository specified is "all", then all repositories will be searched, otherwise only the named repository will be searched\&.
.sp
If the links database does not exist, it will be downloaded first\&.
.SH "OPTIONS"
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Provide detailed output containing the matched links for each package, the repository it came from (in the event that all repositories are being searched), and, in combination with
\-r, a progress bar for the links database download\&.
.RE
.PP
\fB\-r, \-\-refresh\fR
.RS 4
Refresh the links databases
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Show a help text
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
\fBSOLINKS_MIRROR\fR="https://mirror\&.foo\&.com" Alternative mirror to use for downloading soname links database\&.
.PP
\fBSOCACHE_DIR\fR="/path/to/directory"
.RS 4
Directory where soname links database is stored, overrides the default directory set by the
\fBXDG_CACHE_HOME\fR
environment variable or the
\fBHOME\fR
environment variable if
\fBXDG_CACHE_HOME\fR
is not set\&.
.RE
.SH "BUGS"
.sp
Bugs can be reported on the project\(cqs GitLab bug tracker \fIhttps://gitlab\&.archlinux\&.org/archlinux/devtools\fR
.SH "AUTHORS"
.sp
Maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aaron Griffin <aaronmgriffin@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Allan McRae <allan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Bartłomiej Piotrowski <bpiotrowski@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dan McGee <dan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dave Reisner <dreisner@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Evangelos Foutras <evangelos@foutrelis\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Jan Alexander Steffens (heftig) <jan\&.steffens@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Jelle van der Waa <jelle@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Levente Polyak <anthraxx@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pierre Schmitz <pierre@archlinux\&.de>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Sébastien Luttringer <seblu@seblu\&.net>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Sven\-Hendrik Haase <svenstaro@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Thomas Bächler <thomas@archlinux\&.org>
.RE
.sp
For additional contributors, use git shortlog \-s on the devtools\&.git repository\&.
