'\" t
.\"     Title: wifi-menu
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/06/2022
.\"    Manual: \ \&
.\"    Source: \ \& 1.28
.\"  Language: English
.\"
.TH "WIFI\-MENU" "1" "03/06/2022" "\ \& 1\&.28" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wifi-menu \- Interactively connect to a wireless network
.SH "SYNOPSIS"
.sp
\fBwifi\-menu\fR [\-o | \-\-obscure] [INTERFACE]
.sp
\fBwifi\-menu\fR [\-h | \-\-help]
.SH "DESCRIPTION"
.sp
\fBwifi\-menu\fR allows to interactively connect to a wireless network on INTERFACE using a netctl profile\&. In case no netctl profile is available, one can be generated\&. If only one wireless interface is available, INTERFACE can be omitted\&.
.sp
\fBwifi\-menu\fR is only able to generate netctl profiles for simple network configurations\&. Profiles for more complex configurations must be set up manually\&. See \fBnetctl\&.profile\fR(5) for more information\&.
.SH "OPTIONS"
.PP
\-h, \-\-help
.RS 4
Print a short help text and exit\&.
.RE
.PP
\-o, \-\-obscure
.RS 4
Show asterisks for the characters of the password and store the password as a hexadecimal pre\-shared key\&.
.RE
.PP
INTERFACE
.RS 4
The wireless network interface to use for connecting\&.
.RE
.SH "EXIT STATUS"
.PP
0
.RS 4
The interface connected to the wireless network successfully\&.
.RE
.PP
1
.RS 4
The connection attempt was canceled\&.
.RE
.PP
2
.RS 4
The connection attempt failed\&.
.RE
.PP
3
.RS 4
No wireless networks were found\&.
.RE
.PP
4
.RS 4
Invalid passphrase length (WEP
keys must be between 8 and 63 characters in length)\&.
.RE
.PP
7
.RS 4
An unexpected error code was received\&.
.RE
.PP
255
.RS 4
The command was invalid or the connection attempt was aborted\&.
.RE
.SH "NOTES"
.sp
Establishing a connection may take a minute\&. While establishing a connection, nothing is shown on screen\&.
.sp
Starting a connection on an interface that is controlled by \fBnetctl\-auto\fR will cause \fBwifi\-menu\fR to switch to the selected network\&. The interface will continue to be controlled by \fBnetctl\-auto\fR\&.
.SH "ENVIRONMENT"
.PP
\fI$NETCTL_DEBUG\fR
.RS 4
If set to
"yes", debugging output is generated\&.
.RE
.SH "FILES"
.PP
\fI/etc/netctl\fR
.RS 4
Directory where generated profiles are stored\&.
.RE
.SH "SEE ALSO"
.sp
\fBnetctl\fR(1), \fBnetctl\-auto\fR(1)
